// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package strategy

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type StrategyStatus string

const (
	StrategyStatusDraft    StrategyStatus = "draft"
	StrategyStatusActive   StrategyStatus = "active"
	StrategyStatusInactive StrategyStatus = "inactive"
)

func (e *StrategyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StrategyStatus(s)
	case string:
		*e = StrategyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StrategyStatus: %T", src)
	}
	return nil
}

type NullStrategyStatus struct {
	StrategyStatus StrategyStatus
	Valid          bool // Valid is true if StrategyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStrategyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StrategyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StrategyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStrategyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StrategyStatus), nil
}

func (e StrategyStatus) Valid() bool {
	switch e {
	case StrategyStatusDraft,
		StrategyStatusActive,
		StrategyStatusInactive:
		return true
	}
	return false
}

func AllStrategyStatusValues() []StrategyStatus {
	return []StrategyStatus{
		StrategyStatusDraft,
		StrategyStatusActive,
		StrategyStatusInactive,
	}
}

type Strategy struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Status      StrategyStatus `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   *time.Time     `json:"deleted_at"`
}
