// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package positions

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PositionSide string

const (
	PositionSideLONG  PositionSide = "LONG"
	PositionSideSHORT PositionSide = "SHORT"
)

func (e *PositionSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PositionSide(s)
	case string:
		*e = PositionSide(s)
	default:
		return fmt.Errorf("unsupported scan type for PositionSide: %T", src)
	}
	return nil
}

type NullPositionSide struct {
	PositionSide PositionSide
	Valid        bool // Valid is true if PositionSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPositionSide) Scan(value interface{}) error {
	if value == nil {
		ns.PositionSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PositionSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPositionSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PositionSide), nil
}

func (e PositionSide) Valid() bool {
	switch e {
	case PositionSideLONG,
		PositionSideSHORT:
		return true
	}
	return false
}

func AllPositionSideValues() []PositionSide {
	return []PositionSide{
		PositionSideLONG,
		PositionSideSHORT,
	}
}

type Position struct {
	AccountID  string         `json:"account_id"`
	Exchange   string         `json:"exchange"`
	Symbol     string         `json:"symbol"`
	Side       PositionSide   `json:"side"`
	Qty        pgtype.Numeric `json:"qty"`
	EntryPrice pgtype.Numeric `json:"entry_price"`
	Leverage   int32          `json:"leverage"`
	UpdatedTs  time.Time      `json:"updated_ts"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
