// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package kv

import (
	"time"
)

type Kv struct {
	ID        int64     `json:"id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
