// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package kv

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const getByKey = `-- name: GetByKey :one
SELECT id, key, value, created_at, updated_at FROM public.kv WHERE key = $1
`

// -- cache: 60s
// -- timeout: 3s
func (q *Queries) GetByKey(ctx context.Context, key string) (*Kv, error) {
	return _GetByKey(ctx, q.AsReadOnly(), key)
}

func (q *ReadOnlyQueries) GetByKey(ctx context.Context, key string) (*Kv, error) {
	return _GetByKey(ctx, q, key)
}

func _GetByKey(ctx context.Context, q CacheQuerierConn, key string) (*Kv, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	q.GetConn().CountIntent("kv.GetByKey")
	dbRead := func() (any, time.Duration, error) {
		cacheDuration := time.Duration(time.Millisecond * 60000)
		row := q.GetConn().WQueryRow(qctx, "kv.GetByKey", getByKey, key)
		var i *Kv = new(Kv)
		err := row.Scan(
			&i.ID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if err == pgx.ErrNoRows {
			return (*Kv)(nil), cacheDuration, nil
		}
		return i, cacheDuration, err
	}
	if q.GetCache() == nil {
		i, _, err := dbRead()
		return i.(*Kv), err
	}

	var i *Kv
	err := q.GetCache().GetWithTtl(qctx, "kv:GetByKey:"+hashIfLong(fmt.Sprintf("%+v", key)), &i, dbRead, false, false)
	if err != nil {
		return nil, err
	}

	return i, err
}

const upsert = `-- name: Upsert :one
INSERT INTO public.kv (key, value)
VALUES ($1,
        $2)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = now()
returning id, key, value, created_at, updated_at
`

type UpsertParams struct {
	Key   string
	Value string
}

// -- invalidate: [GetByKey]
// -- timeout: 1s
func (q *Queries) Upsert(ctx context.Context, arg UpsertParams, getByKey *string) (*Kv, error) {
	return _Upsert(ctx, q, arg, getByKey)
}

func _Upsert(ctx context.Context, q CacheWGConn, arg UpsertParams, getByKey *string) (*Kv, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "kv.Upsert", upsert, arg.Key, arg.Value)
	var i *Kv = new(Kv)
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Kv)(nil), nil
	} else if err != nil {
		return nil, err
	}

	// invalidate
	_ = q.GetConn().PostExec(func() error {
		anyErr := make(chan error, 1)
		var wg sync.WaitGroup
		wg.Add(1)
		go func() {
			defer wg.Done()
			if getByKey != nil {
				key := "kv:GetByKey:" + hashIfLong(fmt.Sprintf("%+v", (*getByKey)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		wg.Wait()
		close(anyErr)
		return <-anyErr
	})
	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,key,value,created_at,updated_at FROM \"kv\" ORDER BY id,key,value,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "kv.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kv
	for rows.Next() {
		var v Kv
		if err := rows.Scan(&v.ID, &v.Key, &v.Value, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"kv\" (id,key,value,created_at,updated_at) VALUES ($1,$2,$3,$4,$5);"
	rows := make([]Kv, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "kv.Load", sql, row.ID, row.Key, row.Value, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
