// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package alert_event

import (
	"github.com/stumble/dcache"
	"github.com/stumble/wpgx"
)

// BeforeDump allows you to edit result before dump.
type BeforeDump func(m *Alert)

type CacheQuerierConn interface {
	GetCache() *dcache.DCache
	GetConn() wpgx.WQuerier
}

type CacheWGConn interface {
	GetCache() *dcache.DCache
	GetConn() wpgx.WGConn
}

func New(db wpgx.WGConn, cache *dcache.DCache) *Queries {
	return &Queries{db: db, cache: cache}
}

type Queries struct {
	db    wpgx.WGConn
	cache *dcache.DCache
}

var _ CacheWGConn = (*Queries)(nil)

func (q *Queries) GetCache() *dcache.DCache {
	return q.cache
}

func (q *Queries) GetConn() wpgx.WGConn {
	return q.db
}

func (q *Queries) AsReadOnly() *ReadOnlyQueries {
	return &ReadOnlyQueries{
		db:    q.db,
		cache: q.cache,
	}
}

func (q *Queries) WithTx(tx *wpgx.WTx) *Queries {
	return &Queries{
		db:    tx,
		cache: q.cache,
	}
}

func (q *Queries) WithCache(cache *dcache.DCache) *Queries {
	return &Queries{
		db:    q.db,
		cache: cache,
	}
}

func (q *Queries) UseReplica(replicaQuerier wpgx.WQuerier) *ReadOnlyQueries {
	return &ReadOnlyQueries{
		db:    replicaQuerier,
		cache: q.cache,
	}
}

type ReadOnlyQueries struct {
	db    wpgx.WQuerier
	cache *dcache.DCache
}

var _ CacheQuerierConn = (*ReadOnlyQueries)(nil)

func (q *ReadOnlyQueries) WithCache(cache *dcache.DCache) *ReadOnlyQueries {
	return &ReadOnlyQueries{
		db:    q.db,
		cache: cache,
	}
}

func (q *ReadOnlyQueries) GetCache() *dcache.DCache {
	return q.cache
}

func (q *ReadOnlyQueries) GetConn() wpgx.WQuerier {
	return q.db
}

var Schema = `
create type public.alert_frequency_t as enum ('repeat', 'once');
create type public.alert_status_t as enum ('active', 'error');
create type public.alert_window_t as enum ('5m', '1h', '4h', '24h');

create table if not exists public.alert
(
    id                varchar(64) primary key,
    exchange          varchar(32)                         not null,
    symbol            varchar(64)                         not null,
    type              varchar(64)                         not null,
    frequency         public.alert_frequency_t            not null,
    price             decimal(32, 12),
    alert_window      public.alert_window_t,
    percent           decimal(32, 12),
    remark            text,
    cooldown_seconds  integer                  default 60 not null,
    status            public.alert_status_t    default 'active' not null,
    last_triggered_at timestamp with time zone,
    trigger_count     bigint                   default 0 not null,
    created_at        timestamp with time zone default now() not null,
    updated_at        timestamp with time zone default now() not null,
    deleted_at        timestamp with time zone
);

alter table public.alert
    add column if not exists deleted_at timestamp with time zone;

drop index if exists uq_alert_unique_rule;
create unique index if not exists uq_alert_unique_rule on public.alert (
    exchange,
    symbol,
    type,
    frequency,
    price,
    alert_window,
    percent
) nulls not distinct
where deleted_at is null;

drop index if exists idx_alert_exchange_symbol;
create index if not exists idx_alert_exchange_symbol on public.alert (exchange, symbol)
where deleted_at is null;

drop index if exists idx_alert_status;
create index if not exists idx_alert_status on public.alert (status)
where deleted_at is null;

`
