// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package bot

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const countBots = `-- name: CountBots :one
SELECT COUNT(*) FROM bots
WHERE ($1::INT IS NULL OR id = $1)
  AND ($2::VARCHAR IS NULL OR strategy_id = $2)
  AND ($3::run_mode IS NULL OR mode = $3)
  AND ($4::bot_status IS NULL OR status = $4)
  AND ($5::VARCHAR IS NULL OR exchange = $5)
  AND ($6::VARCHAR IS NULL OR account_id = $6)
  AND ($7::VARCHAR IS NULL OR name LIKE '%' || $7 || '%')
  AND ($8::TIMESTAMPTZ IS NULL OR created_at >= $8)
  AND ($9::TIMESTAMPTZ IS NULL OR created_at <= $9)
  AND deleted_at IS NULL
`

type CountBotsParams struct {
	ID             *int32
	StrategyID     *string
	Mode           NullRunMode
	Status         NullBotStatus
	Exchange       *string
	AccountID      *string
	Name           *string
	CreatedAtStart *time.Time
	CreatedAtEnd   *time.Time
}

// -- timeout: 1s
func (q *Queries) CountBots(ctx context.Context, arg CountBotsParams) (*int64, error) {
	return _CountBots(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) CountBots(ctx context.Context, arg CountBotsParams) (*int64, error) {
	return _CountBots(ctx, q, arg)
}

func _CountBots(ctx context.Context, q CacheQuerierConn, arg CountBotsParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("bot.CountBots")
	row := q.GetConn().WQueryRow(qctx, "bot.CountBots", countBots,
		arg.ID,
		arg.StrategyID,
		arg.Mode,
		arg.Status,
		arg.Exchange,
		arg.AccountID,
		arg.Name,
		arg.CreatedAtStart,
		arg.CreatedAtEnd)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const createBot = `-- name: CreateBot :one
INSERT INTO bots (
    strategy_id,
    strategy_version,
    account_id,
    exchange,
    mode,
    name,
    "desc",
    config,
    symbols,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at
`

type CreateBotParams struct {
	StrategyID      string
	StrategyVersion string
	AccountID       string
	Exchange        string
	Mode            RunMode
	Name            string
	Desc            string
	Config          []byte
	Symbols         []string
	Status          BotStatus
}

// -- timeout: 1s
func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (*Bot, error) {
	return _CreateBot(ctx, q.AsReadOnly(), arg)
}

func _CreateBot(ctx context.Context, q CacheQuerierConn, arg CreateBotParams) (*Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "bot.CreateBot", createBot,
		arg.StrategyID,
		arg.StrategyVersion,
		arg.AccountID,
		arg.Exchange,
		arg.Mode,
		arg.Name,
		arg.Desc,
		arg.Config,
		arg.Symbols,
		arg.Status)
	var i *Bot = new(Bot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.StrategyVersion,
		&i.AccountID,
		&i.Exchange,
		&i.Mode,
		&i.Name,
		&i.Desc,
		&i.Symbols,
		&i.Config,
		&i.Storage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Bot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const deleteBot = `-- name: DeleteBot :one
UPDATE bots
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status != 'running' AND deleted_at is null
RETURNING id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at
`

// -- timeout: 1s
func (q *Queries) DeleteBot(ctx context.Context, id int32) (*Bot, error) {
	return _DeleteBot(ctx, q.AsReadOnly(), id)
}

func _DeleteBot(ctx context.Context, q CacheQuerierConn, id int32) (*Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "bot.DeleteBot", deleteBot, id)
	var i *Bot = new(Bot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.StrategyVersion,
		&i.AccountID,
		&i.Exchange,
		&i.Mode,
		&i.Name,
		&i.Desc,
		&i.Symbols,
		&i.Config,
		&i.Storage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Bot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getBot = `-- name: GetBot :one
SELECT id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at FROM bots
WHERE id = $1
AND deleted_at is null
`

// -- timeout: 1s
func (q *Queries) GetBot(ctx context.Context, id int32) (*Bot, error) {
	return _GetBot(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetBot(ctx context.Context, id int32) (*Bot, error) {
	return _GetBot(ctx, q, id)
}

func _GetBot(ctx context.Context, q CacheQuerierConn, id int32) (*Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("bot.GetBot")
	row := q.GetConn().WQueryRow(qctx, "bot.GetBot", getBot, id)
	var i *Bot = new(Bot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.StrategyVersion,
		&i.AccountID,
		&i.Exchange,
		&i.Mode,
		&i.Name,
		&i.Desc,
		&i.Symbols,
		&i.Config,
		&i.Storage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Bot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getBotByAccountID = `-- name: GetBotByAccountID :one
SELECT id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at FROM bots
WHERE account_id = $1
AND deleted_at is null
`

// -- timeout: 1s
func (q *Queries) GetBotByAccountID(ctx context.Context, accountID string) (*Bot, error) {
	return _GetBotByAccountID(ctx, q.AsReadOnly(), accountID)
}

func (q *ReadOnlyQueries) GetBotByAccountID(ctx context.Context, accountID string) (*Bot, error) {
	return _GetBotByAccountID(ctx, q, accountID)
}

func _GetBotByAccountID(ctx context.Context, q CacheQuerierConn, accountID string) (*Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("bot.GetBotByAccountID")
	row := q.GetConn().WQueryRow(qctx, "bot.GetBotByAccountID", getBotByAccountID, accountID)
	var i *Bot = new(Bot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.StrategyVersion,
		&i.AccountID,
		&i.Exchange,
		&i.Mode,
		&i.Name,
		&i.Desc,
		&i.Symbols,
		&i.Config,
		&i.Storage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Bot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const listBots = `-- name: ListBots :many
SELECT id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at FROM bots
WHERE ($1::INT IS NULL OR id = $1)
  AND ($2::VARCHAR IS NULL OR strategy_id = $2)
  AND ($3::run_mode IS NULL OR mode = $3)
  AND ($4::bot_status IS NULL OR status = $4)
  AND ($5::VARCHAR IS NULL OR exchange = $5)
  AND ($6::VARCHAR IS NULL OR account_id = $6)
  AND ($7::VARCHAR IS NULL OR name LIKE '%' || $7 || '%')
  AND ($8::TIMESTAMPTZ IS NULL OR created_at >= $8)
  AND ($9::TIMESTAMPTZ IS NULL OR created_at <= $9)
  AND deleted_at is null
ORDER BY created_at DESC
`

type ListBotsParams struct {
	ID             *int32
	StrategyID     *string
	Mode           NullRunMode
	Status         NullBotStatus
	Exchange       *string
	AccountID      *string
	Name           *string
	CreatedAtStart *time.Time
	CreatedAtEnd   *time.Time
}

// -- timeout: 1s
func (q *Queries) ListBots(ctx context.Context, arg ListBotsParams) ([]Bot, error) {
	return _ListBots(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListBots(ctx context.Context, arg ListBotsParams) ([]Bot, error) {
	return _ListBots(ctx, q, arg)
}

func _ListBots(ctx context.Context, q CacheQuerierConn, arg ListBotsParams) ([]Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("bot.ListBots")
	rows, err := q.GetConn().WQuery(qctx, "bot.ListBots", listBots,
		arg.ID,
		arg.StrategyID,
		arg.Mode,
		arg.Status,
		arg.Exchange,
		arg.AccountID,
		arg.Name,
		arg.CreatedAtStart,
		arg.CreatedAtEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bot
	for rows.Next() {
		var i *Bot = new(Bot)
		if err := rows.Scan(
			&i.ID,
			&i.StrategyID,
			&i.StrategyVersion,
			&i.AccountID,
			&i.Exchange,
			&i.Mode,
			&i.Name,
			&i.Desc,
			&i.Symbols,
			&i.Config,
			&i.Storage,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const updateBot = `-- name: UpdateBot :one
UPDATE bots
SET name = $2,
    "desc" = $3,
    symbols = $4,
    config = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
AND deleted_at is null
RETURNING id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at
`

type UpdateBotParams struct {
	ID      int32
	Name    string
	Desc    string
	Symbols []string
	Config  []byte
}

// -- timeout: 1s
func (q *Queries) UpdateBot(ctx context.Context, arg UpdateBotParams) (*Bot, error) {
	return _UpdateBot(ctx, q.AsReadOnly(), arg)
}

func _UpdateBot(ctx context.Context, q CacheQuerierConn, arg UpdateBotParams) (*Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "bot.UpdateBot", updateBot,
		arg.ID,
		arg.Name,
		arg.Desc,
		arg.Symbols,
		arg.Config)
	var i *Bot = new(Bot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.StrategyVersion,
		&i.AccountID,
		&i.Exchange,
		&i.Mode,
		&i.Name,
		&i.Desc,
		&i.Symbols,
		&i.Config,
		&i.Storage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Bot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateBotStatus = `-- name: UpdateBotStatus :one
UPDATE bots
SET status = $2,
    error_message = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
AND deleted_at is null
RETURNING id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at
`

type UpdateBotStatusParams struct {
	ID           int32
	Status       BotStatus
	ErrorMessage string
}

// -- timeout: 1s
func (q *Queries) UpdateBotStatus(ctx context.Context, arg UpdateBotStatusParams) (*Bot, error) {
	return _UpdateBotStatus(ctx, q.AsReadOnly(), arg)
}

func _UpdateBotStatus(ctx context.Context, q CacheQuerierConn, arg UpdateBotStatusParams) (*Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "bot.UpdateBotStatus", updateBotStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i *Bot = new(Bot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.StrategyVersion,
		&i.AccountID,
		&i.Exchange,
		&i.Mode,
		&i.Name,
		&i.Desc,
		&i.Symbols,
		&i.Config,
		&i.Storage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Bot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateBotStorage = `-- name: UpdateBotStorage :one
UPDATE bots
SET storage = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
AND deleted_at is null
RETURNING id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at
`

type UpdateBotStorageParams struct {
	ID      int32
	Storage []byte
}

// -- timeout: 1s
func (q *Queries) UpdateBotStorage(ctx context.Context, arg UpdateBotStorageParams) (*Bot, error) {
	return _UpdateBotStorage(ctx, q.AsReadOnly(), arg)
}

func _UpdateBotStorage(ctx context.Context, q CacheQuerierConn, arg UpdateBotStorageParams) (*Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "bot.UpdateBotStorage", updateBotStorage, arg.ID, arg.Storage)
	var i *Bot = new(Bot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.StrategyVersion,
		&i.AccountID,
		&i.Exchange,
		&i.Mode,
		&i.Name,
		&i.Desc,
		&i.Symbols,
		&i.Config,
		&i.Storage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Bot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateBotStrategyVersion = `-- name: UpdateBotStrategyVersion :one
UPDATE bots
SET strategy_version = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
AND status != 'running'
AND deleted_at is null
RETURNING id, strategy_id, strategy_version, account_id, exchange, mode, name, "desc", symbols, config, storage, status, error_message, created_at, updated_at, deleted_at
`

type UpdateBotStrategyVersionParams struct {
	ID              int32
	StrategyVersion string
}

// -- timeout: 1s
func (q *Queries) UpdateBotStrategyVersion(ctx context.Context, arg UpdateBotStrategyVersionParams) (*Bot, error) {
	return _UpdateBotStrategyVersion(ctx, q.AsReadOnly(), arg)
}

func _UpdateBotStrategyVersion(ctx context.Context, q CacheQuerierConn, arg UpdateBotStrategyVersionParams) (*Bot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "bot.UpdateBotStrategyVersion", updateBotStrategyVersion, arg.ID, arg.StrategyVersion)
	var i *Bot = new(Bot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.StrategyVersion,
		&i.AccountID,
		&i.Exchange,
		&i.Mode,
		&i.Name,
		&i.Desc,
		&i.Symbols,
		&i.Config,
		&i.Storage,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Bot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,strategy_id,strategy_version,account_id,exchange,mode,name,desc,symbols,config,storage,status,error_message,created_at,updated_at,deleted_at FROM \"bots\" ORDER BY id,strategy_id,strategy_version,account_id,exchange,name,desc,error_message,created_at,updated_at,deleted_at ASC;"
	rows, err := q.db.WQuery(ctx, "bot.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bot
	for rows.Next() {
		var v Bot
		if err := rows.Scan(&v.ID, &v.StrategyID, &v.StrategyVersion, &v.AccountID, &v.Exchange, &v.Mode, &v.Name, &v.Desc, &v.Symbols, &v.Config, &v.Storage, &v.Status, &v.ErrorMessage, &v.CreatedAt, &v.UpdatedAt, &v.DeletedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"bots\" (id,strategy_id,strategy_version,account_id,exchange,mode,name,desc,symbols,config,storage,status,error_message,created_at,updated_at,deleted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16);"
	rows := make([]Bot, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "bot.Load", sql, row.ID, row.StrategyID, row.StrategyVersion, row.AccountID, row.Exchange, row.Mode, row.Name, row.Desc, row.Symbols, row.Config, row.Storage, row.Status, row.ErrorMessage, row.CreatedAt, row.UpdatedAt, row.DeletedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
