// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package alert

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const countAlerts = `-- name: CountAlerts :one
SELECT count(*)
FROM public.alert
WHERE deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) CountAlerts(ctx context.Context) (*int64, error) {
	return _CountAlerts(ctx, q.AsReadOnly())
}

func (q *ReadOnlyQueries) CountAlerts(ctx context.Context) (*int64, error) {
	return _CountAlerts(ctx, q)
}

func _CountAlerts(ctx context.Context, q CacheQuerierConn) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("alert.CountAlerts")
	row := q.GetConn().WQueryRow(qctx, "alert.CountAlerts", countAlerts)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const countAlertsByExchangeSymbol = `-- name: CountAlertsByExchangeSymbol :one
SELECT count(*)
FROM public.alert
WHERE exchange = $1
  AND symbol = $2
  AND deleted_at IS NULL
`

type CountAlertsByExchangeSymbolParams struct {
	Exchange string
	Symbol   string
}

// -- timeout: 1s
func (q *Queries) CountAlertsByExchangeSymbol(ctx context.Context, arg CountAlertsByExchangeSymbolParams) (*int64, error) {
	return _CountAlertsByExchangeSymbol(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) CountAlertsByExchangeSymbol(ctx context.Context, arg CountAlertsByExchangeSymbolParams) (*int64, error) {
	return _CountAlertsByExchangeSymbol(ctx, q, arg)
}

func _CountAlertsByExchangeSymbol(ctx context.Context, q CacheQuerierConn, arg CountAlertsByExchangeSymbolParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("alert.CountAlertsByExchangeSymbol")
	row := q.GetConn().WQueryRow(qctx, "alert.CountAlertsByExchangeSymbol", countAlertsByExchangeSymbol, arg.Exchange, arg.Symbol)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO public.alert (
    id, exchange, symbol, type, frequency, price, alert_window, percent, remark, cooldown_seconds
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, exchange, symbol, type, frequency, price, alert_window, percent, remark, cooldown_seconds, status, last_triggered_at, trigger_count, created_at, updated_at, deleted_at
`

type CreateAlertParams struct {
	ID              string
	Exchange        string
	Symbol          string
	Type            string
	Frequency       AlertFrequencyT
	Price           pgtype.Numeric
	AlertWindow     NullAlertWindowT
	Percent         pgtype.Numeric
	Remark          *string
	CooldownSeconds int32
}

// -- timeout: 1s
func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (*Alert, error) {
	return _CreateAlert(ctx, q.AsReadOnly(), arg)
}

func _CreateAlert(ctx context.Context, q CacheQuerierConn, arg CreateAlertParams) (*Alert, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "alert.CreateAlert", createAlert,
		arg.ID,
		arg.Exchange,
		arg.Symbol,
		arg.Type,
		arg.Frequency,
		arg.Price,
		arg.AlertWindow,
		arg.Percent,
		arg.Remark,
		arg.CooldownSeconds)
	var i *Alert = new(Alert)
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.Symbol,
		&i.Type,
		&i.Frequency,
		&i.Price,
		&i.AlertWindow,
		&i.Percent,
		&i.Remark,
		&i.CooldownSeconds,
		&i.Status,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Alert)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const deleteAlertByID = `-- name: DeleteAlertByID :execrows
UPDATE public.alert
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) DeleteAlertByID(ctx context.Context, id string) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	result, err := q.db.WExec(qctx, "alert.DeleteAlertByID", deleteAlertByID, id)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, exchange, symbol, type, frequency, price, alert_window, percent, remark, cooldown_seconds, status, last_triggered_at, trigger_count, created_at, updated_at, deleted_at
FROM public.alert
WHERE id = $1
  AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) GetAlertByID(ctx context.Context, id string) (*Alert, error) {
	return _GetAlertByID(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetAlertByID(ctx context.Context, id string) (*Alert, error) {
	return _GetAlertByID(ctx, q, id)
}

func _GetAlertByID(ctx context.Context, q CacheQuerierConn, id string) (*Alert, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("alert.GetAlertByID")
	row := q.GetConn().WQueryRow(qctx, "alert.GetAlertByID", getAlertByID, id)
	var i *Alert = new(Alert)
	err := row.Scan(
		&i.ID,
		&i.Exchange,
		&i.Symbol,
		&i.Type,
		&i.Frequency,
		&i.Price,
		&i.AlertWindow,
		&i.Percent,
		&i.Remark,
		&i.CooldownSeconds,
		&i.Status,
		&i.LastTriggeredAt,
		&i.TriggerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Alert)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const listAlertsByExchangeSymbol = `-- name: ListAlertsByExchangeSymbol :many
SELECT id, exchange, symbol, type, frequency, price, alert_window, percent, remark, cooldown_seconds, status, last_triggered_at, trigger_count, created_at, updated_at, deleted_at
FROM public.alert
WHERE exchange = $1
  AND symbol = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListAlertsByExchangeSymbolParams struct {
	Exchange string
	Symbol   string
}

// -- timeout: 1s
func (q *Queries) ListAlertsByExchangeSymbol(ctx context.Context, arg ListAlertsByExchangeSymbolParams) ([]Alert, error) {
	return _ListAlertsByExchangeSymbol(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListAlertsByExchangeSymbol(ctx context.Context, arg ListAlertsByExchangeSymbolParams) ([]Alert, error) {
	return _ListAlertsByExchangeSymbol(ctx, q, arg)
}

func _ListAlertsByExchangeSymbol(ctx context.Context, q CacheQuerierConn, arg ListAlertsByExchangeSymbolParams) ([]Alert, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("alert.ListAlertsByExchangeSymbol")
	rows, err := q.GetConn().WQuery(qctx, "alert.ListAlertsByExchangeSymbol", listAlertsByExchangeSymbol, arg.Exchange, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i *Alert = new(Alert)
		if err := rows.Scan(
			&i.ID,
			&i.Exchange,
			&i.Symbol,
			&i.Type,
			&i.Frequency,
			&i.Price,
			&i.AlertWindow,
			&i.Percent,
			&i.Remark,
			&i.CooldownSeconds,
			&i.Status,
			&i.LastTriggeredAt,
			&i.TriggerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const listAllActiveAlerts = `-- name: ListAllActiveAlerts :many
SELECT id, exchange, symbol, type, frequency, price, alert_window, percent, remark, cooldown_seconds, status, last_triggered_at, trigger_count, created_at, updated_at, deleted_at
FROM public.alert
WHERE status = 'active'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// -- timeout: 1s
func (q *Queries) ListAllActiveAlerts(ctx context.Context) ([]Alert, error) {
	return _ListAllActiveAlerts(ctx, q.AsReadOnly())
}

func (q *ReadOnlyQueries) ListAllActiveAlerts(ctx context.Context) ([]Alert, error) {
	return _ListAllActiveAlerts(ctx, q)
}

func _ListAllActiveAlerts(ctx context.Context, q CacheQuerierConn) ([]Alert, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("alert.ListAllActiveAlerts")
	rows, err := q.GetConn().WQuery(qctx, "alert.ListAllActiveAlerts", listAllActiveAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i *Alert = new(Alert)
		if err := rows.Scan(
			&i.ID,
			&i.Exchange,
			&i.Symbol,
			&i.Type,
			&i.Frequency,
			&i.Price,
			&i.AlertWindow,
			&i.Percent,
			&i.Remark,
			&i.CooldownSeconds,
			&i.Status,
			&i.LastTriggeredAt,
			&i.TriggerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const touchAlertTriggered = `-- name: TouchAlertTriggered :exec
UPDATE public.alert
SET last_triggered_at = $2,
    trigger_count     = trigger_count + 1,
    updated_at        = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type TouchAlertTriggeredParams struct {
	ID              string
	LastTriggeredAt *time.Time
}

// -- timeout: 1s
func (q *Queries) TouchAlertTriggered(ctx context.Context, arg TouchAlertTriggeredParams) error {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	_, err := q.db.WExec(qctx, "alert.TouchAlertTriggered", touchAlertTriggered, arg.ID, arg.LastTriggeredAt)
	if err != nil {
		return err
	}

	return nil
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,exchange,symbol,type,frequency,price,alert_window,percent,remark,cooldown_seconds,status,last_triggered_at,trigger_count,created_at,updated_at,deleted_at FROM \"alert\" ORDER BY id,exchange,symbol,type,remark,cooldown_seconds,last_triggered_at,trigger_count,created_at,updated_at,deleted_at ASC;"
	rows, err := q.db.WQuery(ctx, "alert.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var v Alert
		if err := rows.Scan(&v.ID, &v.Exchange, &v.Symbol, &v.Type, &v.Frequency, &v.Price, &v.AlertWindow, &v.Percent, &v.Remark, &v.CooldownSeconds, &v.Status, &v.LastTriggeredAt, &v.TriggerCount, &v.CreatedAt, &v.UpdatedAt, &v.DeletedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"alert\" (id,exchange,symbol,type,frequency,price,alert_window,percent,remark,cooldown_seconds,status,last_triggered_at,trigger_count,created_at,updated_at,deleted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16);"
	rows := make([]Alert, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "alert.Load", sql, row.ID, row.Exchange, row.Symbol, row.Type, row.Frequency, row.Price, row.AlertWindow, row.Percent, row.Remark, row.CooldownSeconds, row.Status, row.LastTriggeredAt, row.TriggerCount, row.CreatedAt, row.UpdatedAt, row.DeletedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
