// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package alert_trigger_event

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const cleanupAlertTriggerEventsBefore = `-- name: CleanupAlertTriggerEventsBefore :execrows
DELETE
FROM public.alert_trigger_event
WHERE triggered_at < $1
`

// -- timeout: 1s
func (q *Queries) CleanupAlertTriggerEventsBefore(ctx context.Context, triggeredAt time.Time) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	result, err := q.db.WExec(qctx, "alert_trigger_event.CleanupAlertTriggerEventsBefore", cleanupAlertTriggerEventsBefore, triggeredAt)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const createAlertTriggerEvent = `-- name: CreateAlertTriggerEvent :one
INSERT INTO public.alert_trigger_event (
    id, alert_id, exchange, symbol, type, frequency, target_price, alert_window, percent, baseline_price, trigger_price, triggered_at, notify_result, error_message, meta
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, alert_id, exchange, symbol, type, frequency, target_price, alert_window, percent, baseline_price, trigger_price, triggered_at, notify_result, error_message, meta
`

type CreateAlertTriggerEventParams struct {
	ID            string
	AlertID       string
	Exchange      string
	Symbol        string
	Type          string
	Frequency     string
	TargetPrice   pgtype.Numeric
	AlertWindow   *string
	Percent       pgtype.Numeric
	BaselinePrice pgtype.Numeric
	TriggerPrice  pgtype.Numeric
	TriggeredAt   time.Time
	NotifyResult  string
	ErrorMessage  *string
	Meta          []byte
}

type CreateAlertTriggerEventRow struct {
	ID            string
	AlertID       string
	Exchange      string
	Symbol        string
	Type          string
	Frequency     string
	TargetPrice   pgtype.Numeric
	AlertWindow   *string
	Percent       pgtype.Numeric
	BaselinePrice pgtype.Numeric
	TriggerPrice  pgtype.Numeric
	TriggeredAt   time.Time
	NotifyResult  string
	ErrorMessage  *string
	Meta          []byte
}

// -- timeout: 1s
func (q *Queries) CreateAlertTriggerEvent(ctx context.Context, arg CreateAlertTriggerEventParams) (*CreateAlertTriggerEventRow, error) {
	return _CreateAlertTriggerEvent(ctx, q.AsReadOnly(), arg)
}

func _CreateAlertTriggerEvent(ctx context.Context, q CacheQuerierConn, arg CreateAlertTriggerEventParams) (*CreateAlertTriggerEventRow, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "alert_trigger_event.CreateAlertTriggerEvent", createAlertTriggerEvent,
		arg.ID,
		arg.AlertID,
		arg.Exchange,
		arg.Symbol,
		arg.Type,
		arg.Frequency,
		arg.TargetPrice,
		arg.AlertWindow,
		arg.Percent,
		arg.BaselinePrice,
		arg.TriggerPrice,
		arg.TriggeredAt,
		arg.NotifyResult,
		arg.ErrorMessage,
		arg.Meta)
	var i *CreateAlertTriggerEventRow = new(CreateAlertTriggerEventRow)
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Exchange,
		&i.Symbol,
		&i.Type,
		&i.Frequency,
		&i.TargetPrice,
		&i.AlertWindow,
		&i.Percent,
		&i.BaselinePrice,
		&i.TriggerPrice,
		&i.TriggeredAt,
		&i.NotifyResult,
		&i.ErrorMessage,
		&i.Meta,
	)
	if err == pgx.ErrNoRows {
		return (*CreateAlertTriggerEventRow)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,exchange,symbol,type,frequency,price,alert_window,percent,remark,cooldown_seconds,status,last_triggered_at,trigger_count,created_at,updated_at,deleted_at FROM \"alert\" ORDER BY id,exchange,symbol,type,remark,cooldown_seconds,last_triggered_at,trigger_count,created_at,updated_at,deleted_at ASC;"
	rows, err := q.db.WQuery(ctx, "alert_trigger_event.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var v Alert
		if err := rows.Scan(&v.ID, &v.Exchange, &v.Symbol, &v.Type, &v.Frequency, &v.Price, &v.AlertWindow, &v.Percent, &v.Remark, &v.CooldownSeconds, &v.Status, &v.LastTriggeredAt, &v.TriggerCount, &v.CreatedAt, &v.UpdatedAt, &v.DeletedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"alert\" (id,exchange,symbol,type,frequency,price,alert_window,percent,remark,cooldown_seconds,status,last_triggered_at,trigger_count,created_at,updated_at,deleted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16);"
	rows := make([]Alert, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "alert_trigger_event.Load", sql, row.ID, row.Exchange, row.Symbol, row.Type, row.Frequency, row.Price, row.AlertWindow, row.Percent, row.Remark, row.CooldownSeconds, row.Status, row.LastTriggeredAt, row.TriggerCount, row.CreatedAt, row.UpdatedAt, row.DeletedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
