// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package orders

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlgoType string

const (
	AlgoTypeNONE        AlgoType = "NONE"
	AlgoTypeCONDITIONAL AlgoType = "CONDITIONAL"
	AlgoTypeTRAILING    AlgoType = "TRAILING"
	AlgoTypeOCO         AlgoType = "OCO"
	AlgoTypeTWAP        AlgoType = "TWAP"
	AlgoTypeICEBERG     AlgoType = "ICEBERG"
	AlgoTypeCHASE       AlgoType = "CHASE"
	AlgoTypeUNKNOWN     AlgoType = "UNKNOWN"
)

func (e *AlgoType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlgoType(s)
	case string:
		*e = AlgoType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlgoType: %T", src)
	}
	return nil
}

type NullAlgoType struct {
	AlgoType AlgoType
	Valid    bool // Valid is true if AlgoType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlgoType) Scan(value interface{}) error {
	if value == nil {
		ns.AlgoType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlgoType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlgoType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlgoType), nil
}

func (e AlgoType) Valid() bool {
	switch e {
	case AlgoTypeNONE,
		AlgoTypeCONDITIONAL,
		AlgoTypeTRAILING,
		AlgoTypeOCO,
		AlgoTypeTWAP,
		AlgoTypeICEBERG,
		AlgoTypeCHASE,
		AlgoTypeUNKNOWN:
		return true
	}
	return false
}

func AllAlgoTypeValues() []AlgoType {
	return []AlgoType{
		AlgoTypeNONE,
		AlgoTypeCONDITIONAL,
		AlgoTypeTRAILING,
		AlgoTypeOCO,
		AlgoTypeTWAP,
		AlgoTypeICEBERG,
		AlgoTypeCHASE,
		AlgoTypeUNKNOWN,
	}
}

type OrderSide string

const (
	OrderSideLONG  OrderSide = "LONG"
	OrderSideSHORT OrderSide = "SHORT"
)

func (e *OrderSide) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderSide(s)
	case string:
		*e = OrderSide(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderSide: %T", src)
	}
	return nil
}

type NullOrderSide struct {
	OrderSide OrderSide
	Valid     bool // Valid is true if OrderSide is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderSide) Scan(value interface{}) error {
	if value == nil {
		ns.OrderSide, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderSide.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderSide) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderSide), nil
}

func (e OrderSide) Valid() bool {
	switch e {
	case OrderSideLONG,
		OrderSideSHORT:
		return true
	}
	return false
}

func AllOrderSideValues() []OrderSide {
	return []OrderSide{
		OrderSideLONG,
		OrderSideSHORT,
	}
}

type OrderSource string

const (
	OrderSourceUSER        OrderSource = "USER"
	OrderSourceSTRATEGY    OrderSource = "STRATEGY"
	OrderSourceLIQUIDATION OrderSource = "LIQUIDATION"
	OrderSourceADL         OrderSource = "ADL"
)

func (e *OrderSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderSource(s)
	case string:
		*e = OrderSource(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderSource: %T", src)
	}
	return nil
}

type NullOrderSource struct {
	OrderSource OrderSource
	Valid       bool // Valid is true if OrderSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderSource) Scan(value interface{}) error {
	if value == nil {
		ns.OrderSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderSource), nil
}

func (e OrderSource) Valid() bool {
	switch e {
	case OrderSourceUSER,
		OrderSourceSTRATEGY,
		OrderSourceLIQUIDATION,
		OrderSourceADL:
		return true
	}
	return false
}

func AllOrderSourceValues() []OrderSource {
	return []OrderSource{
		OrderSourceUSER,
		OrderSourceSTRATEGY,
		OrderSourceLIQUIDATION,
		OrderSourceADL,
	}
}

type OrderType string

const (
	OrderTypeMARKET  OrderType = "MARKET"
	OrderTypeLIMIT   OrderType = "LIMIT"
	OrderTypeUNKNOWN OrderType = "UNKNOWN"
)

func (e *OrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderType(s)
	case string:
		*e = OrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderType: %T", src)
	}
	return nil
}

type NullOrderType struct {
	OrderType OrderType
	Valid     bool // Valid is true if OrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.OrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderType), nil
}

func (e OrderType) Valid() bool {
	switch e {
	case OrderTypeMARKET,
		OrderTypeLIMIT,
		OrderTypeUNKNOWN:
		return true
	}
	return false
}

func AllOrderTypeValues() []OrderType {
	return []OrderType{
		OrderTypeMARKET,
		OrderTypeLIMIT,
		OrderTypeUNKNOWN,
	}
}

type TimeInForce string

const (
	TimeInForceGTC TimeInForce = "GTC"
	TimeInForceIOC TimeInForce = "IOC"
	TimeInForceFOK TimeInForce = "FOK"
)

func (e *TimeInForce) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimeInForce(s)
	case string:
		*e = TimeInForce(s)
	default:
		return fmt.Errorf("unsupported scan type for TimeInForce: %T", src)
	}
	return nil
}

type NullTimeInForce struct {
	TimeInForce TimeInForce
	Valid       bool // Valid is true if TimeInForce is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimeInForce) Scan(value interface{}) error {
	if value == nil {
		ns.TimeInForce, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimeInForce.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimeInForce) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimeInForce), nil
}

func (e TimeInForce) Valid() bool {
	switch e {
	case TimeInForceGTC,
		TimeInForceIOC,
		TimeInForceFOK:
		return true
	}
	return false
}

func AllTimeInForceValues() []TimeInForce {
	return []TimeInForce{
		TimeInForceGTC,
		TimeInForceIOC,
		TimeInForceFOK,
	}
}

type Order struct {
	ID            int64          `json:"id"`
	BotID         int32          `json:"bot_id"`
	AccountID     string         `json:"account_id"`
	OrderID       string         `json:"order_id"`
	ClientOrderID string         `json:"client_order_id"`
	DrivedOrderID string         `json:"drived_order_id"`
	OrderType     OrderType      `json:"order_type"`
	AlgoType      AlgoType       `json:"algo_type"`
	Source        OrderSource    `json:"source"`
	Exchange      string         `json:"exchange"`
	Symbol        string         `json:"symbol"`
	Side          OrderSide      `json:"side"`
	IsBuy         bool           `json:"is_buy"`
	Price         pgtype.Numeric `json:"price"`
	Quantity      pgtype.Numeric `json:"quantity"`
	ExecutedQty   pgtype.Numeric `json:"executed_qty"`
	ExecutedPrice pgtype.Numeric `json:"executed_price"`
	AvgPrice      pgtype.Numeric `json:"avg_price"`
	ReduceOnly    bool           `json:"reduce_only"`
	PostOnly      bool           `json:"post_only"`
	Tif           TimeInForce    `json:"tif"`
	Conditions    []byte         `json:"conditions"`
	Detail        []byte         `json:"detail"`
	Status        string         `json:"status"`
	RejectReason  *string        `json:"reject_reason"`
	CreatedTs     time.Time      `json:"created_ts"`
	WorkingTs     *time.Time     `json:"working_ts"`
	FinishedTs    *time.Time     `json:"finished_ts"`
	UpdatedTs     time.Time      `json:"updated_ts"`
	Locked        pgtype.Numeric `json:"locked"`
	LockedAsset   *string        `json:"locked_asset"`
	Fee           pgtype.Numeric `json:"fee"`
	FeeAsset      *string        `json:"fee_asset"`
	RealizedPnl   pgtype.Numeric `json:"realized_pnl"`
	PnlAsset      *string        `json:"pnl_asset"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
