// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package orders

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const cancelOrderStatusWithReason = `-- name: CancelOrderStatusWithReason :one
UPDATE orders
SET status = 'CANCELED',
    reject_reason = $3,
    locked = 0,
    finished_ts = $4,
    updated_ts = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE account_id = $1
  AND order_id = $2
RETURNING id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at
`

type CancelOrderStatusWithReasonParams struct {
	AccountID    string
	OrderID      string
	RejectReason *string
	FinishedTs   *time.Time
	UpdatedTs    time.Time
}

// -- timeout: 1s
func (q *Queries) CancelOrderStatusWithReason(ctx context.Context, arg CancelOrderStatusWithReasonParams) (*Order, error) {
	return _CancelOrderStatusWithReason(ctx, q.AsReadOnly(), arg)
}

func _CancelOrderStatusWithReason(ctx context.Context, q CacheQuerierConn, arg CancelOrderStatusWithReasonParams) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "orders.CancelOrderStatusWithReason", cancelOrderStatusWithReason,
		arg.AccountID,
		arg.OrderID,
		arg.RejectReason,
		arg.FinishedTs,
		arg.UpdatedTs)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const countOrdersByFilter = `-- name: CountOrdersByFilter :one
SELECT COUNT(1) FROM orders
WHERE account_id = $1
  AND ($2::int IS NULL OR bot_id = $2::int)
  AND ($3::timestamptz IS NULL OR created_ts >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_ts <= $4::timestamptz)
  AND symbol = coalesce($5::varchar, symbol)
  AND source = coalesce($6::order_source, source)
  AND order_type = coalesce($7::order_type, order_type)
  AND ($8::varchar[] IS NULL OR status = ANY($8::varchar[]))
`

type CountOrdersByFilterParams struct {
	AccountID   string
	BotID       *int32
	StartTs     *time.Time
	EndTs       *time.Time
	Symbol      *string
	OrderSource NullOrderSource
	OrderType   NullOrderType
	Statuses    []string
}

// -- timeout: 1s
func (q *Queries) CountOrdersByFilter(ctx context.Context, arg CountOrdersByFilterParams) (*int64, error) {
	return _CountOrdersByFilter(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) CountOrdersByFilter(ctx context.Context, arg CountOrdersByFilterParams) (*int64, error) {
	return _CountOrdersByFilter(ctx, q, arg)
}

func _CountOrdersByFilter(ctx context.Context, q CacheQuerierConn, arg CountOrdersByFilterParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.CountOrdersByFilter")
	row := q.GetConn().WQueryRow(qctx, "orders.CountOrdersByFilter", countOrdersByFilter,
		arg.AccountID,
		arg.BotID,
		arg.StartTs,
		arg.EndTs,
		arg.Symbol,
		arg.OrderSource,
		arg.OrderType,
		arg.Statuses)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const countOrdersByFinishedTsRange = `-- name: CountOrdersByFinishedTsRange :one
SELECT COUNT(1) FROM orders
WHERE account_id = $1
  AND ($2::int IS NULL OR bot_id = $2::int)
  AND finished_ts IS NOT NULL
  AND finished_ts >= $3::timestamptz
  AND finished_ts <= $4::timestamptz
  AND symbol = coalesce($5::varchar, symbol)
  AND source = coalesce($6::order_source, source)
  AND order_type = coalesce($7::order_type, order_type)
  AND ($8::varchar[] IS NULL OR status = ANY($8::varchar[]))
`

type CountOrdersByFinishedTsRangeParams struct {
	AccountID       string
	BotID           *int32
	FinishedStartTs *time.Time
	FinishedEndTs   *time.Time
	Symbol          *string
	OrderSource     NullOrderSource
	OrderType       NullOrderType
	Statuses        []string
}

// -- timeout: 1s
func (q *Queries) CountOrdersByFinishedTsRange(ctx context.Context, arg CountOrdersByFinishedTsRangeParams) (*int64, error) {
	return _CountOrdersByFinishedTsRange(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) CountOrdersByFinishedTsRange(ctx context.Context, arg CountOrdersByFinishedTsRangeParams) (*int64, error) {
	return _CountOrdersByFinishedTsRange(ctx, q, arg)
}

func _CountOrdersByFinishedTsRange(ctx context.Context, q CacheQuerierConn, arg CountOrdersByFinishedTsRangeParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.CountOrdersByFinishedTsRange")
	row := q.GetConn().WQueryRow(qctx, "orders.CountOrdersByFinishedTsRange", countOrdersByFinishedTsRange,
		arg.AccountID,
		arg.BotID,
		arg.FinishedStartTs,
		arg.FinishedEndTs,
		arg.Symbol,
		arg.OrderSource,
		arg.OrderType,
		arg.Statuses)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE id = $1
`

// -- timeout: 1s
func (q *Queries) GetOrder(ctx context.Context, id int64) (*Order, error) {
	return _GetOrder(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetOrder(ctx context.Context, id int64) (*Order, error) {
	return _GetOrder(ctx, q, id)
}

func _GetOrder(ctx context.Context, q CacheQuerierConn, id int64) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.GetOrder")
	row := q.GetConn().WQueryRow(qctx, "orders.GetOrder", getOrder, id)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getOrderByClientOrderId = `-- name: GetOrderByClientOrderId :one
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND client_order_id = $2
`

type GetOrderByClientOrderIdParams struct {
	AccountID     string
	ClientOrderID string
}

// -- timeout: 1s
func (q *Queries) GetOrderByClientOrderId(ctx context.Context, arg GetOrderByClientOrderIdParams) (*Order, error) {
	return _GetOrderByClientOrderId(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetOrderByClientOrderId(ctx context.Context, arg GetOrderByClientOrderIdParams) (*Order, error) {
	return _GetOrderByClientOrderId(ctx, q, arg)
}

func _GetOrderByClientOrderId(ctx context.Context, q CacheQuerierConn, arg GetOrderByClientOrderIdParams) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.GetOrderByClientOrderId")
	row := q.GetConn().WQueryRow(qctx, "orders.GetOrderByClientOrderId", getOrderByClientOrderId, arg.AccountID, arg.ClientOrderID)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getOrderByClientOrderIdWithLock = `-- name: GetOrderByClientOrderIdWithLock :one
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND client_order_id = $2
FOR UPDATE
`

type GetOrderByClientOrderIdWithLockParams struct {
	AccountID     string
	ClientOrderID string
}

// -- timeout: 1s
func (q *Queries) GetOrderByClientOrderIdWithLock(ctx context.Context, arg GetOrderByClientOrderIdWithLockParams) (*Order, error) {
	return _GetOrderByClientOrderIdWithLock(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetOrderByClientOrderIdWithLock(ctx context.Context, arg GetOrderByClientOrderIdWithLockParams) (*Order, error) {
	return _GetOrderByClientOrderIdWithLock(ctx, q, arg)
}

func _GetOrderByClientOrderIdWithLock(ctx context.Context, q CacheQuerierConn, arg GetOrderByClientOrderIdWithLockParams) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.GetOrderByClientOrderIdWithLock")
	row := q.GetConn().WQueryRow(qctx, "orders.GetOrderByClientOrderIdWithLock", getOrderByClientOrderIdWithLock, arg.AccountID, arg.ClientOrderID)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getOrderByOrderId = `-- name: GetOrderByOrderId :one
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND order_id = $2
`

type GetOrderByOrderIdParams struct {
	AccountID string
	OrderID   string
}

// -- timeout: 1s
func (q *Queries) GetOrderByOrderId(ctx context.Context, arg GetOrderByOrderIdParams) (*Order, error) {
	return _GetOrderByOrderId(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetOrderByOrderId(ctx context.Context, arg GetOrderByOrderIdParams) (*Order, error) {
	return _GetOrderByOrderId(ctx, q, arg)
}

func _GetOrderByOrderId(ctx context.Context, q CacheQuerierConn, arg GetOrderByOrderIdParams) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.GetOrderByOrderId")
	row := q.GetConn().WQueryRow(qctx, "orders.GetOrderByOrderId", getOrderByOrderId, arg.AccountID, arg.OrderID)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getOrderByOrderIdWithLock = `-- name: GetOrderByOrderIdWithLock :one
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND order_id = $2
FOR UPDATE
`

type GetOrderByOrderIdWithLockParams struct {
	AccountID string
	OrderID   string
}

// -- timeout: 1s
func (q *Queries) GetOrderByOrderIdWithLock(ctx context.Context, arg GetOrderByOrderIdWithLockParams) (*Order, error) {
	return _GetOrderByOrderIdWithLock(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetOrderByOrderIdWithLock(ctx context.Context, arg GetOrderByOrderIdWithLockParams) (*Order, error) {
	return _GetOrderByOrderIdWithLock(ctx, q, arg)
}

func _GetOrderByOrderIdWithLock(ctx context.Context, q CacheQuerierConn, arg GetOrderByOrderIdWithLockParams) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.GetOrderByOrderIdWithLock")
	row := q.GetConn().WQueryRow(qctx, "orders.GetOrderByOrderIdWithLock", getOrderByOrderIdWithLock, arg.AccountID, arg.OrderID)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getPendingOrders = `-- name: GetPendingOrders :many
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
AND status IN ('NEW', 'PENDING', 'WORKING', 'PARTIAL_DONE')
AND symbol = coalesce($2::varchar, symbol)
ORDER BY created_at DESC
`

type GetPendingOrdersParams struct {
	AccountID string
	Symbol    *string
}

// -- timeout: 1s
func (q *Queries) GetPendingOrders(ctx context.Context, arg GetPendingOrdersParams) ([]Order, error) {
	return _GetPendingOrders(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetPendingOrders(ctx context.Context, arg GetPendingOrdersParams) ([]Order, error) {
	return _GetPendingOrders(ctx, q, arg)
}

func _GetPendingOrders(ctx context.Context, q CacheQuerierConn, arg GetPendingOrdersParams) ([]Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.GetPendingOrders")
	rows, err := q.GetConn().WQuery(qctx, "orders.GetPendingOrders", getPendingOrders, arg.AccountID, arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i *Order = new(Order)
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.AccountID,
			&i.OrderID,
			&i.ClientOrderID,
			&i.DrivedOrderID,
			&i.OrderType,
			&i.AlgoType,
			&i.Source,
			&i.Exchange,
			&i.Symbol,
			&i.Side,
			&i.IsBuy,
			&i.Price,
			&i.Quantity,
			&i.ExecutedQty,
			&i.ExecutedPrice,
			&i.AvgPrice,
			&i.ReduceOnly,
			&i.PostOnly,
			&i.Tif,
			&i.Conditions,
			&i.Detail,
			&i.Status,
			&i.RejectReason,
			&i.CreatedTs,
			&i.WorkingTs,
			&i.FinishedTs,
			&i.UpdatedTs,
			&i.Locked,
			&i.LockedAsset,
			&i.Fee,
			&i.FeeAsset,
			&i.RealizedPnl,
			&i.PnlAsset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND ($4::int IS NULL OR bot_id = $4::int)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersParams struct {
	AccountID string
	Limit     int32
	Offset    int32
	BotID     *int32
}

// -- timeout: 1s
func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	return _ListOrders(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	return _ListOrders(ctx, q, arg)
}

func _ListOrders(ctx context.Context, q CacheQuerierConn, arg ListOrdersParams) ([]Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.ListOrders")
	rows, err := q.GetConn().WQuery(qctx, "orders.ListOrders", listOrders,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
		arg.BotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i *Order = new(Order)
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.AccountID,
			&i.OrderID,
			&i.ClientOrderID,
			&i.DrivedOrderID,
			&i.OrderType,
			&i.AlgoType,
			&i.Source,
			&i.Exchange,
			&i.Symbol,
			&i.Side,
			&i.IsBuy,
			&i.Price,
			&i.Quantity,
			&i.ExecutedQty,
			&i.ExecutedPrice,
			&i.AvgPrice,
			&i.ReduceOnly,
			&i.PostOnly,
			&i.Tif,
			&i.Conditions,
			&i.Detail,
			&i.Status,
			&i.RejectReason,
			&i.CreatedTs,
			&i.WorkingTs,
			&i.FinishedTs,
			&i.UpdatedTs,
			&i.Locked,
			&i.LockedAsset,
			&i.Fee,
			&i.FeeAsset,
			&i.RealizedPnl,
			&i.PnlAsset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const listOrdersByAccountAndTimeRange = `-- name: ListOrdersByAccountAndTimeRange :many
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND ($5::int IS NULL OR bot_id = $5::int)
  AND ($6::varchar IS NULL OR symbol = $6::varchar)
  AND created_ts >= $2
  AND created_ts <= $3
ORDER BY created_ts ASC, id ASC
LIMIT $4
`

type ListOrdersByAccountAndTimeRangeParams struct {
	AccountID   string
	CreatedTs   time.Time
	CreatedTs_2 time.Time
	Limit       int32
	BotID       *int32
	Symbol      *string
}

// -- timeout: 5s
func (q *Queries) ListOrdersByAccountAndTimeRange(ctx context.Context, arg ListOrdersByAccountAndTimeRangeParams) ([]Order, error) {
	return _ListOrdersByAccountAndTimeRange(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListOrdersByAccountAndTimeRange(ctx context.Context, arg ListOrdersByAccountAndTimeRangeParams) ([]Order, error) {
	return _ListOrdersByAccountAndTimeRange(ctx, q, arg)
}

func _ListOrdersByAccountAndTimeRange(ctx context.Context, q CacheQuerierConn, arg ListOrdersByAccountAndTimeRangeParams) ([]Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("orders.ListOrdersByAccountAndTimeRange")
	rows, err := q.GetConn().WQuery(qctx, "orders.ListOrdersByAccountAndTimeRange", listOrdersByAccountAndTimeRange,
		arg.AccountID,
		arg.CreatedTs,
		arg.CreatedTs_2,
		arg.Limit,
		arg.BotID,
		arg.Symbol)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i *Order = new(Order)
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.AccountID,
			&i.OrderID,
			&i.ClientOrderID,
			&i.DrivedOrderID,
			&i.OrderType,
			&i.AlgoType,
			&i.Source,
			&i.Exchange,
			&i.Symbol,
			&i.Side,
			&i.IsBuy,
			&i.Price,
			&i.Quantity,
			&i.ExecutedQty,
			&i.ExecutedPrice,
			&i.AvgPrice,
			&i.ReduceOnly,
			&i.PostOnly,
			&i.Tif,
			&i.Conditions,
			&i.Detail,
			&i.Status,
			&i.RejectReason,
			&i.CreatedTs,
			&i.WorkingTs,
			&i.FinishedTs,
			&i.UpdatedTs,
			&i.Locked,
			&i.LockedAsset,
			&i.Fee,
			&i.FeeAsset,
			&i.RealizedPnl,
			&i.PnlAsset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const listOrdersByCursor = `-- name: ListOrdersByCursor :many
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND ($3::int IS NULL OR bot_id = $3::int)
  AND symbol = coalesce($4::varchar, symbol)
  AND source = coalesce($5::order_source, source)
  AND order_type = coalesce($6::order_type, order_type)
  AND ($7::varchar[] IS NULL OR status = ANY($7::varchar[]))
  AND (
    $8::timestamptz IS NULL
    OR created_ts < $8::timestamptz
    OR (
      created_ts = $8::timestamptz
      AND id < $9::bigint
    )
  )
ORDER BY created_ts DESC, id DESC
LIMIT $2
`

type ListOrdersByCursorParams struct {
	AccountID       string
	Limit           int32
	BotID           *int32
	Symbol          *string
	OrderSource     NullOrderSource
	OrderType       NullOrderType
	Statuses        []string
	CursorCreatedTs *time.Time
	CursorID        *int64
}

// -- timeout: 1s
func (q *Queries) ListOrdersByCursor(ctx context.Context, arg ListOrdersByCursorParams) ([]Order, error) {
	return _ListOrdersByCursor(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListOrdersByCursor(ctx context.Context, arg ListOrdersByCursorParams) ([]Order, error) {
	return _ListOrdersByCursor(ctx, q, arg)
}

func _ListOrdersByCursor(ctx context.Context, q CacheQuerierConn, arg ListOrdersByCursorParams) ([]Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.ListOrdersByCursor")
	rows, err := q.GetConn().WQuery(qctx, "orders.ListOrdersByCursor", listOrdersByCursor,
		arg.AccountID,
		arg.Limit,
		arg.BotID,
		arg.Symbol,
		arg.OrderSource,
		arg.OrderType,
		arg.Statuses,
		arg.CursorCreatedTs,
		arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i *Order = new(Order)
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.AccountID,
			&i.OrderID,
			&i.ClientOrderID,
			&i.DrivedOrderID,
			&i.OrderType,
			&i.AlgoType,
			&i.Source,
			&i.Exchange,
			&i.Symbol,
			&i.Side,
			&i.IsBuy,
			&i.Price,
			&i.Quantity,
			&i.ExecutedQty,
			&i.ExecutedPrice,
			&i.AvgPrice,
			&i.ReduceOnly,
			&i.PostOnly,
			&i.Tif,
			&i.Conditions,
			&i.Detail,
			&i.Status,
			&i.RejectReason,
			&i.CreatedTs,
			&i.WorkingTs,
			&i.FinishedTs,
			&i.UpdatedTs,
			&i.Locked,
			&i.LockedAsset,
			&i.Fee,
			&i.FeeAsset,
			&i.RealizedPnl,
			&i.PnlAsset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const listOrdersByPage = `-- name: ListOrdersByPage :many
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND ($4::int IS NULL OR bot_id = $4::int)
  AND ($5::timestamptz IS NULL OR created_ts >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR created_ts <= $6::timestamptz)
  AND symbol = coalesce($7::varchar, symbol)
  AND source = coalesce($8::order_source, source)
  AND order_type = coalesce($9::order_type, order_type)
  AND ($10::varchar[] IS NULL OR status = ANY($10::varchar[]))
ORDER BY created_ts DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByPageParams struct {
	AccountID   string
	Limit       int32
	Offset      int32
	BotID       *int32
	StartTs     *time.Time
	EndTs       *time.Time
	Symbol      *string
	OrderSource NullOrderSource
	OrderType   NullOrderType
	Statuses    []string
}

// -- timeout: 1s
func (q *Queries) ListOrdersByPage(ctx context.Context, arg ListOrdersByPageParams) ([]Order, error) {
	return _ListOrdersByPage(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListOrdersByPage(ctx context.Context, arg ListOrdersByPageParams) ([]Order, error) {
	return _ListOrdersByPage(ctx, q, arg)
}

func _ListOrdersByPage(ctx context.Context, q CacheQuerierConn, arg ListOrdersByPageParams) ([]Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.ListOrdersByPage")
	rows, err := q.GetConn().WQuery(qctx, "orders.ListOrdersByPage", listOrdersByPage,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
		arg.BotID,
		arg.StartTs,
		arg.EndTs,
		arg.Symbol,
		arg.OrderSource,
		arg.OrderType,
		arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i *Order = new(Order)
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.AccountID,
			&i.OrderID,
			&i.ClientOrderID,
			&i.DrivedOrderID,
			&i.OrderType,
			&i.AlgoType,
			&i.Source,
			&i.Exchange,
			&i.Symbol,
			&i.Side,
			&i.IsBuy,
			&i.Price,
			&i.Quantity,
			&i.ExecutedQty,
			&i.ExecutedPrice,
			&i.AvgPrice,
			&i.ReduceOnly,
			&i.PostOnly,
			&i.Tif,
			&i.Conditions,
			&i.Detail,
			&i.Status,
			&i.RejectReason,
			&i.CreatedTs,
			&i.WorkingTs,
			&i.FinishedTs,
			&i.UpdatedTs,
			&i.Locked,
			&i.LockedAsset,
			&i.Fee,
			&i.FeeAsset,
			&i.RealizedPnl,
			&i.PnlAsset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const listOrdersByPageByFinishedTs = `-- name: ListOrdersByPageByFinishedTs :many
SELECT id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at FROM orders
WHERE account_id = $1
  AND ($4::int IS NULL OR bot_id = $4::int)
  AND finished_ts IS NOT NULL
  AND finished_ts >= $5::timestamptz
  AND finished_ts <= $6::timestamptz
  AND symbol = coalesce($7::varchar, symbol)
  AND source = coalesce($8::order_source, source)
  AND order_type = coalesce($9::order_type, order_type)
  AND ($10::varchar[] IS NULL OR status = ANY($10::varchar[]))
ORDER BY finished_ts DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByPageByFinishedTsParams struct {
	AccountID       string
	Limit           int32
	Offset          int32
	BotID           *int32
	FinishedStartTs *time.Time
	FinishedEndTs   *time.Time
	Symbol          *string
	OrderSource     NullOrderSource
	OrderType       NullOrderType
	Statuses        []string
}

// -- timeout: 1s
func (q *Queries) ListOrdersByPageByFinishedTs(ctx context.Context, arg ListOrdersByPageByFinishedTsParams) ([]Order, error) {
	return _ListOrdersByPageByFinishedTs(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListOrdersByPageByFinishedTs(ctx context.Context, arg ListOrdersByPageByFinishedTsParams) ([]Order, error) {
	return _ListOrdersByPageByFinishedTs(ctx, q, arg)
}

func _ListOrdersByPageByFinishedTs(ctx context.Context, q CacheQuerierConn, arg ListOrdersByPageByFinishedTsParams) ([]Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("orders.ListOrdersByPageByFinishedTs")
	rows, err := q.GetConn().WQuery(qctx, "orders.ListOrdersByPageByFinishedTs", listOrdersByPageByFinishedTs,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
		arg.BotID,
		arg.FinishedStartTs,
		arg.FinishedEndTs,
		arg.Symbol,
		arg.OrderSource,
		arg.OrderType,
		arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i *Order = new(Order)
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.AccountID,
			&i.OrderID,
			&i.ClientOrderID,
			&i.DrivedOrderID,
			&i.OrderType,
			&i.AlgoType,
			&i.Source,
			&i.Exchange,
			&i.Symbol,
			&i.Side,
			&i.IsBuy,
			&i.Price,
			&i.Quantity,
			&i.ExecutedQty,
			&i.ExecutedPrice,
			&i.AvgPrice,
			&i.ReduceOnly,
			&i.PostOnly,
			&i.Tif,
			&i.Conditions,
			&i.Detail,
			&i.Status,
			&i.RejectReason,
			&i.CreatedTs,
			&i.WorkingTs,
			&i.FinishedTs,
			&i.UpdatedTs,
			&i.Locked,
			&i.LockedAsset,
			&i.Fee,
			&i.FeeAsset,
			&i.RealizedPnl,
			&i.PnlAsset,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const setOrderLockedAsset = `-- name: SetOrderLockedAsset :one
UPDATE orders
SET locked = $3,
    locked_asset = $4
WHERE account_id = $1
  AND order_id = $2
RETURNING id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at
`

type SetOrderLockedAssetParams struct {
	AccountID   string
	OrderID     string
	Locked      pgtype.Numeric
	LockedAsset *string
}

// -- timeout: 1s
func (q *Queries) SetOrderLockedAsset(ctx context.Context, arg SetOrderLockedAssetParams) (*Order, error) {
	return _SetOrderLockedAsset(ctx, q.AsReadOnly(), arg)
}

func _SetOrderLockedAsset(ctx context.Context, q CacheQuerierConn, arg SetOrderLockedAssetParams) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "orders.SetOrderLockedAsset", setOrderLockedAsset,
		arg.AccountID,
		arg.OrderID,
		arg.Locked,
		arg.LockedAsset)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateOrderId = `-- name: UpdateOrderId :one
UPDATE orders
SET order_id = $2
WHERE id = $1
RETURNING id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at
`

type UpdateOrderIdParams struct {
	ID      int64
	OrderID string
}

// -- timeout: 1s
func (q *Queries) UpdateOrderId(ctx context.Context, arg UpdateOrderIdParams) (*Order, error) {
	return _UpdateOrderId(ctx, q.AsReadOnly(), arg)
}

func _UpdateOrderId(ctx context.Context, q CacheQuerierConn, arg UpdateOrderIdParams) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "orders.UpdateOrderId", updateOrderId, arg.ID, arg.OrderID)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const upsertOrder = `-- name: UpsertOrder :one
INSERT INTO orders (bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, conditions, detail, status, reject_reason, reduce_only, post_only, tif, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34)
ON CONFLICT (account_id, order_id) DO UPDATE
SET drived_order_id = coalesce(EXCLUDED.drived_order_id, orders.drived_order_id),
    executed_qty = coalesce(EXCLUDED.executed_qty, orders.executed_qty),
    executed_price = coalesce(EXCLUDED.executed_price, orders.executed_price),
    avg_price = coalesce(EXCLUDED.avg_price, orders.avg_price),
    conditions = coalesce(EXCLUDED.conditions, orders.conditions),
    detail = coalesce(EXCLUDED.detail, orders.detail),
    status = coalesce(EXCLUDED.status, orders.status),
    reject_reason = coalesce(EXCLUDED.reject_reason, orders.reject_reason),
    working_ts = coalesce(orders.working_ts, EXCLUDED.working_ts),
    finished_ts = coalesce(EXCLUDED.finished_ts, orders.finished_ts),
    updated_ts = coalesce(EXCLUDED.updated_ts, orders.updated_ts),
    locked = CASE
        WHEN coalesce(EXCLUDED.status, orders.status) IN ('DONE', 'CANCELED', 'REJECTED', 'EXPIRED') THEN 0
        ELSE coalesce(EXCLUDED.locked, orders.locked)
    END,
    locked_asset = coalesce(EXCLUDED.locked_asset, orders.locked_asset),
    fee = coalesce(EXCLUDED.fee, orders.fee),
    fee_asset = coalesce(EXCLUDED.fee_asset, orders.fee_asset),
    realized_pnl = coalesce(EXCLUDED.realized_pnl, orders.realized_pnl),
    pnl_asset = coalesce(EXCLUDED.pnl_asset, orders.pnl_asset),
    updated_at = CURRENT_TIMESTAMP
WHERE orders.updated_ts <= EXCLUDED.updated_ts
RETURNING id, bot_id, account_id, order_id, client_order_id, drived_order_id, order_type, algo_type, source, exchange, symbol, side, is_buy, price, quantity, executed_qty, executed_price, avg_price, reduce_only, post_only, tif, conditions, detail, status, reject_reason, created_ts, working_ts, finished_ts, updated_ts, locked, locked_asset, fee, fee_asset, realized_pnl, pnl_asset, created_at, updated_at
`

type UpsertOrderParams struct {
	BotID         int32
	AccountID     string
	OrderID       string
	ClientOrderID string
	DrivedOrderID string
	OrderType     OrderType
	AlgoType      AlgoType
	Source        OrderSource
	Exchange      string
	Symbol        string
	Side          OrderSide
	IsBuy         bool
	Price         pgtype.Numeric
	Quantity      pgtype.Numeric
	ExecutedQty   pgtype.Numeric
	ExecutedPrice pgtype.Numeric
	AvgPrice      pgtype.Numeric
	Conditions    []byte
	Detail        []byte
	Status        string
	RejectReason  *string
	ReduceOnly    bool
	PostOnly      bool
	Tif           TimeInForce
	CreatedTs     time.Time
	WorkingTs     *time.Time
	FinishedTs    *time.Time
	UpdatedTs     time.Time
	Locked        pgtype.Numeric
	LockedAsset   *string
	Fee           pgtype.Numeric
	FeeAsset      *string
	RealizedPnl   pgtype.Numeric
	PnlAsset      *string
}

// -- timeout: 1s
func (q *Queries) UpsertOrder(ctx context.Context, arg UpsertOrderParams) (*Order, error) {
	return _UpsertOrder(ctx, q.AsReadOnly(), arg)
}

func _UpsertOrder(ctx context.Context, q CacheQuerierConn, arg UpsertOrderParams) (*Order, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "orders.UpsertOrder", upsertOrder,
		arg.BotID,
		arg.AccountID,
		arg.OrderID,
		arg.ClientOrderID,
		arg.DrivedOrderID,
		arg.OrderType,
		arg.AlgoType,
		arg.Source,
		arg.Exchange,
		arg.Symbol,
		arg.Side,
		arg.IsBuy,
		arg.Price,
		arg.Quantity,
		arg.ExecutedQty,
		arg.ExecutedPrice,
		arg.AvgPrice,
		arg.Conditions,
		arg.Detail,
		arg.Status,
		arg.RejectReason,
		arg.ReduceOnly,
		arg.PostOnly,
		arg.Tif,
		arg.CreatedTs,
		arg.WorkingTs,
		arg.FinishedTs,
		arg.UpdatedTs,
		arg.Locked,
		arg.LockedAsset,
		arg.Fee,
		arg.FeeAsset,
		arg.RealizedPnl,
		arg.PnlAsset)
	var i *Order = new(Order)
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.AccountID,
		&i.OrderID,
		&i.ClientOrderID,
		&i.DrivedOrderID,
		&i.OrderType,
		&i.AlgoType,
		&i.Source,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.IsBuy,
		&i.Price,
		&i.Quantity,
		&i.ExecutedQty,
		&i.ExecutedPrice,
		&i.AvgPrice,
		&i.ReduceOnly,
		&i.PostOnly,
		&i.Tif,
		&i.Conditions,
		&i.Detail,
		&i.Status,
		&i.RejectReason,
		&i.CreatedTs,
		&i.WorkingTs,
		&i.FinishedTs,
		&i.UpdatedTs,
		&i.Locked,
		&i.LockedAsset,
		&i.Fee,
		&i.FeeAsset,
		&i.RealizedPnl,
		&i.PnlAsset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Order)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,bot_id,account_id,order_id,client_order_id,drived_order_id,order_type,algo_type,source,exchange,symbol,side,is_buy,price,quantity,executed_qty,executed_price,avg_price,reduce_only,post_only,tif,conditions,detail,status,reject_reason,created_ts,working_ts,finished_ts,updated_ts,locked,locked_asset,fee,fee_asset,realized_pnl,pnl_asset,created_at,updated_at FROM \"orders\" ORDER BY id,bot_id,account_id,order_id,client_order_id,drived_order_id,exchange,symbol,is_buy,reduce_only,post_only,status,reject_reason,created_ts,working_ts,finished_ts,updated_ts,locked_asset,fee_asset,pnl_asset,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "orders.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var v Order
		if err := rows.Scan(&v.ID, &v.BotID, &v.AccountID, &v.OrderID, &v.ClientOrderID, &v.DrivedOrderID, &v.OrderType, &v.AlgoType, &v.Source, &v.Exchange, &v.Symbol, &v.Side, &v.IsBuy, &v.Price, &v.Quantity, &v.ExecutedQty, &v.ExecutedPrice, &v.AvgPrice, &v.ReduceOnly, &v.PostOnly, &v.Tif, &v.Conditions, &v.Detail, &v.Status, &v.RejectReason, &v.CreatedTs, &v.WorkingTs, &v.FinishedTs, &v.UpdatedTs, &v.Locked, &v.LockedAsset, &v.Fee, &v.FeeAsset, &v.RealizedPnl, &v.PnlAsset, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"orders\" (id,bot_id,account_id,order_id,client_order_id,drived_order_id,order_type,algo_type,source,exchange,symbol,side,is_buy,price,quantity,executed_qty,executed_price,avg_price,reduce_only,post_only,tif,conditions,detail,status,reject_reason,created_ts,working_ts,finished_ts,updated_ts,locked,locked_asset,fee,fee_asset,realized_pnl,pnl_asset,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37);"
	rows := make([]Order, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "orders.Load", sql, row.ID, row.BotID, row.AccountID, row.OrderID, row.ClientOrderID, row.DrivedOrderID, row.OrderType, row.AlgoType, row.Source, row.Exchange, row.Symbol, row.Side, row.IsBuy, row.Price, row.Quantity, row.ExecutedQty, row.ExecutedPrice, row.AvgPrice, row.ReduceOnly, row.PostOnly, row.Tif, row.Conditions, row.Detail, row.Status, row.RejectReason, row.CreatedTs, row.WorkingTs, row.FinishedTs, row.UpdatedTs, row.Locked, row.LockedAsset, row.Fee, row.FeeAsset, row.RealizedPnl, row.PnlAsset, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
