// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package llm_completion

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type LlmCompletionStatus string

const (
	LlmCompletionStatusActive     LlmCompletionStatus = "active"
	LlmCompletionStatusDeleted    LlmCompletionStatus = "deleted"
	LlmCompletionStatusOverridden LlmCompletionStatus = "overridden"
)

func (e *LlmCompletionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LlmCompletionStatus(s)
	case string:
		*e = LlmCompletionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LlmCompletionStatus: %T", src)
	}
	return nil
}

type NullLlmCompletionStatus struct {
	LlmCompletionStatus LlmCompletionStatus
	Valid               bool // Valid is true if LlmCompletionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLlmCompletionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LlmCompletionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LlmCompletionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLlmCompletionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LlmCompletionStatus), nil
}

func (e LlmCompletionStatus) Valid() bool {
	switch e {
	case LlmCompletionStatusActive,
		LlmCompletionStatusDeleted,
		LlmCompletionStatusOverridden:
		return true
	}
	return false
}

func AllLlmCompletionStatusValues() []LlmCompletionStatus {
	return []LlmCompletionStatus{
		LlmCompletionStatusActive,
		LlmCompletionStatusDeleted,
		LlmCompletionStatusOverridden,
	}
}

type LlmCompletion struct {
	ID        int64               `json:"id"`
	SessionID int64               `json:"session_id"`
	SceneKey  string              `json:"scene_key"`
	SceneID   int64               `json:"scene_id"`
	PromptID  int64               `json:"prompt_id"`
	Platform  string              `json:"platform"`
	Provider  string              `json:"provider"`
	Model     string              `json:"model"`
	Variables []byte              `json:"variables"`
	Messages  []byte              `json:"messages"`
	Question  string              `json:"question"`
	Answer    string              `json:"answer"`
	Error     string              `json:"error"`
	Duration  int32               `json:"duration"`
	Tokens    []byte              `json:"tokens"`
	Status    LlmCompletionStatus `json:"status"`
	CreatedAt time.Time           `json:"created_at"`
	UpdatedAt time.Time           `json:"updated_at"`
}
