// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package llm_completion

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const create = `-- name: Create :one
insert into public.llm_completion (
  session_id, scene_id, prompt_id, scene_key, platform, provider, model, variables, messages, question, answer, error, duration, tokens, status
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) returning id, session_id, scene_key, scene_id, prompt_id, platform, provider, model, variables, messages, question, answer, error, duration, tokens, status, created_at, updated_at
`

type CreateParams struct {
	SessionID int64
	SceneID   int64
	PromptID  int64
	SceneKey  string
	Platform  string
	Provider  string
	Model     string
	Variables []byte
	Messages  []byte
	Question  string
	Answer    string
	Error     string
	Duration  int32
	Tokens    []byte
	Status    LlmCompletionStatus
}

// -- timeout: 3s
func (q *Queries) Create(ctx context.Context, arg CreateParams) (*LlmCompletion, error) {
	return _Create(ctx, q.AsReadOnly(), arg)
}

func _Create(ctx context.Context, q CacheQuerierConn, arg CreateParams) (*LlmCompletion, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_completion.Create", create,
		arg.SessionID,
		arg.SceneID,
		arg.PromptID,
		arg.SceneKey,
		arg.Platform,
		arg.Provider,
		arg.Model,
		arg.Variables,
		arg.Messages,
		arg.Question,
		arg.Answer,
		arg.Error,
		arg.Duration,
		arg.Tokens,
		arg.Status)
	var i *LlmCompletion = new(LlmCompletion)
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SceneKey,
		&i.SceneID,
		&i.PromptID,
		&i.Platform,
		&i.Provider,
		&i.Model,
		&i.Variables,
		&i.Messages,
		&i.Question,
		&i.Answer,
		&i.Error,
		&i.Duration,
		&i.Tokens,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmCompletion)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getCompletionStats = `-- name: GetCompletionStats :one
SELECT
  COUNT(*)::bigint AS total_count,
  COUNT(*) FILTER (WHERE error = '')::bigint AS success_count,
  COUNT(*) FILTER (WHERE error != '')::bigint AS fail_count,
  COALESCE(AVG(duration) FILTER (WHERE error = ''), 0)::double precision AS avg_duration_ms
FROM public.llm_completion
WHERE created_at >= to_timestamp($1::bigint)::timestamptz
  AND created_at < to_timestamp($2::bigint)::timestamptz
`

type GetCompletionStatsParams struct {
	StartTs int64
	EndTs   int64
}

type GetCompletionStatsRow struct {
	TotalCount    int64
	SuccessCount  int64
	FailCount     int64
	AvgDurationMs float64
}

// -- timeout: 5s
func (q *Queries) GetCompletionStats(ctx context.Context, arg GetCompletionStatsParams) (*GetCompletionStatsRow, error) {
	return _GetCompletionStats(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetCompletionStats(ctx context.Context, arg GetCompletionStatsParams) (*GetCompletionStatsRow, error) {
	return _GetCompletionStats(ctx, q, arg)
}

func _GetCompletionStats(ctx context.Context, q CacheQuerierConn, arg GetCompletionStatsParams) (*GetCompletionStatsRow, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("llm_completion.GetCompletionStats")
	row := q.GetConn().WQueryRow(qctx, "llm_completion.GetCompletionStats", getCompletionStats, arg.StartTs, arg.EndTs)
	var i *GetCompletionStatsRow = new(GetCompletionStatsRow)
	err := row.Scan(
		&i.TotalCount,
		&i.SuccessCount,
		&i.FailCount,
		&i.AvgDurationMs,
	)
	if err == pgx.ErrNoRows {
		return (*GetCompletionStatsRow)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getCompletionStatsByScene = `-- name: GetCompletionStatsByScene :many
SELECT
  scene_key,
  scene_id,
  COUNT(*)::bigint AS total_count,
  COUNT(*) FILTER (WHERE error = '')::bigint AS success_count,
  COUNT(*) FILTER (WHERE error != '')::bigint AS fail_count,
  COALESCE(AVG(duration) FILTER (WHERE error = ''), 0)::double precision AS avg_duration_ms
FROM public.llm_completion
WHERE created_at >= to_timestamp($1::bigint)::timestamptz
  AND created_at < to_timestamp($2::bigint)::timestamptz
GROUP BY scene_key, scene_id
`

type GetCompletionStatsBySceneParams struct {
	StartTs int64
	EndTs   int64
}

type GetCompletionStatsBySceneRow struct {
	SceneKey      string
	SceneID       int64
	TotalCount    int64
	SuccessCount  int64
	FailCount     int64
	AvgDurationMs float64
}

// -- timeout: 5s
func (q *Queries) GetCompletionStatsByScene(ctx context.Context, arg GetCompletionStatsBySceneParams) ([]GetCompletionStatsBySceneRow, error) {
	return _GetCompletionStatsByScene(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetCompletionStatsByScene(ctx context.Context, arg GetCompletionStatsBySceneParams) ([]GetCompletionStatsBySceneRow, error) {
	return _GetCompletionStatsByScene(ctx, q, arg)
}

func _GetCompletionStatsByScene(ctx context.Context, q CacheQuerierConn, arg GetCompletionStatsBySceneParams) ([]GetCompletionStatsBySceneRow, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("llm_completion.GetCompletionStatsByScene")
	rows, err := q.GetConn().WQuery(qctx, "llm_completion.GetCompletionStatsByScene", getCompletionStatsByScene, arg.StartTs, arg.EndTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletionStatsBySceneRow
	for rows.Next() {
		var i *GetCompletionStatsBySceneRow = new(GetCompletionStatsBySceneRow)
		if err := rows.Scan(
			&i.SceneKey,
			&i.SceneID,
			&i.TotalCount,
			&i.SuccessCount,
			&i.FailCount,
			&i.AvgDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,session_id,scene_key,scene_id,prompt_id,platform,provider,model,variables,messages,question,answer,error,duration,tokens,status,created_at,updated_at FROM \"llm_completion\" ORDER BY id,session_id,scene_key,scene_id,prompt_id,platform,provider,model,question,answer,error,duration,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "llm_completion.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmCompletion
	for rows.Next() {
		var v LlmCompletion
		if err := rows.Scan(&v.ID, &v.SessionID, &v.SceneKey, &v.SceneID, &v.PromptID, &v.Platform, &v.Provider, &v.Model, &v.Variables, &v.Messages, &v.Question, &v.Answer, &v.Error, &v.Duration, &v.Tokens, &v.Status, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"llm_completion\" (id,session_id,scene_key,scene_id,prompt_id,platform,provider,model,variables,messages,question,answer,error,duration,tokens,status,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18);"
	rows := make([]LlmCompletion, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "llm_completion.Load", sql, row.ID, row.SessionID, row.SceneKey, row.SceneID, row.PromptID, row.Platform, row.Provider, row.Model, row.Variables, row.Messages, row.Question, row.Answer, row.Error, row.Duration, row.Tokens, row.Status, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
