// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	"time"

	calendar "github.com/wangliang139/llt-trade/server/pkg/repos/calendar"
	document "github.com/wangliang139/llt-trade/server/pkg/repos/document"
	types "github.com/wangliang139/llt-trade/server/pkg/types"
)

func CalendarRepo2Types(source *calendar.Calendar) *types.Calendar {
	var pTypesCalendar *types.Calendar
	if source != nil {
		var typesCalendar types.Calendar
		typesCalendar.ID = (*source).ID
		typesCalendar.DateID = (*source).DateID
		typesCalendar.Sid = (*source).Sid
		typesCalendar.Source = (*source).Source
		typesCalendar.Type = (*source).Type
		typesCalendar.Category = (*source).Category
		typesCalendar.Country = (*source).Country
		typesCalendar.Project = (*source).Project
		typesCalendar.Symbol = (*source).Symbol
		typesCalendar.Title = (*source).Title
		typesCalendar.Content = (*source).Content
		typesCalendar.Importance = (*source).Importance
		typesCalendar.Url = (*source).Url
		typesCalendar.Ext = (*source).Ext
		typesCalendar.PublishedAt = timeTimeToTimeTime((*source).PublishedAt)
		typesCalendar.CreatedAt = timeTimeToTimeTime((*source).CreatedAt)
		typesCalendar.UpdatedAt = timeTimeToTimeTime((*source).UpdatedAt)
		pTypesCalendar = &typesCalendar
	}
	return pTypesCalendar
}
func DocumentArchiveDocumentRowRepo2Types(source *document.ArchiveDocumentRow) *types.Document {
	var pTypesDocument *types.Document
	if source != nil {
		var typesDocument types.Document
		typesDocument.Id = (*source).ID
		typesDocument.Source = types.DocumentSource((*source).Source)
		typesDocument.Provider = (*source).Provider
		typesDocument.Catalog = (*source).Catalog
		typesDocument.Title = (*source).Title
		typesDocument.Content = (*source).Content
		typesDocument.AiTitle = (*source).AiTitle
		typesDocument.AiSummary = (*source).AiSummary
		typesDocument.AiTags = (*source).AiTags
		typesDocument.AiCoins = (*source).AiCoins
		typesDocument.AiInfluence = (*source).AiInfluence
		typesDocument.AiInfluenceScore = (*source).AiInfluenceScore
		typesDocument.AiSentiment = (*source).AiSentiment
		typesDocument.Format = (*source).Format
		typesDocument.Authors = (*source).Authors
		typesDocument.Lang = (*source).Lang
		typesDocument.Url = (*source).Url
		typesDocument.Md5 = (*source).Md5
		typesDocument.PublishedAt = timeTimeToTimeTime((*source).PublishedAt)
		typesDocument.Status = (*source).Status
		typesDocument.ErrMsg = (*source).ErrMsg
		typesDocument.DedupedBy = (*source).DedupedBy
		typesDocument.CreatedAt = timeTimeToTimeTime((*source).CreatedAt)
		typesDocument.UpdatedAt = timeTimeToTimeTime((*source).UpdatedAt)
		pTypesDocument = &typesDocument
	}
	return pTypesDocument
}
func DocumentGetByIdRowRepo2Types(source *document.GetByIdRow) *types.Document {
	var pTypesDocument *types.Document
	if source != nil {
		var typesDocument types.Document
		typesDocument.Id = (*source).ID
		typesDocument.Source = types.DocumentSource((*source).Source)
		typesDocument.Provider = (*source).Provider
		typesDocument.Catalog = (*source).Catalog
		typesDocument.Title = (*source).Title
		typesDocument.Content = (*source).Content
		typesDocument.AiTitle = (*source).AiTitle
		typesDocument.AiSummary = (*source).AiSummary
		typesDocument.AiTags = (*source).AiTags
		typesDocument.AiCoins = (*source).AiCoins
		typesDocument.AiInfluence = (*source).AiInfluence
		typesDocument.AiInfluenceScore = (*source).AiInfluenceScore
		typesDocument.AiSentiment = (*source).AiSentiment
		typesDocument.Format = (*source).Format
		typesDocument.Authors = (*source).Authors
		typesDocument.Lang = (*source).Lang
		typesDocument.Url = (*source).Url
		typesDocument.Md5 = (*source).Md5
		typesDocument.PublishedAt = timeTimeToTimeTime((*source).PublishedAt)
		typesDocument.Status = (*source).Status
		typesDocument.ErrMsg = (*source).ErrMsg
		typesDocument.DedupedBy = (*source).DedupedBy
		typesDocument.CreatedAt = timeTimeToTimeTime((*source).CreatedAt)
		typesDocument.UpdatedAt = timeTimeToTimeTime((*source).UpdatedAt)
		pTypesDocument = &typesDocument
	}
	return pTypesDocument
}
func DocumentQueryDocumentsRowRepo2Types(source *document.QueryDocumentsRow) *types.Document {
	var pTypesDocument *types.Document
	if source != nil {
		var typesDocument types.Document
		typesDocument.Id = (*source).ID
		typesDocument.Source = types.DocumentSource((*source).Source)
		typesDocument.Provider = (*source).Provider
		typesDocument.Catalog = (*source).Catalog
		typesDocument.Title = (*source).Title
		typesDocument.Content = (*source).Content
		typesDocument.AiTitle = (*source).AiTitle
		typesDocument.AiSummary = (*source).AiSummary
		typesDocument.AiTags = (*source).AiTags
		typesDocument.AiCoins = (*source).AiCoins
		typesDocument.AiInfluence = (*source).AiInfluence
		typesDocument.AiInfluenceScore = (*source).AiInfluenceScore
		typesDocument.AiSentiment = (*source).AiSentiment
		typesDocument.Format = (*source).Format
		typesDocument.Authors = (*source).Authors
		typesDocument.Lang = (*source).Lang
		typesDocument.Url = (*source).Url
		typesDocument.Md5 = (*source).Md5
		typesDocument.PublishedAt = timeTimeToTimeTime((*source).PublishedAt)
		typesDocument.Status = (*source).Status
		typesDocument.ErrMsg = (*source).ErrMsg
		typesDocument.DedupedBy = (*source).DedupedBy
		typesDocument.CreatedAt = timeTimeToTimeTime((*source).CreatedAt)
		typesDocument.UpdatedAt = timeTimeToTimeTime((*source).UpdatedAt)
		pTypesDocument = &typesDocument
	}
	return pTypesDocument
}
func DocumentRepo2Types(source *document.Document) *types.Document {
	var pTypesDocument *types.Document
	if source != nil {
		var typesDocument types.Document
		typesDocument.Id = (*source).ID
		typesDocument.Source = types.DocumentSource((*source).Source)
		typesDocument.Provider = (*source).Provider
		typesDocument.Catalog = (*source).Catalog
		typesDocument.Title = (*source).Title
		typesDocument.Content = (*source).Content
		typesDocument.AiTitle = (*source).AiTitle
		typesDocument.AiSummary = (*source).AiSummary
		typesDocument.AiTags = (*source).AiTags
		typesDocument.AiCoins = (*source).AiCoins
		typesDocument.AiInfluence = (*source).AiInfluence
		typesDocument.AiInfluenceScore = (*source).AiInfluenceScore
		typesDocument.AiSentiment = (*source).AiSentiment
		typesDocument.Format = (*source).Format
		typesDocument.Authors = (*source).Authors
		typesDocument.Lang = (*source).Lang
		typesDocument.Url = (*source).Url
		typesDocument.Md5 = (*source).Md5
		typesDocument.PublishedAt = timeTimeToTimeTime((*source).PublishedAt)
		typesDocument.Status = (*source).Status
		typesDocument.ErrMsg = (*source).ErrMsg
		typesDocument.DedupedBy = (*source).DedupedBy
		typesDocument.CreatedAt = timeTimeToTimeTime((*source).CreatedAt)
		typesDocument.UpdatedAt = timeTimeToTimeTime((*source).UpdatedAt)
		pTypesDocument = &typesDocument
	}
	return pTypesDocument
}
func DocumentSaveAiSummaryRowRepo2Types(source *document.SaveAiSummaryRow) *types.Document {
	var pTypesDocument *types.Document
	if source != nil {
		var typesDocument types.Document
		typesDocument.Id = (*source).ID
		typesDocument.Source = types.DocumentSource((*source).Source)
		typesDocument.Provider = (*source).Provider
		typesDocument.Catalog = (*source).Catalog
		typesDocument.Title = (*source).Title
		typesDocument.Content = (*source).Content
		typesDocument.AiTitle = (*source).AiTitle
		typesDocument.AiSummary = (*source).AiSummary
		typesDocument.AiTags = (*source).AiTags
		typesDocument.AiCoins = (*source).AiCoins
		typesDocument.AiInfluence = (*source).AiInfluence
		typesDocument.AiInfluenceScore = (*source).AiInfluenceScore
		typesDocument.AiSentiment = (*source).AiSentiment
		typesDocument.Format = (*source).Format
		typesDocument.Authors = (*source).Authors
		typesDocument.Lang = (*source).Lang
		typesDocument.Url = (*source).Url
		typesDocument.Md5 = (*source).Md5
		typesDocument.PublishedAt = timeTimeToTimeTime((*source).PublishedAt)
		typesDocument.Status = (*source).Status
		typesDocument.ErrMsg = (*source).ErrMsg
		typesDocument.DedupedBy = (*source).DedupedBy
		typesDocument.CreatedAt = timeTimeToTimeTime((*source).CreatedAt)
		typesDocument.UpdatedAt = timeTimeToTimeTime((*source).UpdatedAt)
		pTypesDocument = &typesDocument
	}
	return pTypesDocument
}
func DocumentSaveDraftToPendingRowRepo2Types(source *document.SaveDraftToPendingRow) *types.Document {
	var pTypesDocument *types.Document
	if source != nil {
		var typesDocument types.Document
		typesDocument.Id = (*source).ID
		typesDocument.Source = types.DocumentSource((*source).Source)
		typesDocument.Provider = (*source).Provider
		typesDocument.Catalog = (*source).Catalog
		typesDocument.Title = (*source).Title
		typesDocument.Content = (*source).Content
		typesDocument.AiTitle = (*source).AiTitle
		typesDocument.AiSummary = (*source).AiSummary
		typesDocument.AiTags = (*source).AiTags
		typesDocument.AiCoins = (*source).AiCoins
		typesDocument.AiInfluence = (*source).AiInfluence
		typesDocument.AiInfluenceScore = (*source).AiInfluenceScore
		typesDocument.AiSentiment = (*source).AiSentiment
		typesDocument.Format = (*source).Format
		typesDocument.Authors = (*source).Authors
		typesDocument.Lang = (*source).Lang
		typesDocument.Url = (*source).Url
		typesDocument.Md5 = (*source).Md5
		typesDocument.PublishedAt = timeTimeToTimeTime((*source).PublishedAt)
		typesDocument.Status = (*source).Status
		typesDocument.ErrMsg = (*source).ErrMsg
		typesDocument.DedupedBy = (*source).DedupedBy
		typesDocument.CreatedAt = timeTimeToTimeTime((*source).CreatedAt)
		typesDocument.UpdatedAt = timeTimeToTimeTime((*source).UpdatedAt)
		pTypesDocument = &typesDocument
	}
	return pTypesDocument
}
func timeTimeToTimeTime(source time.Time) time.Time {
	return source
}
