// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package llm_prompt

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const count = `-- name: Count :one
SELECT COUNT(1) FROM public.llm_prompt
WHERE deleted_at IS NULL
  AND scene_id = coalesce($1, scene_id)
  AND enabled = coalesce($2::boolean, enabled)
`

type CountParams struct {
	SceneID *int64
	Enabled *bool
}

// -- timeout: 1s
func (q *Queries) Count(ctx context.Context, arg CountParams) (*int64, error) {
	return _Count(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) Count(ctx context.Context, arg CountParams) (*int64, error) {
	return _Count(ctx, q, arg)
}

func _Count(ctx context.Context, q CacheQuerierConn, arg CountParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("llm_prompt.Count")
	row := q.GetConn().WQueryRow(qctx, "llm_prompt.Count", count, arg.SceneID, arg.Enabled)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const create = `-- name: Create :one
INSERT INTO public.llm_prompt (scene_id, scene_key, platform, name, model, providers, config, messages, timeout, weight, variants, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
returning id, scene_key, scene_id, platform, name, model, providers, config, messages, timeout, weight, variants, enabled, deleted_at, created_at, updated_at
`

type CreateParams struct {
	SceneID   int64
	SceneKey  string
	Platform  string
	Name      string
	Model     string
	Providers []string
	Config    []byte
	Messages  []byte
	Timeout   int32
	Weight    int32
	Variants  []string
	Enabled   bool
}

// -- timeout: 1s
func (q *Queries) Create(ctx context.Context, arg CreateParams) (*LlmPrompt, error) {
	return _Create(ctx, q.AsReadOnly(), arg)
}

func _Create(ctx context.Context, q CacheQuerierConn, arg CreateParams) (*LlmPrompt, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_prompt.Create", create,
		arg.SceneID,
		arg.SceneKey,
		arg.Platform,
		arg.Name,
		arg.Model,
		arg.Providers,
		arg.Config,
		arg.Messages,
		arg.Timeout,
		arg.Weight,
		arg.Variants,
		arg.Enabled)
	var i *LlmPrompt = new(LlmPrompt)
	err := row.Scan(
		&i.ID,
		&i.SceneKey,
		&i.SceneID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.Providers,
		&i.Config,
		&i.Messages,
		&i.Timeout,
		&i.Weight,
		&i.Variants,
		&i.Enabled,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmPrompt)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const delete = `-- name: Delete :execrows
UPDATE public.llm_prompt
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) Delete(ctx context.Context, id int64) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	result, err := q.db.WExec(qctx, "llm_prompt.Delete", delete, id)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const deleteBySceneID = `-- name: DeleteBySceneID :execrows
UPDATE public.llm_prompt
SET deleted_at = now(),
    updated_at = now()
WHERE scene_id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) DeleteBySceneID(ctx context.Context, sceneID int64) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	result, err := q.db.WExec(qctx, "llm_prompt.DeleteBySceneID", deleteBySceneID, sceneID)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const getByID = `-- name: GetByID :one
SELECT id, scene_key, scene_id, platform, name, model, providers, config, messages, timeout, weight, variants, enabled, deleted_at, created_at, updated_at FROM public.llm_prompt
WHERE id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) GetByID(ctx context.Context, id int64) (*LlmPrompt, error) {
	return _GetByID(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetByID(ctx context.Context, id int64) (*LlmPrompt, error) {
	return _GetByID(ctx, q, id)
}

func _GetByID(ctx context.Context, q CacheQuerierConn, id int64) (*LlmPrompt, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("llm_prompt.GetByID")
	row := q.GetConn().WQueryRow(qctx, "llm_prompt.GetByID", getByID, id)
	var i *LlmPrompt = new(LlmPrompt)
	err := row.Scan(
		&i.ID,
		&i.SceneKey,
		&i.SceneID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.Providers,
		&i.Config,
		&i.Messages,
		&i.Timeout,
		&i.Weight,
		&i.Variants,
		&i.Enabled,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmPrompt)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getBySceneID = `-- name: GetBySceneID :many
SELECT id, scene_key, scene_id, platform, name, model, providers, config, messages, timeout, weight, variants, enabled, deleted_at, created_at, updated_at FROM public.llm_prompt
WHERE scene_id = $1
  AND enabled = coalesce($2::boolean, enabled)
  AND deleted_at IS NULL
ORDER BY weight DESC, id
`

type GetBySceneIDParams struct {
	SceneID int64
	Enabled *bool
}

// -- timeout: 2s
func (q *Queries) GetBySceneID(ctx context.Context, arg GetBySceneIDParams) ([]LlmPrompt, error) {
	return _GetBySceneID(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetBySceneID(ctx context.Context, arg GetBySceneIDParams) ([]LlmPrompt, error) {
	return _GetBySceneID(ctx, q, arg)
}

func _GetBySceneID(ctx context.Context, q CacheQuerierConn, arg GetBySceneIDParams) ([]LlmPrompt, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("llm_prompt.GetBySceneID")
	rows, err := q.GetConn().WQuery(qctx, "llm_prompt.GetBySceneID", getBySceneID, arg.SceneID, arg.Enabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmPrompt
	for rows.Next() {
		var i *LlmPrompt = new(LlmPrompt)
		if err := rows.Scan(
			&i.ID,
			&i.SceneKey,
			&i.SceneID,
			&i.Platform,
			&i.Name,
			&i.Model,
			&i.Providers,
			&i.Config,
			&i.Messages,
			&i.Timeout,
			&i.Weight,
			&i.Variants,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const getBySceneKey = `-- name: GetBySceneKey :many
SELECT id, scene_key, scene_id, platform, name, model, providers, config, messages, timeout, weight, variants, enabled, deleted_at, created_at, updated_at FROM public.llm_prompt
WHERE scene_key = $1
  AND deleted_at IS NULL
  AND enabled = coalesce($2::boolean, enabled)
ORDER BY weight DESC, id
`

type GetBySceneKeyParams struct {
	SceneKey string
	Enabled  *bool
}

// -- timeout: 2s
func (q *Queries) GetBySceneKey(ctx context.Context, arg GetBySceneKeyParams) ([]LlmPrompt, error) {
	return _GetBySceneKey(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetBySceneKey(ctx context.Context, arg GetBySceneKeyParams) ([]LlmPrompt, error) {
	return _GetBySceneKey(ctx, q, arg)
}

func _GetBySceneKey(ctx context.Context, q CacheQuerierConn, arg GetBySceneKeyParams) ([]LlmPrompt, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("llm_prompt.GetBySceneKey")
	rows, err := q.GetConn().WQuery(qctx, "llm_prompt.GetBySceneKey", getBySceneKey, arg.SceneKey, arg.Enabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmPrompt
	for rows.Next() {
		var i *LlmPrompt = new(LlmPrompt)
		if err := rows.Scan(
			&i.ID,
			&i.SceneKey,
			&i.SceneID,
			&i.Platform,
			&i.Name,
			&i.Model,
			&i.Providers,
			&i.Config,
			&i.Messages,
			&i.Timeout,
			&i.Weight,
			&i.Variants,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const getBySceneKeyAndVariant = `-- name: GetBySceneKeyAndVariant :many
SELECT id, scene_key, scene_id, platform, name, model, providers, config, messages, timeout, weight, variants, enabled, deleted_at, created_at, updated_at FROM public.llm_prompt
WHERE scene_key = $1
  AND $2::varchar = ANY(variants)
  AND deleted_at IS NULL
  AND enabled = coalesce($3::boolean, enabled)
ORDER BY weight DESC, id
`

type GetBySceneKeyAndVariantParams struct {
	SceneKey string
	Variant  string
	Enabled  *bool
}

// -- timeout: 2s
func (q *Queries) GetBySceneKeyAndVariant(ctx context.Context, arg GetBySceneKeyAndVariantParams) ([]LlmPrompt, error) {
	return _GetBySceneKeyAndVariant(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetBySceneKeyAndVariant(ctx context.Context, arg GetBySceneKeyAndVariantParams) ([]LlmPrompt, error) {
	return _GetBySceneKeyAndVariant(ctx, q, arg)
}

func _GetBySceneKeyAndVariant(ctx context.Context, q CacheQuerierConn, arg GetBySceneKeyAndVariantParams) ([]LlmPrompt, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("llm_prompt.GetBySceneKeyAndVariant")
	rows, err := q.GetConn().WQuery(qctx, "llm_prompt.GetBySceneKeyAndVariant", getBySceneKeyAndVariant, arg.SceneKey, arg.Variant, arg.Enabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmPrompt
	for rows.Next() {
		var i *LlmPrompt = new(LlmPrompt)
		if err := rows.Scan(
			&i.ID,
			&i.SceneKey,
			&i.SceneID,
			&i.Platform,
			&i.Name,
			&i.Model,
			&i.Providers,
			&i.Config,
			&i.Messages,
			&i.Timeout,
			&i.Weight,
			&i.Variants,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const list = `-- name: List :many
SELECT id, scene_key, scene_id, platform, name, model, providers, config, messages, timeout, weight, variants, enabled, deleted_at, created_at, updated_at FROM public.llm_prompt
WHERE deleted_at IS NULL
  AND scene_id = coalesce($1, scene_id)
  AND enabled = coalesce($2::boolean, enabled)
ORDER BY weight DESC, id
OFFSET $3::int LIMIT $4::int
`

type ListParams struct {
	SceneID *int64
	Enabled *bool
	Offset  int32
	Limit   int32
}

// -- timeout: 2s
func (q *Queries) List(ctx context.Context, arg ListParams) ([]LlmPrompt, error) {
	return _List(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) List(ctx context.Context, arg ListParams) ([]LlmPrompt, error) {
	return _List(ctx, q, arg)
}

func _List(ctx context.Context, q CacheQuerierConn, arg ListParams) ([]LlmPrompt, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("llm_prompt.List")
	rows, err := q.GetConn().WQuery(qctx, "llm_prompt.List", list,
		arg.SceneID,
		arg.Enabled,
		arg.Offset,
		arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmPrompt
	for rows.Next() {
		var i *LlmPrompt = new(LlmPrompt)
		if err := rows.Scan(
			&i.ID,
			&i.SceneKey,
			&i.SceneID,
			&i.Platform,
			&i.Name,
			&i.Model,
			&i.Providers,
			&i.Config,
			&i.Messages,
			&i.Timeout,
			&i.Weight,
			&i.Variants,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const update = `-- name: Update :one
UPDATE public.llm_prompt
SET name = coalesce($1, name),
    timeout = coalesce($2, timeout),
    weight = coalesce($3, weight),
    variants = CASE 
        WHEN $4::varchar[] IS NULL THEN variants
        ELSE $4::varchar[]
    END,
    enabled = coalesce($5, enabled),
    updated_at = now()
WHERE id = $6 AND deleted_at IS NULL
returning id, scene_key, scene_id, platform, name, model, providers, config, messages, timeout, weight, variants, enabled, deleted_at, created_at, updated_at
`

type UpdateParams struct {
	Name     *string
	Timeout  *int32
	Weight   *int32
	Variants []string
	Enabled  *bool
	ID       int64
}

// -- timeout: 1s
func (q *Queries) Update(ctx context.Context, arg UpdateParams) (*LlmPrompt, error) {
	return _Update(ctx, q.AsReadOnly(), arg)
}

func _Update(ctx context.Context, q CacheQuerierConn, arg UpdateParams) (*LlmPrompt, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_prompt.Update", update,
		arg.Name,
		arg.Timeout,
		arg.Weight,
		arg.Variants,
		arg.Enabled,
		arg.ID)
	var i *LlmPrompt = new(LlmPrompt)
	err := row.Scan(
		&i.ID,
		&i.SceneKey,
		&i.SceneID,
		&i.Platform,
		&i.Name,
		&i.Model,
		&i.Providers,
		&i.Config,
		&i.Messages,
		&i.Timeout,
		&i.Weight,
		&i.Variants,
		&i.Enabled,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmPrompt)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,scene_key,scene_id,platform,name,model,providers,config,messages,timeout,weight,variants,enabled,deleted_at,created_at,updated_at FROM \"llm_prompt\" ORDER BY id,scene_key,scene_id,platform,name,model,timeout,weight,enabled,deleted_at,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "llm_prompt.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmPrompt
	for rows.Next() {
		var v LlmPrompt
		if err := rows.Scan(&v.ID, &v.SceneKey, &v.SceneID, &v.Platform, &v.Name, &v.Model, &v.Providers, &v.Config, &v.Messages, &v.Timeout, &v.Weight, &v.Variants, &v.Enabled, &v.DeletedAt, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"llm_prompt\" (id,scene_key,scene_id,platform,name,model,providers,config,messages,timeout,weight,variants,enabled,deleted_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16);"
	rows := make([]LlmPrompt, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "llm_prompt.Load", sql, row.ID, row.SceneKey, row.SceneID, row.Platform, row.Name, row.Model, row.Providers, row.Config, row.Messages, row.Timeout, row.Weight, row.Variants, row.Enabled, row.DeletedAt, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
