// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package api_keys

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const countActiveUserApiKeysByUserID = `-- name: CountActiveUserApiKeysByUserID :one
SELECT COUNT(*)::bigint AS count FROM api_keys
WHERE user_id = $1 AND deleted_at IS NULL
`

// -- timeout: 2s
func (q *Queries) CountActiveUserApiKeysByUserID(ctx context.Context, userID int64) (*int64, error) {
	return _CountActiveUserApiKeysByUserID(ctx, q.AsReadOnly(), userID)
}

func (q *ReadOnlyQueries) CountActiveUserApiKeysByUserID(ctx context.Context, userID int64) (*int64, error) {
	return _CountActiveUserApiKeysByUserID(ctx, q, userID)
}

func _CountActiveUserApiKeysByUserID(ctx context.Context, q CacheQuerierConn, userID int64) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("api_keys.CountActiveUserApiKeysByUserID")
	row := q.GetConn().WQueryRow(qctx, "api_keys.CountActiveUserApiKeysByUserID", countActiveUserApiKeysByUserID, userID)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const countActiveUserApiKeysByUserIDAndName = `-- name: CountActiveUserApiKeysByUserIDAndName :one
SELECT COUNT(*)::bigint AS count FROM api_keys
WHERE user_id = $1 AND name = $2 AND deleted_at IS NULL
`

type CountActiveUserApiKeysByUserIDAndNameParams struct {
	UserID int64
	Name   string
}

// -- timeout: 2s
func (q *Queries) CountActiveUserApiKeysByUserIDAndName(ctx context.Context, arg CountActiveUserApiKeysByUserIDAndNameParams) (*int64, error) {
	return _CountActiveUserApiKeysByUserIDAndName(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) CountActiveUserApiKeysByUserIDAndName(ctx context.Context, arg CountActiveUserApiKeysByUserIDAndNameParams) (*int64, error) {
	return _CountActiveUserApiKeysByUserIDAndName(ctx, q, arg)
}

func _CountActiveUserApiKeysByUserIDAndName(ctx context.Context, q CacheQuerierConn, arg CountActiveUserApiKeysByUserIDAndNameParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("api_keys.CountActiveUserApiKeysByUserIDAndName")
	row := q.GetConn().WQueryRow(qctx, "api_keys.CountActiveUserApiKeysByUserIDAndName", countActiveUserApiKeysByUserIDAndName, arg.UserID, arg.Name)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const createUserApiKey = `-- name: CreateUserApiKey :one
INSERT INTO api_keys (
    user_id,
    name,
    key_lookup,
    secret_hash,
    key_prefix,
    permissions
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, name, key_lookup, secret_hash, key_prefix, permissions, created_at, updated_at, deleted_at
`

type CreateUserApiKeyParams struct {
	UserID      int64
	Name        string
	KeyLookup   string
	SecretHash  string
	KeyPrefix   string
	Permissions []string
}

// -- timeout: 2s
func (q *Queries) CreateUserApiKey(ctx context.Context, arg CreateUserApiKeyParams) (*ApiKey, error) {
	return _CreateUserApiKey(ctx, q.AsReadOnly(), arg)
}

func _CreateUserApiKey(ctx context.Context, q CacheQuerierConn, arg CreateUserApiKeyParams) (*ApiKey, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "api_keys.CreateUserApiKey", createUserApiKey,
		arg.UserID,
		arg.Name,
		arg.KeyLookup,
		arg.SecretHash,
		arg.KeyPrefix,
		arg.Permissions)
	var i *ApiKey = new(ApiKey)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyLookup,
		&i.SecretHash,
		&i.KeyPrefix,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*ApiKey)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getUserApiKeyByLookup = `-- name: GetUserApiKeyByLookup :one
SELECT id, user_id, name, key_lookup, secret_hash, key_prefix, permissions, created_at, updated_at, deleted_at FROM api_keys
WHERE key_lookup = $1 AND deleted_at IS NULL
LIMIT 1
`

// -- timeout: 2s
func (q *Queries) GetUserApiKeyByLookup(ctx context.Context, keyLookup string) (*ApiKey, error) {
	return _GetUserApiKeyByLookup(ctx, q.AsReadOnly(), keyLookup)
}

func (q *ReadOnlyQueries) GetUserApiKeyByLookup(ctx context.Context, keyLookup string) (*ApiKey, error) {
	return _GetUserApiKeyByLookup(ctx, q, keyLookup)
}

func _GetUserApiKeyByLookup(ctx context.Context, q CacheQuerierConn, keyLookup string) (*ApiKey, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("api_keys.GetUserApiKeyByLookup")
	row := q.GetConn().WQueryRow(qctx, "api_keys.GetUserApiKeyByLookup", getUserApiKeyByLookup, keyLookup)
	var i *ApiKey = new(ApiKey)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyLookup,
		&i.SecretHash,
		&i.KeyPrefix,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*ApiKey)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const listUserApiKeysByUserID = `-- name: ListUserApiKeysByUserID :many
SELECT id, user_id, name, key_lookup, secret_hash, key_prefix, permissions, created_at, updated_at, deleted_at FROM api_keys
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

// -- timeout: 2s
func (q *Queries) ListUserApiKeysByUserID(ctx context.Context, userID int64) ([]ApiKey, error) {
	return _ListUserApiKeysByUserID(ctx, q.AsReadOnly(), userID)
}

func (q *ReadOnlyQueries) ListUserApiKeysByUserID(ctx context.Context, userID int64) ([]ApiKey, error) {
	return _ListUserApiKeysByUserID(ctx, q, userID)
}

func _ListUserApiKeysByUserID(ctx context.Context, q CacheQuerierConn, userID int64) ([]ApiKey, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("api_keys.ListUserApiKeysByUserID")
	rows, err := q.GetConn().WQuery(qctx, "api_keys.ListUserApiKeysByUserID", listUserApiKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i *ApiKey = new(ApiKey)
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyLookup,
			&i.SecretHash,
			&i.KeyPrefix,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const softDeleteUserApiKey = `-- name: SoftDeleteUserApiKey :execrows
UPDATE api_keys
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserApiKeyParams struct {
	ID     int64
	UserID int64
}

// -- timeout: 2s
func (q *Queries) SoftDeleteUserApiKey(ctx context.Context, arg SoftDeleteUserApiKeyParams) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	result, err := q.db.WExec(qctx, "api_keys.SoftDeleteUserApiKey", softDeleteUserApiKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,user_id,name,key_lookup,secret_hash,key_prefix,permissions,created_at,updated_at,deleted_at FROM \"api_keys\" ORDER BY id,user_id,name,key_lookup,secret_hash,key_prefix,created_at,updated_at,deleted_at ASC;"
	rows, err := q.db.WQuery(ctx, "api_keys.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var v ApiKey
		if err := rows.Scan(&v.ID, &v.UserID, &v.Name, &v.KeyLookup, &v.SecretHash, &v.KeyPrefix, &v.Permissions, &v.CreatedAt, &v.UpdatedAt, &v.DeletedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"api_keys\" (id,user_id,name,key_lookup,secret_hash,key_prefix,permissions,created_at,updated_at,deleted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10);"
	rows := make([]ApiKey, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "api_keys.Load", sql, row.ID, row.UserID, row.Name, row.KeyLookup, row.SecretHash, row.KeyPrefix, row.Permissions, row.CreatedAt, row.UpdatedAt, row.DeletedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
