// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package datasource

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type SignalType string

const (
	SignalTypeKline    SignalType = "kline"
	SignalTypeTrade    SignalType = "trade"
	SignalTypeDepth    SignalType = "depth"
	SignalTypeTicker   SignalType = "ticker"
	SignalTypeSocial   SignalType = "social"
	SignalTypeTimer    SignalType = "timer"
	SignalTypeOrder    SignalType = "order"
	SignalTypePosition SignalType = "position"
	SignalTypeBalance  SignalType = "balance"
	SignalTypeRisk     SignalType = "risk"
	SignalTypeSystem   SignalType = "system"
)

func (e *SignalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignalType(s)
	case string:
		*e = SignalType(s)
	default:
		return fmt.Errorf("unsupported scan type for SignalType: %T", src)
	}
	return nil
}

type NullSignalType struct {
	SignalType SignalType
	Valid      bool // Valid is true if SignalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignalType) Scan(value interface{}) error {
	if value == nil {
		ns.SignalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignalType), nil
}

func (e SignalType) Valid() bool {
	switch e {
	case SignalTypeKline,
		SignalTypeTrade,
		SignalTypeDepth,
		SignalTypeTicker,
		SignalTypeSocial,
		SignalTypeTimer,
		SignalTypeOrder,
		SignalTypePosition,
		SignalTypeBalance,
		SignalTypeRisk,
		SignalTypeSystem:
		return true
	}
	return false
}

func AllSignalTypeValues() []SignalType {
	return []SignalType{
		SignalTypeKline,
		SignalTypeTrade,
		SignalTypeDepth,
		SignalTypeTicker,
		SignalTypeSocial,
		SignalTypeTimer,
		SignalTypeOrder,
		SignalTypePosition,
		SignalTypeBalance,
		SignalTypeRisk,
		SignalTypeSystem,
	}
}

type Datasource struct {
	ID          int32      `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Type        SignalType `json:"type"`
	Exchange    string     `json:"exchange"`
	Symbol      string     `json:"symbol"`
	Props       []byte     `json:"props"`
	StartTs     time.Time  `json:"start_ts"`
	EndTs       time.Time  `json:"end_ts"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}
