// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package datasource

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const countDatasources = `-- name: CountDatasources :one
SELECT COUNT(*) FROM datasources
WHERE deleted_at IS NULL
  AND ($1::signal_type IS NULL OR type = $1::signal_type)
  AND ($2::varchar IS NULL OR exchange = $2::varchar)
  AND ($3::varchar IS NULL OR symbol = $3::varchar)
`

type CountDatasourcesParams struct {
	Type     NullSignalType
	Exchange *string
	Symbol   *string
}

// -- timeout: 5s
func (q *Queries) CountDatasources(ctx context.Context, arg CountDatasourcesParams) (*int64, error) {
	return _CountDatasources(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) CountDatasources(ctx context.Context, arg CountDatasourcesParams) (*int64, error) {
	return _CountDatasources(ctx, q, arg)
}

func _CountDatasources(ctx context.Context, q CacheQuerierConn, arg CountDatasourcesParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("datasource.CountDatasources")
	row := q.GetConn().WQueryRow(qctx, "datasource.CountDatasources", countDatasources, arg.Type, arg.Exchange, arg.Symbol)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const createDataSource = `-- name: CreateDataSource :one
INSERT INTO datasources (name, description, type, exchange, symbol, props, start_ts, end_ts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, type, exchange, symbol, props, start_ts, end_ts, created_at, updated_at, deleted_at
`

type CreateDataSourceParams struct {
	Name        string
	Description string
	Type        SignalType
	Exchange    string
	Symbol      string
	Props       []byte
	StartTs     time.Time
	EndTs       time.Time
}

// -- timeout: 1s
func (q *Queries) CreateDataSource(ctx context.Context, arg CreateDataSourceParams) (*Datasource, error) {
	return _CreateDataSource(ctx, q.AsReadOnly(), arg)
}

func _CreateDataSource(ctx context.Context, q CacheQuerierConn, arg CreateDataSourceParams) (*Datasource, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "datasource.CreateDataSource", createDataSource,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Exchange,
		arg.Symbol,
		arg.Props,
		arg.StartTs,
		arg.EndTs)
	var i *Datasource = new(Datasource)
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Exchange,
		&i.Symbol,
		&i.Props,
		&i.StartTs,
		&i.EndTs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Datasource)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const deleteDatasource = `-- name: DeleteDatasource :exec
UPDATE datasources
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) DeleteDatasource(ctx context.Context, id int32) error {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	_, err := q.db.WExec(qctx, "datasource.DeleteDatasource", deleteDatasource, id)
	if err != nil {
		return err
	}

	return nil
}

const getById = `-- name: GetById :one
SELECT id, name, description, type, exchange, symbol, props, start_ts, end_ts, created_at, updated_at, deleted_at FROM datasources WHERE id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) GetById(ctx context.Context, id int32) (*Datasource, error) {
	return _GetById(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetById(ctx context.Context, id int32) (*Datasource, error) {
	return _GetById(ctx, q, id)
}

func _GetById(ctx context.Context, q CacheQuerierConn, id int32) (*Datasource, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("datasource.GetById")
	row := q.GetConn().WQueryRow(qctx, "datasource.GetById", getById, id)
	var i *Datasource = new(Datasource)
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Exchange,
		&i.Symbol,
		&i.Props,
		&i.StartTs,
		&i.EndTs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Datasource)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const listDatasources = `-- name: ListDatasources :many
SELECT id, name, description, type, exchange, symbol, props, start_ts, end_ts, created_at, updated_at, deleted_at FROM datasources
WHERE deleted_at IS NULL
  AND ($1::signal_type IS NULL OR type = $1::signal_type)
  AND ($2::varchar IS NULL OR exchange = $2::varchar)
  AND ($3::varchar IS NULL OR symbol = $3::varchar)
ORDER BY created_at DESC
OFFSET $4::int8
LIMIT $5::int8
`

type ListDatasourcesParams struct {
	Type     NullSignalType
	Exchange *string
	Symbol   *string
	Offset   int64
	Limit    int64
}

// -- timeout: 5s
func (q *Queries) ListDatasources(ctx context.Context, arg ListDatasourcesParams) ([]Datasource, error) {
	return _ListDatasources(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListDatasources(ctx context.Context, arg ListDatasourcesParams) ([]Datasource, error) {
	return _ListDatasources(ctx, q, arg)
}

func _ListDatasources(ctx context.Context, q CacheQuerierConn, arg ListDatasourcesParams) ([]Datasource, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("datasource.ListDatasources")
	rows, err := q.GetConn().WQuery(qctx, "datasource.ListDatasources", listDatasources,
		arg.Type,
		arg.Exchange,
		arg.Symbol,
		arg.Offset,
		arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datasource
	for rows.Next() {
		var i *Datasource = new(Datasource)
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Exchange,
			&i.Symbol,
			&i.Props,
			&i.StartTs,
			&i.EndTs,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const updateDatasource = `-- name: UpdateDatasource :one
UPDATE datasources
SET 
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  start_ts = COALESCE($4, start_ts),
  end_ts = COALESCE($5, end_ts),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, type, exchange, symbol, props, start_ts, end_ts, created_at, updated_at, deleted_at
`

type UpdateDatasourceParams struct {
	ID          int32
	Name        string
	Description string
	StartTs     time.Time
	EndTs       time.Time
}

// -- timeout: 1s
func (q *Queries) UpdateDatasource(ctx context.Context, arg UpdateDatasourceParams) (*Datasource, error) {
	return _UpdateDatasource(ctx, q.AsReadOnly(), arg)
}

func _UpdateDatasource(ctx context.Context, q CacheQuerierConn, arg UpdateDatasourceParams) (*Datasource, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "datasource.UpdateDatasource", updateDatasource,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.StartTs,
		arg.EndTs)
	var i *Datasource = new(Datasource)
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Exchange,
		&i.Symbol,
		&i.Props,
		&i.StartTs,
		&i.EndTs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Datasource)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,name,description,type,exchange,symbol,props,start_ts,end_ts,created_at,updated_at,deleted_at FROM \"datasources\" ORDER BY id,name,description,exchange,symbol,start_ts,end_ts,created_at,updated_at,deleted_at ASC;"
	rows, err := q.db.WQuery(ctx, "datasource.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Datasource
	for rows.Next() {
		var v Datasource
		if err := rows.Scan(&v.ID, &v.Name, &v.Description, &v.Type, &v.Exchange, &v.Symbol, &v.Props, &v.StartTs, &v.EndTs, &v.CreatedAt, &v.UpdatedAt, &v.DeletedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"datasources\" (id,name,description,type,exchange,symbol,props,start_ts,end_ts,created_at,updated_at,deleted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12);"
	rows := make([]Datasource, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "datasource.Load", sql, row.ID, row.Name, row.Description, row.Type, row.Exchange, row.Symbol, row.Props, row.StartTs, row.EndTs, row.CreatedAt, row.UpdatedAt, row.DeletedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
