// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package tg_channel

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type DocumentCatalog string

const (
	DocumentCatalogAirdrop                 DocumentCatalog = "airdrop"
	DocumentCatalogApi                     DocumentCatalog = "api"
	DocumentCatalogCryptocurrencyListing   DocumentCatalog = "cryptocurrency_listing"
	DocumentCatalogCryptocurrencyDelisting DocumentCatalog = "cryptocurrency_delisting"
	DocumentCatalogActivity                DocumentCatalog = "activity"
	DocumentCatalogNews                    DocumentCatalog = "news"
	DocumentCatalogFlashNews               DocumentCatalog = "flash_news"
	DocumentCatalogOther                   DocumentCatalog = "other"
)

func (e *DocumentCatalog) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentCatalog(s)
	case string:
		*e = DocumentCatalog(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentCatalog: %T", src)
	}
	return nil
}

type NullDocumentCatalog struct {
	DocumentCatalog DocumentCatalog
	Valid           bool // Valid is true if DocumentCatalog is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentCatalog) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentCatalog, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentCatalog.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentCatalog) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentCatalog), nil
}

func (e DocumentCatalog) Valid() bool {
	switch e {
	case DocumentCatalogAirdrop,
		DocumentCatalogApi,
		DocumentCatalogCryptocurrencyListing,
		DocumentCatalogCryptocurrencyDelisting,
		DocumentCatalogActivity,
		DocumentCatalogNews,
		DocumentCatalogFlashNews,
		DocumentCatalogOther:
		return true
	}
	return false
}

func AllDocumentCatalogValues() []DocumentCatalog {
	return []DocumentCatalog{
		DocumentCatalogAirdrop,
		DocumentCatalogApi,
		DocumentCatalogCryptocurrencyListing,
		DocumentCatalogCryptocurrencyDelisting,
		DocumentCatalogActivity,
		DocumentCatalogNews,
		DocumentCatalogFlashNews,
		DocumentCatalogOther,
	}
}

type DocumentFormat string

const (
	DocumentFormatMarkdown DocumentFormat = "markdown"
	DocumentFormatTxt      DocumentFormat = "txt"
	DocumentFormatHtml     DocumentFormat = "html"
)

func (e *DocumentFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentFormat(s)
	case string:
		*e = DocumentFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentFormat: %T", src)
	}
	return nil
}

type NullDocumentFormat struct {
	DocumentFormat DocumentFormat
	Valid          bool // Valid is true if DocumentFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentFormat) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentFormat), nil
}

func (e DocumentFormat) Valid() bool {
	switch e {
	case DocumentFormatMarkdown,
		DocumentFormatTxt,
		DocumentFormatHtml:
		return true
	}
	return false
}

func AllDocumentFormatValues() []DocumentFormat {
	return []DocumentFormat{
		DocumentFormatMarkdown,
		DocumentFormatTxt,
		DocumentFormatHtml,
	}
}

type DocumentStatus string

const (
	DocumentStatusDraft         DocumentStatus = "draft"
	DocumentStatusDraftFailed   DocumentStatus = "draft_failed"
	DocumentStatusPending       DocumentStatus = "pending"
	DocumentStatusPendingFailed DocumentStatus = "pending_failed"
	DocumentStatusActive        DocumentStatus = "active"
	DocumentStatusArchived      DocumentStatus = "archived"
	DocumentStatusDeduped       DocumentStatus = "deduped"
	DocumentStatusTimeout       DocumentStatus = "timeout"
)

func (e *DocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentStatus(s)
	case string:
		*e = DocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentStatus: %T", src)
	}
	return nil
}

type NullDocumentStatus struct {
	DocumentStatus DocumentStatus
	Valid          bool // Valid is true if DocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentStatus), nil
}

func (e DocumentStatus) Valid() bool {
	switch e {
	case DocumentStatusDraft,
		DocumentStatusDraftFailed,
		DocumentStatusPending,
		DocumentStatusPendingFailed,
		DocumentStatusActive,
		DocumentStatusArchived,
		DocumentStatusDeduped,
		DocumentStatusTimeout:
		return true
	}
	return false
}

func AllDocumentStatusValues() []DocumentStatus {
	return []DocumentStatus{
		DocumentStatusDraft,
		DocumentStatusDraftFailed,
		DocumentStatusPending,
		DocumentStatusPendingFailed,
		DocumentStatusActive,
		DocumentStatusArchived,
		DocumentStatusDeduped,
		DocumentStatusTimeout,
	}
}

type TgChannel struct {
	ID         int64           `json:"id"`
	Name       string          `json:"name"`
	Title      string          `json:"title"`
	Broadcast  bool            `json:"broadcast"`
	Source     string          `json:"source"`
	Catalog    DocumentCatalog `json:"catalog"`
	ExtractCfg []byte          `json:"extract_cfg"`
	Enabled    bool            `json:"enabled"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}
