// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package tg_channel

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const countList = `-- name: CountList :one
SELECT COUNT(*) 
FROM public.tg_channel
WHERE 
    ($1::bigint IS NULL OR id = $1::bigint)
    AND ($2::varchar IS NULL OR name LIKE '%' || $2::varchar || '%')
    AND ($3::varchar IS NULL OR source = $3::varchar)
    AND ($4::document_catalog IS NULL OR catalog = $4::document_catalog)
    AND ($5::boolean IS NULL OR enabled = $5::boolean)
`

type CountListParams struct {
	ID      *int64
	Name    *string
	Source  *string
	Catalog NullDocumentCatalog
	Enabled *bool
}

// -- timeout: 2s
func (q *Queries) CountList(ctx context.Context, arg CountListParams) (*int64, error) {
	return _CountList(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) CountList(ctx context.Context, arg CountListParams) (*int64, error) {
	return _CountList(ctx, q, arg)
}

func _CountList(ctx context.Context, q CacheQuerierConn, arg CountListParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("tg_channel.CountList")
	row := q.GetConn().WQueryRow(qctx, "tg_channel.CountList", countList,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Catalog,
		arg.Enabled)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const create = `-- name: Create :one
INSERT INTO public.tg_channel (
    id,
    name,
    title,
    broadcast,
    source,
    catalog,
    extract_cfg,
    enabled,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    now(),
    now()
)
RETURNING id, name, title, broadcast, source, catalog, extract_cfg, enabled, created_at, updated_at
`

type CreateParams struct {
	ID         int64
	Name       string
	Title      string
	Broadcast  bool
	Source     string
	Catalog    DocumentCatalog
	ExtractCfg []byte
	Enabled    bool
}

// -- timeout: 2s
// -- invalidate : [GetById]
func (q *Queries) Create(ctx context.Context, arg CreateParams, getById *int64) (*TgChannel, error) {
	return _Create(ctx, q, arg, getById)
}

func _Create(ctx context.Context, q CacheWGConn, arg CreateParams, getById *int64) (*TgChannel, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "tg_channel.Create", create,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.Broadcast,
		arg.Source,
		arg.Catalog,
		arg.ExtractCfg,
		arg.Enabled)
	var i *TgChannel = new(TgChannel)
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Broadcast,
		&i.Source,
		&i.Catalog,
		&i.ExtractCfg,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*TgChannel)(nil), nil
	} else if err != nil {
		return nil, err
	}

	// invalidate
	_ = q.GetConn().PostExec(func() error {
		anyErr := make(chan error, 1)
		var wg sync.WaitGroup
		wg.Add(1)
		go func() {
			defer wg.Done()
			if getById != nil {
				key := "tg_channel:GetById:" + hashIfLong(fmt.Sprintf("%+v", (*getById)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		wg.Wait()
		close(anyErr)
		return <-anyErr
	})
	return i, err
}

const getById = `-- name: GetById :one
SELECT id, name, title, broadcast, source, catalog, extract_cfg, enabled, created_at, updated_at 
FROM public.tg_channel
WHERE id = $1
`

// -- timeout: 1s
// -- cache: 60s
func (q *Queries) GetById(ctx context.Context, id int64) (*TgChannel, error) {
	return _GetById(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetById(ctx context.Context, id int64) (*TgChannel, error) {
	return _GetById(ctx, q, id)
}

func _GetById(ctx context.Context, q CacheQuerierConn, id int64) (*TgChannel, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("tg_channel.GetById")
	dbRead := func() (any, time.Duration, error) {
		cacheDuration := time.Duration(time.Millisecond * 60000)
		row := q.GetConn().WQueryRow(qctx, "tg_channel.GetById", getById, id)
		var i *TgChannel = new(TgChannel)
		err := row.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Broadcast,
			&i.Source,
			&i.Catalog,
			&i.ExtractCfg,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if err == pgx.ErrNoRows {
			return (*TgChannel)(nil), cacheDuration, nil
		}
		return i, cacheDuration, err
	}
	if q.GetCache() == nil {
		i, _, err := dbRead()
		return i.(*TgChannel), err
	}

	var i *TgChannel
	err := q.GetCache().GetWithTtl(qctx, "tg_channel:GetById:"+hashIfLong(fmt.Sprintf("%+v", id)), &i, dbRead, false, false)
	if err != nil {
		return nil, err
	}

	return i, err
}

const queryList = `-- name: QueryList :many
SELECT id, name, title, broadcast, source, catalog, extract_cfg, enabled, created_at, updated_at 
FROM public.tg_channel
WHERE 
    ($1::bigint IS NULL OR id = $1::bigint)
    AND ($2::varchar IS NULL OR name LIKE '%' || $2::varchar || '%')
    AND ($3::varchar IS NULL OR source = $3::varchar)
    AND ($4::document_catalog IS NULL OR catalog = $4::document_catalog)
    AND ($5::boolean IS NULL OR enabled = $5::boolean)
ORDER BY created_at DESC
LIMIT $7
OFFSET $6
`

type QueryListParams struct {
	ID      *int64
	Name    *string
	Source  *string
	Catalog NullDocumentCatalog
	Enabled *bool
	Offset  int32
	Limit   int32
}

// -- timeout: 2s
func (q *Queries) QueryList(ctx context.Context, arg QueryListParams) ([]TgChannel, error) {
	return _QueryList(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) QueryList(ctx context.Context, arg QueryListParams) ([]TgChannel, error) {
	return _QueryList(ctx, q, arg)
}

func _QueryList(ctx context.Context, q CacheQuerierConn, arg QueryListParams) ([]TgChannel, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("tg_channel.QueryList")
	rows, err := q.GetConn().WQuery(qctx, "tg_channel.QueryList", queryList,
		arg.ID,
		arg.Name,
		arg.Source,
		arg.Catalog,
		arg.Enabled,
		arg.Offset,
		arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TgChannel
	for rows.Next() {
		var i *TgChannel = new(TgChannel)
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Broadcast,
			&i.Source,
			&i.Catalog,
			&i.ExtractCfg,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const update = `-- name: Update :one
UPDATE public.tg_channel
SET 
    name = coalesce($1, name),
    title = coalesce($2, title),
    broadcast = coalesce($3, broadcast),
    source = coalesce($4, source),
    catalog = coalesce($5, catalog),
    extract_cfg = coalesce($6, extract_cfg),
    enabled = coalesce($7, enabled),
    updated_at = now()
WHERE id = $8
RETURNING id, name, title, broadcast, source, catalog, extract_cfg, enabled, created_at, updated_at
`

type UpdateParams struct {
	Name       *string
	Title      *string
	Broadcast  *bool
	Source     *string
	Catalog    NullDocumentCatalog
	ExtractCfg []byte
	Enabled    *bool
	ID         int64
}

// -- timeout: 2s
// -- invalidate : [GetById]
func (q *Queries) Update(ctx context.Context, arg UpdateParams, getById *int64) (*TgChannel, error) {
	return _Update(ctx, q, arg, getById)
}

func _Update(ctx context.Context, q CacheWGConn, arg UpdateParams, getById *int64) (*TgChannel, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "tg_channel.Update", update,
		arg.Name,
		arg.Title,
		arg.Broadcast,
		arg.Source,
		arg.Catalog,
		arg.ExtractCfg,
		arg.Enabled,
		arg.ID)
	var i *TgChannel = new(TgChannel)
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.Broadcast,
		&i.Source,
		&i.Catalog,
		&i.ExtractCfg,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*TgChannel)(nil), nil
	} else if err != nil {
		return nil, err
	}

	// invalidate
	_ = q.GetConn().PostExec(func() error {
		anyErr := make(chan error, 1)
		var wg sync.WaitGroup
		wg.Add(1)
		go func() {
			defer wg.Done()
			if getById != nil {
				key := "tg_channel:GetById:" + hashIfLong(fmt.Sprintf("%+v", (*getById)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		wg.Wait()
		close(anyErr)
		return <-anyErr
	})
	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,name,title,broadcast,source,catalog,extract_cfg,enabled,created_at,updated_at FROM \"tg_channel\" ORDER BY id,name,title,broadcast,source,enabled,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "tg_channel.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TgChannel
	for rows.Next() {
		var v TgChannel
		if err := rows.Scan(&v.ID, &v.Name, &v.Title, &v.Broadcast, &v.Source, &v.Catalog, &v.ExtractCfg, &v.Enabled, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"tg_channel\" (id,name,title,broadcast,source,catalog,extract_cfg,enabled,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10);"
	rows := make([]TgChannel, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "tg_channel.Load", sql, row.ID, row.Name, row.Title, row.Broadcast, row.Source, row.Catalog, row.ExtractCfg, row.Enabled, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
