// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package assets

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const getAsset = `-- name: GetAsset :one
SELECT account_id, exchange, asset, wallet_type, total, frozen, order_occupied, avg_price, last_updated_ts, created_at, updated_at FROM assets
WHERE account_id = $1 AND asset = $2 AND wallet_type = $3
`

type GetAssetParams struct {
	AccountID  string
	Asset      string
	WalletType WalletType
}

// -- timeout: 1s
func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (*Asset, error) {
	return _GetAsset(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetAsset(ctx context.Context, arg GetAssetParams) (*Asset, error) {
	return _GetAsset(ctx, q, arg)
}

func _GetAsset(ctx context.Context, q CacheQuerierConn, arg GetAssetParams) (*Asset, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("assets.GetAsset")
	row := q.GetConn().WQueryRow(qctx, "assets.GetAsset", getAsset, arg.AccountID, arg.Asset, arg.WalletType)
	var i *Asset = new(Asset)
	err := row.Scan(
		&i.AccountID,
		&i.Exchange,
		&i.Asset,
		&i.WalletType,
		&i.Total,
		&i.Frozen,
		&i.OrderOccupied,
		&i.AvgPrice,
		&i.LastUpdatedTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Asset)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getAssetWithLock = `-- name: GetAssetWithLock :one
SELECT account_id, exchange, asset, wallet_type, total, frozen, order_occupied, avg_price, last_updated_ts, created_at, updated_at FROM assets
WHERE account_id = $1 AND asset = $2 AND wallet_type = $3
FOR UPDATE
`

type GetAssetWithLockParams struct {
	AccountID  string
	Asset      string
	WalletType WalletType
}

// -- timeout: 1s
func (q *Queries) GetAssetWithLock(ctx context.Context, arg GetAssetWithLockParams) (*Asset, error) {
	return _GetAssetWithLock(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetAssetWithLock(ctx context.Context, arg GetAssetWithLockParams) (*Asset, error) {
	return _GetAssetWithLock(ctx, q, arg)
}

func _GetAssetWithLock(ctx context.Context, q CacheQuerierConn, arg GetAssetWithLockParams) (*Asset, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("assets.GetAssetWithLock")
	row := q.GetConn().WQueryRow(qctx, "assets.GetAssetWithLock", getAssetWithLock, arg.AccountID, arg.Asset, arg.WalletType)
	var i *Asset = new(Asset)
	err := row.Scan(
		&i.AccountID,
		&i.Exchange,
		&i.Asset,
		&i.WalletType,
		&i.Total,
		&i.Frozen,
		&i.OrderOccupied,
		&i.AvgPrice,
		&i.LastUpdatedTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Asset)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const incrementAsset = `-- name: IncrementAsset :one
UPDATE assets SET 
    total = total + COALESCE($1::numeric, 0), 
    frozen = frozen + COALESCE($2::numeric, 0), 
    order_occupied = order_occupied + COALESCE($3::numeric, 0), 
    updated_at = CURRENT_TIMESTAMP 
WHERE account_id = $4::varchar
AND asset = $5::varchar
AND wallet_type = $6::wallet_type
AND last_updated_ts < $7::timestamptz
RETURNING account_id, exchange, asset, wallet_type, total, frozen, order_occupied, avg_price, last_updated_ts, created_at, updated_at
`

type IncrementAssetParams struct {
	Total         pgtype.Numeric
	Frozen        pgtype.Numeric
	OrderOccupied pgtype.Numeric
	AccountID     string
	Asset         string
	WalletType    WalletType
	LastUpdatedTs time.Time
}

// -- timeout: 1s
func (q *Queries) IncrementAsset(ctx context.Context, arg IncrementAssetParams) (*Asset, error) {
	return _IncrementAsset(ctx, q.AsReadOnly(), arg)
}

func _IncrementAsset(ctx context.Context, q CacheQuerierConn, arg IncrementAssetParams) (*Asset, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "assets.IncrementAsset", incrementAsset,
		arg.Total,
		arg.Frozen,
		arg.OrderOccupied,
		arg.AccountID,
		arg.Asset,
		arg.WalletType,
		arg.LastUpdatedTs)
	var i *Asset = new(Asset)
	err := row.Scan(
		&i.AccountID,
		&i.Exchange,
		&i.Asset,
		&i.WalletType,
		&i.Total,
		&i.Frozen,
		&i.OrderOccupied,
		&i.AvgPrice,
		&i.LastUpdatedTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Asset)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const incrementOrderOccupied = `-- name: IncrementOrderOccupied :one
UPDATE assets SET 
    order_occupied = order_occupied + COALESCE($1::numeric, 0), 
    updated_at = CURRENT_TIMESTAMP 
WHERE account_id = $2::varchar
AND asset = $3::varchar
AND wallet_type = $4::wallet_type
RETURNING account_id, exchange, asset, wallet_type, total, frozen, order_occupied, avg_price, last_updated_ts, created_at, updated_at
`

type IncrementOrderOccupiedParams struct {
	OrderOccupied pgtype.Numeric
	AccountID     string
	Asset         string
	WalletType    WalletType
}

// -- timeout: 1s
func (q *Queries) IncrementOrderOccupied(ctx context.Context, arg IncrementOrderOccupiedParams) (*Asset, error) {
	return _IncrementOrderOccupied(ctx, q.AsReadOnly(), arg)
}

func _IncrementOrderOccupied(ctx context.Context, q CacheQuerierConn, arg IncrementOrderOccupiedParams) (*Asset, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "assets.IncrementOrderOccupied", incrementOrderOccupied,
		arg.OrderOccupied,
		arg.AccountID,
		arg.Asset,
		arg.WalletType)
	var i *Asset = new(Asset)
	err := row.Scan(
		&i.AccountID,
		&i.Exchange,
		&i.Asset,
		&i.WalletType,
		&i.Total,
		&i.Frozen,
		&i.OrderOccupied,
		&i.AvgPrice,
		&i.LastUpdatedTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Asset)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const listAssetsByAccount = `-- name: ListAssetsByAccount :many
SELECT account_id, exchange, asset, wallet_type, total, frozen, order_occupied, avg_price, last_updated_ts, created_at, updated_at FROM assets
WHERE account_id = $1
ORDER BY asset, wallet_type
`

// -- timeout: 1s
func (q *Queries) ListAssetsByAccount(ctx context.Context, accountID string) ([]Asset, error) {
	return _ListAssetsByAccount(ctx, q.AsReadOnly(), accountID)
}

func (q *ReadOnlyQueries) ListAssetsByAccount(ctx context.Context, accountID string) ([]Asset, error) {
	return _ListAssetsByAccount(ctx, q, accountID)
}

func _ListAssetsByAccount(ctx context.Context, q CacheQuerierConn, accountID string) ([]Asset, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("assets.ListAssetsByAccount")
	rows, err := q.GetConn().WQuery(qctx, "assets.ListAssetsByAccount", listAssetsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i *Asset = new(Asset)
		if err := rows.Scan(
			&i.AccountID,
			&i.Exchange,
			&i.Asset,
			&i.WalletType,
			&i.Total,
			&i.Frozen,
			&i.OrderOccupied,
			&i.AvgPrice,
			&i.LastUpdatedTs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const resetOrderOccupiedByPendingOrders = `-- name: ResetOrderOccupiedByPendingOrders :many
WITH locked_sums AS (
    SELECT
        o.account_id,
        UPPER(TRIM(o.locked_asset)) AS asset,
        CASE
            WHEN o.exchange IN ('okx', 'okx_test') THEN 'trade'::wallet_type
            WHEN split_part(o.symbol, ':', 2) = 'FUTURE' THEN 'future'::wallet_type
            WHEN split_part(o.symbol, ':', 2) = 'SPOT' THEN 'spot'::wallet_type
            ELSE 'fund'::wallet_type
        END AS wallet_type,
        SUM(COALESCE(o.locked, 0)) AS order_occupied
    FROM orders o
    WHERE o.account_id = $1
      AND o.status IN ('NEW', 'PENDING', 'WORKING', 'PARTIAL_DONE')
      AND o.locked_asset IS NOT NULL
      AND TRIM(o.locked_asset) <> ''
    GROUP BY o.account_id, UPPER(TRIM(o.locked_asset)), wallet_type
),
all_assets AS (
    SELECT
        a.account_id,
        a.asset,
        a.wallet_type,
        COALESCE(s.order_occupied, 0) AS order_occupied
    FROM assets a
    LEFT JOIN locked_sums s
      ON s.account_id = a.account_id
     AND s.asset = a.asset
     AND s.wallet_type = a.wallet_type
    WHERE a.account_id = $1
)
UPDATE assets a
SET order_occupied = aa.order_occupied,
    updated_at = CURRENT_TIMESTAMP
FROM all_assets aa
WHERE a.account_id = aa.account_id
  AND a.asset = aa.asset
  AND a.wallet_type = aa.wallet_type
  AND (a.order_occupied IS DISTINCT FROM aa.order_occupied)
RETURNING a.account_id, a.exchange, a.asset, a.wallet_type, a.total, a.frozen, a.order_occupied, a.avg_price, a.last_updated_ts, a.created_at, a.updated_at
`

// -- timeout: 5s
// 从当前“在途订单”汇总 locked，重置账户维度的 order_occupied。
// 说明：
// - 订单侧 locked_asset 作为资产币种；wallet_type 由 (exchange, symbol.marketType) 推导
// - 未出现在在途订单汇总中的资产，将被重置为 0
func (q *Queries) ResetOrderOccupiedByPendingOrders(ctx context.Context, accountID string) ([]Asset, error) {
	return _ResetOrderOccupiedByPendingOrders(ctx, q.AsReadOnly(), accountID)
}

func _ResetOrderOccupiedByPendingOrders(ctx context.Context, q CacheQuerierConn, accountID string) ([]Asset, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	rows, err := q.GetConn().WQuery(qctx, "assets.ResetOrderOccupiedByPendingOrders", resetOrderOccupiedByPendingOrders, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i *Asset = new(Asset)
		if err := rows.Scan(
			&i.AccountID,
			&i.Exchange,
			&i.Asset,
			&i.WalletType,
			&i.Total,
			&i.Frozen,
			&i.OrderOccupied,
			&i.AvgPrice,
			&i.LastUpdatedTs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const setAssetAvgPrice = `-- name: SetAssetAvgPrice :one
UPDATE assets SET
  avg_price = $1::numeric,
  updated_at = CURRENT_TIMESTAMP
WHERE account_id = $2::varchar
  AND asset = $3::varchar
  AND wallet_type = $4::wallet_type
RETURNING account_id, exchange, asset, wallet_type, total, frozen, order_occupied, avg_price, last_updated_ts, created_at, updated_at
`

type SetAssetAvgPriceParams struct {
	AvgPrice   pgtype.Numeric
	AccountID  string
	Asset      string
	WalletType WalletType
}

// -- timeout: 1s
// 直接设置 avg_price（用于定时补全）
func (q *Queries) SetAssetAvgPrice(ctx context.Context, arg SetAssetAvgPriceParams) (*Asset, error) {
	return _SetAssetAvgPrice(ctx, q.AsReadOnly(), arg)
}

func _SetAssetAvgPrice(ctx context.Context, q CacheQuerierConn, arg SetAssetAvgPriceParams) (*Asset, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "assets.SetAssetAvgPrice", setAssetAvgPrice,
		arg.AvgPrice,
		arg.AccountID,
		arg.Asset,
		arg.WalletType)
	var i *Asset = new(Asset)
	err := row.Scan(
		&i.AccountID,
		&i.Exchange,
		&i.Asset,
		&i.WalletType,
		&i.Total,
		&i.Frozen,
		&i.OrderOccupied,
		&i.AvgPrice,
		&i.LastUpdatedTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Asset)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateAssetAvgPriceOnIncrease = `-- name: UpdateAssetAvgPriceOnIncrease :one
UPDATE assets SET
  avg_price = (
    (total - $1::numeric) * COALESCE(NULLIF(avg_price, 0), 0)
    + $1::numeric * $2::numeric
  ) / NULLIF(total, 0),
  updated_at = CURRENT_TIMESTAMP
WHERE account_id = $3::varchar
  AND asset = $4::varchar
  AND wallet_type = $5::wallet_type
  AND total >= $1::numeric
  AND total > 0
RETURNING account_id, exchange, asset, wallet_type, total, frozen, order_occupied, avg_price, last_updated_ts, created_at, updated_at
`

type UpdateAssetAvgPriceOnIncreaseParams struct {
	TotalDelta pgtype.Numeric
	PriceUsdt  pgtype.Numeric
	AccountID  string
	Asset      string
	WalletType WalletType
}

// -- timeout: 1s
// 资产变多时按 WAC 更新 avg_price
// total_delta: 本次增加的数量（正数）
// price_usdt: 当前 asset/USDT 价格
func (q *Queries) UpdateAssetAvgPriceOnIncrease(ctx context.Context, arg UpdateAssetAvgPriceOnIncreaseParams) (*Asset, error) {
	return _UpdateAssetAvgPriceOnIncrease(ctx, q.AsReadOnly(), arg)
}

func _UpdateAssetAvgPriceOnIncrease(ctx context.Context, q CacheQuerierConn, arg UpdateAssetAvgPriceOnIncreaseParams) (*Asset, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "assets.UpdateAssetAvgPriceOnIncrease", updateAssetAvgPriceOnIncrease,
		arg.TotalDelta,
		arg.PriceUsdt,
		arg.AccountID,
		arg.Asset,
		arg.WalletType)
	var i *Asset = new(Asset)
	err := row.Scan(
		&i.AccountID,
		&i.Exchange,
		&i.Asset,
		&i.WalletType,
		&i.Total,
		&i.Frozen,
		&i.OrderOccupied,
		&i.AvgPrice,
		&i.LastUpdatedTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Asset)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const upsertAsset = `-- name: UpsertAsset :one
WITH prev AS (
    SELECT 
        a.account_id, a.exchange, a.asset, a.wallet_type, a.total, a.frozen, a.order_occupied, a.avg_price, a.last_updated_ts, a.created_at, a.updated_at,
        a.total  AS prev_total,
        a.frozen AS prev_frozen,
        a.order_occupied AS prev_order_occupied
    FROM assets a
    WHERE a.account_id = $1::varchar
    AND a.asset = $2::varchar
    AND a.wallet_type = $3::wallet_type
    FOR UPDATE
),
upsert AS (
    INSERT INTO assets (account_id, exchange, asset, wallet_type, total, frozen, order_occupied, avg_price, last_updated_ts)
    VALUES (
        $1::varchar, 
        $4::varchar, 
        $2::varchar, 
        $3::wallet_type, 
        COALESCE($5::numeric, 0),   -- insert: NULL → 0
        COALESCE($6::numeric, 0),   -- insert: NULL → 0
        COALESCE($7::numeric, 0),   -- insert: NULL → 0
        COALESCE($8::numeric, 0),   -- insert: NULL → 0
        $9::timestamptz)
    ON CONFLICT (account_id, asset, wallet_type)
    DO UPDATE SET 
        total = COALESCE($5::numeric, assets.total),     -- update: NULL → 原值
        frozen = COALESCE($6::numeric, assets.frozen),  -- update: NULL → 原值
        order_occupied = COALESCE($7::numeric, assets.order_occupied),  -- update: NULL → 原值
        avg_price = COALESCE($8::numeric, assets.avg_price),  -- update: NULL → 原值
        last_updated_ts = EXCLUDED.last_updated_ts,
        updated_at = CURRENT_TIMESTAMP
    WHERE assets.last_updated_ts <= EXCLUDED.last_updated_ts
    RETURNING assets.account_id, assets.exchange, assets.asset, assets.wallet_type, assets.total, assets.frozen, assets.order_occupied, assets.avg_price, assets.last_updated_ts, assets.created_at, assets.updated_at
)
SELECT
    COALESCE(u.account_id, p.account_id)       AS account_id,
    COALESCE(u.exchange,   p.exchange)         AS exchange,
    COALESCE(u.asset,      p.asset)            AS asset,
    COALESCE(u.wallet_type,p.wallet_type)      AS wallet_type,
    COALESCE(u.total,      p.total)            AS total,
    COALESCE(u.frozen,     p.frozen)           AS frozen,
    COALESCE(u.order_occupied, p.order_occupied) AS order_occupied,
    COALESCE(u.avg_price, p.avg_price) AS avg_price,
    COALESCE(u.last_updated_ts, p.last_updated_ts) AS last_updated_ts,
    COALESCE(u.created_at, p.created_at)       AS created_at,
    COALESCE(u.updated_at, p.updated_at)       AS updated_at,
    COALESCE(p.prev_total, 0) AS prev_total,
    COALESCE(p.prev_frozen, 0) AS prev_frozen,
    COALESCE(p.prev_order_occupied, 0) AS prev_order_occupied
FROM prev p
FULL JOIN upsert u ON true
`

type UpsertAssetParams struct {
	AccountID     string
	Asset         string
	WalletType    WalletType
	Exchange      string
	Total         pgtype.Numeric
	Frozen        pgtype.Numeric
	OrderOccupied pgtype.Numeric
	AvgPrice      pgtype.Numeric
	LastUpdatedTs time.Time
}

type UpsertAssetRow struct {
	AccountID         string
	Exchange          string
	Asset             string
	WalletType        WalletType
	Total             pgtype.Numeric
	Frozen            pgtype.Numeric
	OrderOccupied     pgtype.Numeric
	AvgPrice          pgtype.Numeric
	LastUpdatedTs     time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	PrevTotal         pgtype.Numeric
	PrevFrozen        pgtype.Numeric
	PrevOrderOccupied pgtype.Numeric
}

// -- timeout: 1s
func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (*UpsertAssetRow, error) {
	return _UpsertAsset(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (*UpsertAssetRow, error) {
	return _UpsertAsset(ctx, q, arg)
}

func _UpsertAsset(ctx context.Context, q CacheQuerierConn, arg UpsertAssetParams) (*UpsertAssetRow, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("assets.UpsertAsset")
	row := q.GetConn().WQueryRow(qctx, "assets.UpsertAsset", upsertAsset,
		arg.AccountID,
		arg.Asset,
		arg.WalletType,
		arg.Exchange,
		arg.Total,
		arg.Frozen,
		arg.OrderOccupied,
		arg.AvgPrice,
		arg.LastUpdatedTs)
	var i *UpsertAssetRow = new(UpsertAssetRow)
	err := row.Scan(
		&i.AccountID,
		&i.Exchange,
		&i.Asset,
		&i.WalletType,
		&i.Total,
		&i.Frozen,
		&i.OrderOccupied,
		&i.AvgPrice,
		&i.LastUpdatedTs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrevTotal,
		&i.PrevFrozen,
		&i.PrevOrderOccupied,
	)
	if err == pgx.ErrNoRows {
		return (*UpsertAssetRow)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT account_id,exchange,asset,wallet_type,total,frozen,order_occupied,avg_price,last_updated_ts,created_at,updated_at FROM \"assets\" ORDER BY account_id,exchange,asset,last_updated_ts,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "assets.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var v Asset
		if err := rows.Scan(&v.AccountID, &v.Exchange, &v.Asset, &v.WalletType, &v.Total, &v.Frozen, &v.OrderOccupied, &v.AvgPrice, &v.LastUpdatedTs, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"assets\" (account_id,exchange,asset,wallet_type,total,frozen,order_occupied,avg_price,last_updated_ts,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11);"
	rows := make([]Asset, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "assets.Load", sql, row.AccountID, row.Exchange, row.Asset, row.WalletType, row.Total, row.Frozen, row.OrderOccupied, row.AvgPrice, row.LastUpdatedTs, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
