// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package acct_snapshot

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const getAccountAssetSnapshotAtOrBefore = `-- name: GetAccountAssetSnapshotAtOrBefore :one
SELECT id, account_id, exchange, wallet_type, asset, total, frozen, order_occupied, effective_ts, created_at
FROM account_asset_snapshot
WHERE account_id = $1
  AND exchange = $2
  AND asset = $3
  AND wallet_type = $4
  AND effective_ts <= $5
ORDER BY effective_ts DESC, id DESC
LIMIT 1
`

type GetAccountAssetSnapshotAtOrBeforeParams struct {
	AccountID   string
	Exchange    string
	Asset       string
	WalletType  WalletType
	EffectiveTs time.Time
}

type GetAccountAssetSnapshotAtOrBeforeRow struct {
	ID            int64
	AccountID     string
	Exchange      string
	WalletType    WalletType
	Asset         string
	Total         pgtype.Numeric
	Frozen        pgtype.Numeric
	OrderOccupied pgtype.Numeric
	EffectiveTs   time.Time
	CreatedAt     time.Time
}

// -- timeout: 2s
func (q *Queries) GetAccountAssetSnapshotAtOrBefore(ctx context.Context, arg GetAccountAssetSnapshotAtOrBeforeParams) (*GetAccountAssetSnapshotAtOrBeforeRow, error) {
	return _GetAccountAssetSnapshotAtOrBefore(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetAccountAssetSnapshotAtOrBefore(ctx context.Context, arg GetAccountAssetSnapshotAtOrBeforeParams) (*GetAccountAssetSnapshotAtOrBeforeRow, error) {
	return _GetAccountAssetSnapshotAtOrBefore(ctx, q, arg)
}

func _GetAccountAssetSnapshotAtOrBefore(ctx context.Context, q CacheQuerierConn, arg GetAccountAssetSnapshotAtOrBeforeParams) (*GetAccountAssetSnapshotAtOrBeforeRow, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("acct_snapshot.GetAccountAssetSnapshotAtOrBefore")
	row := q.GetConn().WQueryRow(qctx, "acct_snapshot.GetAccountAssetSnapshotAtOrBefore", getAccountAssetSnapshotAtOrBefore,
		arg.AccountID,
		arg.Exchange,
		arg.Asset,
		arg.WalletType,
		arg.EffectiveTs)
	var i *GetAccountAssetSnapshotAtOrBeforeRow = new(GetAccountAssetSnapshotAtOrBeforeRow)
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Exchange,
		&i.WalletType,
		&i.Asset,
		&i.Total,
		&i.Frozen,
		&i.OrderOccupied,
		&i.EffectiveTs,
		&i.CreatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*GetAccountAssetSnapshotAtOrBeforeRow)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getAccountPositionSnapshotAtOrBefore = `-- name: GetAccountPositionSnapshotAtOrBefore :one
SELECT id, account_id, exchange, symbol, side, qty, entry_price, leverage, effective_ts, created_at
FROM account_position_snapshot
WHERE account_id = $1
  AND exchange = $2
  AND symbol = $3
  AND side = $4
  AND effective_ts <= $5
ORDER BY effective_ts DESC, id DESC
LIMIT 1
`

type GetAccountPositionSnapshotAtOrBeforeParams struct {
	AccountID   string
	Exchange    string
	Symbol      string
	Side        PositionSide
	EffectiveTs time.Time
}

type GetAccountPositionSnapshotAtOrBeforeRow struct {
	ID          int64
	AccountID   string
	Exchange    string
	Symbol      string
	Side        PositionSide
	Qty         pgtype.Numeric
	EntryPrice  pgtype.Numeric
	Leverage    int32
	EffectiveTs time.Time
	CreatedAt   time.Time
}

// -- timeout: 2s
func (q *Queries) GetAccountPositionSnapshotAtOrBefore(ctx context.Context, arg GetAccountPositionSnapshotAtOrBeforeParams) (*GetAccountPositionSnapshotAtOrBeforeRow, error) {
	return _GetAccountPositionSnapshotAtOrBefore(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetAccountPositionSnapshotAtOrBefore(ctx context.Context, arg GetAccountPositionSnapshotAtOrBeforeParams) (*GetAccountPositionSnapshotAtOrBeforeRow, error) {
	return _GetAccountPositionSnapshotAtOrBefore(ctx, q, arg)
}

func _GetAccountPositionSnapshotAtOrBefore(ctx context.Context, q CacheQuerierConn, arg GetAccountPositionSnapshotAtOrBeforeParams) (*GetAccountPositionSnapshotAtOrBeforeRow, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	q.GetConn().CountIntent("acct_snapshot.GetAccountPositionSnapshotAtOrBefore")
	row := q.GetConn().WQueryRow(qctx, "acct_snapshot.GetAccountPositionSnapshotAtOrBefore", getAccountPositionSnapshotAtOrBefore,
		arg.AccountID,
		arg.Exchange,
		arg.Symbol,
		arg.Side,
		arg.EffectiveTs)
	var i *GetAccountPositionSnapshotAtOrBeforeRow = new(GetAccountPositionSnapshotAtOrBeforeRow)
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Exchange,
		&i.Symbol,
		&i.Side,
		&i.Qty,
		&i.EntryPrice,
		&i.Leverage,
		&i.EffectiveTs,
		&i.CreatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*GetAccountPositionSnapshotAtOrBeforeRow)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const insertAccountAssetSnapshot = `-- name: InsertAccountAssetSnapshot :exec
INSERT INTO account_asset_snapshot (account_id, exchange, wallet_type, asset, total, frozen, order_occupied, effective_ts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAccountAssetSnapshotParams struct {
	AccountID     string
	Exchange      string
	WalletType    WalletType
	Asset         string
	Total         pgtype.Numeric
	Frozen        pgtype.Numeric
	OrderOccupied pgtype.Numeric
	EffectiveTs   time.Time
}

// -- timeout: 2s
func (q *Queries) InsertAccountAssetSnapshot(ctx context.Context, arg InsertAccountAssetSnapshotParams) error {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	_, err := q.db.WExec(qctx, "acct_snapshot.InsertAccountAssetSnapshot", insertAccountAssetSnapshot,
		arg.AccountID,
		arg.Exchange,
		arg.WalletType,
		arg.Asset,
		arg.Total,
		arg.Frozen,
		arg.OrderOccupied,
		arg.EffectiveTs)
	if err != nil {
		return err
	}

	return nil
}

const insertAccountPositionSnapshot = `-- name: InsertAccountPositionSnapshot :exec
INSERT INTO account_position_snapshot (account_id, exchange, symbol, side, qty, entry_price, leverage, effective_ts)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAccountPositionSnapshotParams struct {
	AccountID   string
	Exchange    string
	Symbol      string
	Side        PositionSide
	Qty         pgtype.Numeric
	EntryPrice  pgtype.Numeric
	Leverage    int32
	EffectiveTs time.Time
}

// -- timeout: 2s
func (q *Queries) InsertAccountPositionSnapshot(ctx context.Context, arg InsertAccountPositionSnapshotParams) error {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*2000)
	defer cancel()
	_, err := q.db.WExec(qctx, "acct_snapshot.InsertAccountPositionSnapshot", insertAccountPositionSnapshot,
		arg.AccountID,
		arg.Exchange,
		arg.Symbol,
		arg.Side,
		arg.Qty,
		arg.EntryPrice,
		arg.Leverage,
		arg.EffectiveTs)
	if err != nil {
		return err
	}

	return nil
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT account_id,exchange,asset,wallet_type,total,frozen,order_occupied,avg_price,last_updated_ts,created_at,updated_at FROM \"assets\" ORDER BY account_id,exchange,asset,last_updated_ts,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "acct_snapshot.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var v Asset
		if err := rows.Scan(&v.AccountID, &v.Exchange, &v.Asset, &v.WalletType, &v.Total, &v.Frozen, &v.OrderOccupied, &v.AvgPrice, &v.LastUpdatedTs, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"assets\" (account_id,exchange,asset,wallet_type,total,frozen,order_occupied,avg_price,last_updated_ts,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11);"
	rows := make([]Asset, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "acct_snapshot.Load", sql, row.AccountID, row.Exchange, row.Asset, row.WalletType, row.Total, row.Frozen, row.OrderOccupied, row.AvgPrice, row.LastUpdatedTs, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
