// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package ds_items

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/rs/zerolog/log"
)

const batchInsert = `-- name: BatchInsert :execrows
INSERT INTO ds_items (ds_id, data, ts)
VALUES (UNNEST($1::int[]), UNNEST($2::jsonb[]), UNNEST($3::timestamptz[]))
`

type BatchInsertParams struct {
	DsID []int32
	Data [][]byte
	Ts   []time.Time
}

// -- timeout: 10s
func (q *Queries) BatchInsert(ctx context.Context, arg BatchInsertParams) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*10000)
	defer cancel()
	result, err := q.db.WExec(qctx, "ds_items.BatchInsert", batchInsert, arg.DsID, arg.Data, arg.Ts)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const getItemsByDsIdAndTs = `-- name: GetItemsByDsIdAndTs :many
SELECT id, ds_id, data, ts, created_at
FROM ds_items
WHERE ds_id = $1
  AND (
    ts > $2
    OR (ts = $2 AND id > $3)
  )
  AND ts <= $4
ORDER BY ts, id
LIMIT $5
`

type GetItemsByDsIdAndTsParams struct {
	DsID    int32
	StartTs time.Time
	StartID int64
	EndTs   time.Time
	Limit   int32
}

// -- timeout: 10s
func (q *Queries) GetItemsByDsIdAndTs(ctx context.Context, arg GetItemsByDsIdAndTsParams) ([]DsItem, error) {
	return _GetItemsByDsIdAndTs(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetItemsByDsIdAndTs(ctx context.Context, arg GetItemsByDsIdAndTsParams) ([]DsItem, error) {
	return _GetItemsByDsIdAndTs(ctx, q, arg)
}

func _GetItemsByDsIdAndTs(ctx context.Context, q CacheQuerierConn, arg GetItemsByDsIdAndTsParams) ([]DsItem, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*10000)
	defer cancel()
	q.GetConn().CountIntent("ds_items.GetItemsByDsIdAndTs")
	rows, err := q.GetConn().WQuery(qctx, "ds_items.GetItemsByDsIdAndTs", getItemsByDsIdAndTs,
		arg.DsID,
		arg.StartTs,
		arg.StartID,
		arg.EndTs,
		arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DsItem
	for rows.Next() {
		var i *DsItem = new(DsItem)
		if err := rows.Scan(
			&i.ID,
			&i.DsID,
			&i.Data,
			&i.Ts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,ds_id,data,ts,created_at FROM \"ds_items\" ORDER BY id,ds_id,ts,created_at ASC;"
	rows, err := q.db.WQuery(ctx, "ds_items.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DsItem
	for rows.Next() {
		var v DsItem
		if err := rows.Scan(&v.ID, &v.DsID, &v.Data, &v.Ts, &v.CreatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"ds_items\" (id,ds_id,data,ts,created_at) VALUES ($1,$2,$3,$4,$5);"
	rows := make([]DsItem, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "ds_items.Load", sql, row.ID, row.DsID, row.Data, row.Ts, row.CreatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
