package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strconv"
	"strings"
	"time"

	"github.com/samber/lo"
	"github.com/wangliang139/NovaForge/server/pkg/action"
	"github.com/wangliang139/NovaForge/server/pkg/action/converter"
	"github.com/wangliang139/NovaForge/server/pkg/action/model"
	"github.com/wangliang139/NovaForge/server/pkg/gateway/auth"
	stypes "github.com/wangliang139/NovaForge/server/pkg/strategy/types"
	ctypes "github.com/wangliang139/NovaForge/server/pkg/types"
	"github.com/wangliang139/NovaForge/server/pkg/utils/types"
	mowerror "github.com/wangliang139/mow/errors"
)

// Stats is the resolver for the stats field.
func (r *accountResolver) Stats(ctx context.Context, obj *model.Account) (*model.AccountStats, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if obj == nil || obj.ID == "" {
		return nil, nil
	}
	response, err := r.AccountSvc.GetBalance(ctx, &ctypes.GetBalanceRequest{
		AccountID:    obj.ID,
		WithNotional: lo.ToPtr(true),
	})
	if err != nil {
		return nil, err
	}
	if response == nil || response.Balance == nil {
		return &model.AccountStats{
			Notional:          "0",
			UnRealizedProfit:  "0",
			Notional24HChange: "0",
		}, nil
	}
	b := response.Balance
	return &model.AccountStats{
		Notional:          b.Notional.String(),
		UnRealizedProfit:  b.UnRealizedProfit.String(),
		Notional24HChange: b.Notional24HChange.String(),
	}, nil
}

// RiskIndex is the resolver for the riskIndex field.
func (r *accountResolver) RiskIndex(ctx context.Context, obj *model.Account) (*string, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if obj == nil || strings.TrimSpace(obj.ID) == "" {
		return nil, nil
	}

	req := &ctypes.GetRiskIndexRequest{
		AccountID: obj.ID,
	}
	resp, err := r.AccountSvc.GetRiskIndex(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp == nil || strings.TrimSpace(resp.RiskIndex) == "" {
		return nil, nil
	}
	return lo.ToPtr(resp.RiskIndex), nil
}

// CreateAccount is the resolver for the CreateAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.MutationAccountInput) (*model.Account, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	// 前端只能创建真实账户（不允许创建虚拟账户）
	if input.AccountType != nil && *input.AccountType != model.AccountTypeReal {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountType is invalid")
	}
	algo := ctypes.AuthAlgorithmHmac
	if input.Algorithm != nil {
		algo = ctypes.AuthAlgorithm(*input.Algorithm)
	}
	acc, err := r.AccountSvc.CreateAccount(ctx, ctypes.CreateAccountInput{
		Name:        input.Name,
		Exchange:    input.Exchange,
		ApiKey:      input.APIKey,
		ApiSecret:   input.APISecret,
		Passphrase:  input.Passphrase,
		Tags:        input.Tags,
		Status:      ctypes.AccountStatusOffline,
		Algorithm:   algo,
		AccountType: ctypes.AccountTypeReal,
	})
	if err != nil {
		return nil, err
	}
	return converter.AccountTypes2Gql(acc), nil
}

// UpdateAccount is the resolver for the UpdateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, input model.MutationAccountInput) (*model.Account, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if input.ID == nil || len(*input.ID) == 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "id is invalid")
	}
	if input.Status == nil || *input.Status == model.AccountStatusUnspecified {
		return nil, mowerror.New(mowerror.InvalidArgument, "status is invalid")
	}
	algo := ctypes.AuthAlgorithmHmac
	if input.Algorithm != nil {
		algo = ctypes.AuthAlgorithm(*input.Algorithm)
	}
	acctType := ctypes.AccountTypeReal
	if input.AccountType != nil {
		acctType = ctypes.AccountType(*input.AccountType)
	}
	response, err := r.AccountSvc.UpdateAccount(ctx, &ctypes.UpdateAccountRequest{
		ID:          *input.ID,
		Name:        input.Name,
		Exchange:    input.Exchange,
		ApiKey:      input.APIKey,
		ApiSecret:   input.APISecret,
		Passphrase:  input.Passphrase,
		Tags:        input.Tags,
		Status:      ctypes.AccountStatus(*input.Status),
		Algorithm:   algo,
		AccountType: acctType,
	})
	if err != nil {
		return nil, err
	}
	return converter.AccountTypes2Gql(response.Account), nil
}

// OnlineAccount is the resolver for the OnlineAccount field.
func (r *mutationResolver) OnlineAccount(ctx context.Context, id string) (*model.Account, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(id) == 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "id is required")
	}

	response, err := r.AccountSvc.OnlineAccount(ctx, &ctypes.OnlineAccountRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return converter.AccountTypes2Gql(response.Account), nil
}

// OfflineAccount is the resolver for the OfflineAccount field.
func (r *mutationResolver) OfflineAccount(ctx context.Context, id string) (*model.Account, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(id) == 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "id is required")
	}

	// 业务约束：如果账户被运行中的 bot 绑定，则不可下线
	botsResp, err := r.StrategySvc.ListBots(ctx, &stypes.ListBotsRequest{
		Limit:     1,
		Offset:    0,
		AccountID: &id,
		Status:    lo.ToPtr(stypes.BotStatusRunning),
	})
	if err != nil {
		return nil, err
	}
	if botsResp != nil && (botsResp.TotalCount > 0 || len(botsResp.Bots) > 0) {
		return nil, mowerror.New(mowerror.InvalidArgument, "账户已被运行中的 Bot 绑定，无法下线")
	}

	response, err := r.AccountSvc.OfflineAccount(ctx, &ctypes.OfflineAccountRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return converter.AccountTypes2Gql(response.Account), nil
}

// DeleteAccount is the resolver for the DeleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, id string) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(id) == 0 {
		return false, mowerror.New(mowerror.InvalidArgument, "id is required")
	}

	// 业务约束：如果账户被运行中的 bot 绑定，则不可下线
	botsResp, err := r.StrategySvc.ListBots(ctx, &stypes.ListBotsRequest{
		Limit:     1,
		Offset:    0,
		AccountID: &id,
	})
	if err != nil {
		return false, err
	}
	if botsResp != nil && (botsResp.TotalCount > 0 || len(botsResp.Bots) > 0) {
		return false, mowerror.New(mowerror.InvalidArgument, "账户已被 Bot 绑定，无法删除")
	}

	_, err = r.AccountSvc.DeleteAccount(ctx, &ctypes.DeleteAccountRequest{Id: id})
	if err != nil {
		return false, err
	}
	return true, nil
}

// RefreshAccountSnapshots is the resolver for the RefreshAccountSnapshots field.
func (r *mutationResolver) RefreshAccountSnapshots(ctx context.Context, accountID string) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(accountID) == 0 {
		return false, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	response, err := r.AccountSvc.RefreshAccountSnapshots(ctx, &ctypes.RefreshAccountSnapshotsRequest{
		AccountID: accountID,
	})
	if err != nil {
		return false, err
	}
	return response.Success, nil
}

// PlaceOrder is the resolver for the PlaceOrder field.
func (r *mutationResolver) PlaceOrder(ctx context.Context, input model.PlaceOrderInput) (*model.PlaceOrderResult, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	accountID := strings.TrimSpace(input.AccountID)
	if accountID == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}
	symbol := strings.TrimSpace(input.Symbol)
	if symbol == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}
	quantity := strings.TrimSpace(input.Quantity)
	if quantity == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "quantity is required")
	}

	side := ctypes.PositionSideLong
	switch input.Side {
	case model.PositionSideLong:
		side = ctypes.PositionSideLong
	case model.PositionSideShort:
		side = ctypes.PositionSideShort
	}
	orderType := ctypes.OrderTypeLimit
	switch input.OrderType {
	case model.OrderTypeMarket:
		orderType = ctypes.OrderTypeMarket
	case model.OrderTypeLimit:
		orderType = ctypes.OrderTypeLimit
	case model.OrderTypeNone:
		orderType = ctypes.OrderTypeUnknown
	}

	req := &ctypes.PlaceOrderRequest{
		AccountID:     accountID,
		Symbol:        symbol,
		Side:          side,
		IsBuy:         input.IsBuy,
		OrderType:     orderType,
		Price:         input.Price,
		Quantity:      lo.ToPtr(quantity),
		TimeInForce:   input.TimeInForce,
		ReduceOnly:    input.ReduceOnly,
		ClosePosition: input.ClosePosition,
	}

	resp, err := r.OrderSvc.PlaceOrder(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp == nil {
		return nil, mowerror.New(mowerror.Internal, "empty response")
	}
	if resp.Error != nil && strings.TrimSpace(*resp.Error) != "" {
		return nil, mowerror.New(mowerror.Internal, strings.TrimSpace(*resp.Error))
	}

	return &model.PlaceOrderResult{
		OrderID:       resp.OrderId,
		ClientOrderID: resp.ClientOrderId,
	}, nil
}

// CancelOrder is the resolver for the CancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, input model.CancelOrderInput) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}

	accountID := strings.TrimSpace(input.AccountID)
	if accountID == "" {
		return false, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}
	symbol := strings.TrimSpace(input.Symbol)
	if symbol == "" {
		return false, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}
	var clientOrderID, orderID string
	if input.ClientOrderID != nil {
		clientOrderID = strings.TrimSpace(*input.ClientOrderID)
	}
	if input.OrderID != nil {
		orderID = strings.TrimSpace(*input.OrderID)
	}
	if clientOrderID == "" && orderID == "" {
		return false, mowerror.New(mowerror.InvalidArgument, "clientOrderId or orderId is required")
	}

	req := &ctypes.CancelOrderRequest{
		AccountID:     accountID,
		Symbol:        symbol,
		ClientOrderID: clientOrderID,
		OrderID:       orderID,
	}

	resp, err := r.OrderSvc.CancelOrder(ctx, req)
	if err != nil {
		return false, err
	}
	if resp == nil {
		return false, mowerror.New(mowerror.Internal, "empty response")
	}
	if resp.Error != nil && strings.TrimSpace(*resp.Error) != "" {
		return false, mowerror.New(mowerror.Internal, strings.TrimSpace(*resp.Error))
	}
	return resp.Success, nil
}

// SetLeverage is the resolver for the SetLeverage field.
func (r *mutationResolver) SetLeverage(ctx context.Context, accountID string, symbol string, leverage int) (int, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return 0, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}

	accountID = strings.TrimSpace(accountID)
	if accountID == "" {
		return 0, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}
	symbol = strings.TrimSpace(symbol)
	if symbol == "" {
		return 0, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}
	if leverage <= 0 {
		return 0, mowerror.New(mowerror.InvalidArgument, "leverage must be > 0")
	}

	resp, err := r.AccountSvc.SetLeverage(ctx, &ctypes.SetLeverageRequest{
		AccountID: accountID,
		Symbol:    symbol,
		Leverage:  int32(leverage),
	})
	if err != nil {
		return 0, err
	}
	return int(resp.Leverage), nil
}

// UpdateAccountRiskConfig is the resolver for the UpdateAccountRiskConfig field.
func (r *mutationResolver) UpdateAccountRiskConfig(ctx context.Context, input model.UpdateAccountRiskConfigInput) (*model.Account, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	accountID := strings.TrimSpace(input.AccountID)
	if accountID == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	toAmountLimit := func(src *model.AmountLimitInput) *ctypes.AmountLimitStrings {
		if src == nil {
			return nil
		}
		amount := lo.FromPtr(src.Amount)
		ratio := lo.FromPtr(src.Ratio)
		if strings.TrimSpace(amount) == "" && strings.TrimSpace(ratio) == "" {
			return nil
		}
		return &ctypes.AmountLimitStrings{Amount: amount, Ratio: ratio}
	}

	resp, err := r.AccountSvc.UpdateAccountRiskConfig(ctx, &ctypes.UpdateAccountRiskConfigRequest{
		AccountID:                 accountID,
		MaxOrderSize:              lo.FromPtr(input.MaxOrderSize),
		MaxLeverage:               lo.FromPtr(input.MaxLeverage),
		MaxOrdersPerMinute:        int32(lo.FromPtrOr(input.MaxOrdersPerMinute, 0)),
		MinMaintenanceMarginRatio: lo.FromPtr(input.MinMaintenanceMarginRatio),
		RiskIndexThreshold:        lo.FromPtr(input.RiskIndexThreshold),
		RiskIndexAction:           lo.FromPtr(input.RiskIndexAction),
		CooldownSeconds:           int32(lo.FromPtrOr(input.CooldownSeconds, 0)),
		MaxPositionPerSymbol:      toAmountLimit(input.MaxPositionPerSymbol),
		MaxDailyLoss:              toAmountLimit(input.MaxDailyLoss),
		MaxTotalNetExposure:       toAmountLimit(input.MaxTotalNetExposure),
		MaxTotalGrossExposure:     toAmountLimit(input.MaxTotalGrossExposure),
	})
	if err != nil {
		return nil, err
	}
	if resp == nil || resp.Account == nil {
		return nil, mowerror.New(mowerror.Internal, "empty response")
	}
	return converter.AccountTypes2Gql(resp.Account), nil
}

// Accounts is the resolver for the Accounts field.
func (r *queryResolver) Accounts(ctx context.Context, input model.QueryAccountsInput) (*model.AccountsConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	response, err := r.AccountSvc.QueryAccounts(ctx, &ctypes.QueryAccountsRequest{
		Id:             input.ID,
		Offset:         int64(input.Offset),
		Limit:          int64(input.Limit),
		Name:           input.Name,
		Tags:           input.Tags,
		Exchange:       input.Exchange,
		Status:         converter.AccountStatusGql2TypesPtr(input.Status),
		CreatedAtStart: types.PIntToPInt64(input.CreatedAtStart),
		CreatedAtEnd:   types.PIntToPInt64(input.CreatedAtEnd),
	})
	if err != nil {
		return nil, err
	}
	projects := make([]*model.Account, len(response.Accounts))
	for i := range response.Accounts {
		projects[i] = converter.AccountTypes2Gql(response.Accounts[i])
	}
	return &model.AccountsConnection{
		List:       projects,
		TotalCount: int(response.Count),
	}, nil
}

// Equitys is the resolver for the Equitys field.
func (r *queryResolver) Equitys(ctx context.Context, input model.QueryEquitysInput) ([]*model.Equity, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if input.AccountID == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}
	rangeKey := strings.ToLower(strings.TrimSpace(input.Range))
	duration := 7 * 24 * time.Hour
	switch rangeKey {
	case "1d", "1day", "day":
		duration = 24 * time.Hour
	case "7d", "1w", "week", "7day":
		duration = 7 * 24 * time.Hour
	case "30d", "1m", "month", "30day":
		duration = 30 * 24 * time.Hour
	}
	endTs := time.Now()
	startTs := endTs.Add(-duration)

	response, err := r.AccountSvc.QueryEquitys(ctx, &ctypes.QueryEquitysRequest{
		AccountID: input.AccountID,
		StartTs:   startTs.UnixMilli(),
		EndTs:     endTs.UnixMilli(),
	})
	if err != nil {
		return nil, err
	}
	if response == nil || len(response.Equitys) == 0 {
		return []*model.Equity{}, nil
	}
	result := make([]*model.Equity, 0, len(response.Equitys))
	for _, item := range response.Equitys {
		if item == nil {
			continue
		}
		if ge := converter.EquityTypes2Gql(item); ge != nil {
			result = append(result, ge)
		}
	}
	return result, nil
}

// AccountEventFlow is the resolver for the AccountEventFlow field.
func (r *queryResolver) AccountEventFlow(ctx context.Context, input model.QueryAccountEventFlowInput) (*model.AccountEventFlowConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if input.AccountID == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	stream := converter.EventFlowStreamGql2Types(input.Stream)
	if stream == ctypes.EventFlowStreamUnspecified {
		stream = ctypes.EventFlowStreamAll
	}

	limit := int32(100)
	if input.Limit != nil && *input.Limit > 0 {
		limit = int32(*input.Limit)
	}

	var startID *int64
	if input.StartID != nil {
		startID = lo.ToPtr(int64(*input.StartID))
	}

	response, err := r.AccountSvc.QueryAccountEventFlow(ctx, &ctypes.QueryAccountEventFlowRequest{
		AccountID: input.AccountID,
		Stream:    stream,
		StartTsMs: types.PIntToPInt64(input.StartTsMs),
		StartID:   startID,
		Limit:     limit,
	})
	if err != nil {
		return nil, err
	}

	events := make([]*model.EventRecord, 0, len(response.Events))
	for _, evt := range response.Events {
		if evt == nil {
			continue
		}
		events = append(events, &model.EventRecord{
			ID:          strconv.FormatInt(evt.ID, 10),
			AccountID:   evt.AccountID,
			Exchange:    evt.Exchange,
			Stream:      evt.Stream,
			Topic:       evt.Topic,
			EventKind:   evt.EventKind,
			TsMs:        int(evt.TsMs),
			ReceiveAtMs: int(evt.ReceiveAtMs),
			PublishAtMs: int(evt.PublishAtMs),
			IngestAtMs:  int(evt.IngestAtMs),
			PayloadJSON: evt.PayloadJSON,
		})
	}

	return &model.AccountEventFlowConnection{
		Events: events,
		NextID: strconv.FormatInt(response.NextID, 10),
	}, nil
}

// Leverage is the resolver for the Leverage field.
func (r *queryResolver) Leverage(ctx context.Context, accountID string, symbol string) (int, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return 0, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}

	accountID = strings.TrimSpace(accountID)
	if accountID == "" {
		return 0, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}
	symbol = strings.TrimSpace(symbol)
	if symbol == "" {
		return 0, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}

	resp, err := r.AccountSvc.GetLeverage(ctx, &ctypes.GetLeverageRequest{
		AccountID: accountID,
		Symbol:    symbol,
	})
	if err != nil {
		return 0, err
	}
	return int(resp.Leverage), nil
}

// AccountMetrics is the resolver for the AccountMetrics field.
func (r *queryResolver) AccountMetrics(ctx context.Context, input model.QueryAccountMetricsInput) (*model.AccountMetrics, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	resp, err := r.AccountSvc.QueryAccountMetrics(ctx, &ctypes.QueryAccountMetricsRequest{
		AccountID: input.AccountID,
		Dimension: converter.MetricsDimensionGql2AccountAPI(input.Dimension),
		Symbol:    input.Symbol,
		StartTs:   types.PIntToPInt64(input.StartTs),
		EndTs:     types.PIntToPInt64(input.EndTs),
	})
	if err != nil {
		return nil, err
	}
	return converter.AccountMetricsTypes2Model(resp), nil
}

// RiskEvents is the resolver for the RiskEvents field.
func (r *queryResolver) RiskEvents(ctx context.Context, input model.QueryRiskEventsInput) ([]*model.RiskEvent, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	accountID := strings.TrimSpace(input.AccountID)
	if accountID == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	limit := int64(50)
	if input.Limit != nil && *input.Limit > 0 && *input.Limit <= 200 {
		limit = int64(*input.Limit)
	}
	offset := int64(0)
	if input.Offset != nil && *input.Offset >= 0 {
		offset = int64(*input.Offset)
	}

	resp, err := r.AccountSvc.QueryRiskEvents(ctx, &ctypes.QueryRiskEventsRequest{
		AccountID: accountID,
		Limit:     limit,
		Offset:    offset,
	})
	if err != nil {
		return nil, err
	}
	if resp == nil || len(resp.Events) == 0 {
		return []*model.RiskEvent{}, nil
	}

	out := make([]*model.RiskEvent, 0, len(resp.Events))
	for _, evt := range resp.Events {
		if evt == nil {
			continue
		}
		var riskIndexPtr *string
		if strings.TrimSpace(evt.RiskIndex) != "" {
			riskIndexPtr = lo.ToPtr(evt.RiskIndex)
		}
		var payloadPtr *string
		if strings.TrimSpace(evt.PayloadJSON) != "" {
			payloadPtr = lo.ToPtr(evt.PayloadJSON)
		}
		out = append(out, &model.RiskEvent{
			ID:          int(evt.ID),
			AccountID:   evt.AccountID,
			Exchange:    evt.Exchange,
			Rule:        evt.Rule,
			RiskIndex:   riskIndexPtr,
			PayloadJSON: payloadPtr,
			CreatedAt:   int(evt.CreatedAt),
		})
	}
	return out, nil
}

// Account returns action.AccountResolver implementation.
func (r *Resolver) Account() action.AccountResolver { return &accountResolver{r} }

// Mutation returns action.MutationResolver implementation.
func (r *Resolver) Mutation() action.MutationResolver { return &mutationResolver{r} }

// Query returns action.QueryResolver implementation.
func (r *Resolver) Query() action.QueryResolver { return &queryResolver{r} }

type accountResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
