package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/samber/lo"
	"github.com/wangliang139/llt-trade/server/pkg/action/converter"
	"github.com/wangliang139/llt-trade/server/pkg/action/model"
	"github.com/wangliang139/llt-trade/server/pkg/gateway/auth"
	"github.com/wangliang139/llt-trade/server/pkg/types"
	utypes "github.com/wangliang139/llt-trade/server/pkg/utils/types"
	mowerror "github.com/wangliang139/mow/errors"
)

// Calendars is the resolver for the Calendars field.
func (r *queryResolver) Calendars(ctx context.Context, input model.QueryCalendarsInput) ([]*model.Calendar, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	resp, err := r.DocumentSvc.QueryCalendar(ctx, &types.QueryCalendarRequest{
		DateID:        int32(input.DateID),
		Source:        converter.CalendarSourceGql2Repo(input.Source),
		Type:          converter.CalendarTypeGql2Repo(input.Type),
		Category:      input.Category,
		Country:       input.Country,
		MinImportance: utypes.PIntToPInt32(input.MinImportance),
	})
	if err != nil {
		return nil, err
	}
	return lo.Map(resp.Calendars, func(item *types.Calendar, _ int) *model.Calendar {
		return converter.CalendarTypes2Gql(item)
	}), nil
}
