package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strings"
	"time"

	"github.com/samber/lo"
	"github.com/wangliang139/NovaForge/server/pkg/action"
	"github.com/wangliang139/NovaForge/server/pkg/action/converter"
	"github.com/wangliang139/NovaForge/server/pkg/action/model"
	"github.com/wangliang139/NovaForge/server/pkg/gateway/auth"
	"github.com/wangliang139/NovaForge/server/pkg/service/alertsvc"
	ctypes "github.com/wangliang139/NovaForge/server/pkg/types"
	mowerror "github.com/wangliang139/mow/errors"
)

// AddAlert is the resolver for the AddAlert field.
func (r *mutationResolver) AddAlert(ctx context.Context, input model.AlertItemInput) (*model.AlertItem, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	item, err := r.AlertSvc.AddAlert(ctx, alertsvc.AddAlertInput{
		Exchange:        input.Exchange,
		Symbol:          input.Symbol,
		Type:            input.Type.String(),
		Frequency:       input.Frequency.String(),
		Price:           input.Price,
		Window:          input.Window,
		Percent:         input.Percent,
		Remark:          input.Remark,
		CooldownSeconds: input.CooldownSeconds,
	})
	if err != nil {
		return nil, err
	}
	return converter.ToGqlAlertItem(*item), nil
}

// RemoveAlert is the resolver for the RemoveAlert field.
func (r *mutationResolver) RemoveAlert(ctx context.Context, id string) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if strings.TrimSpace(id) == "" {
		return false, mowerror.New(mowerror.InvalidArgument, "id is required")
	}
	return r.AlertSvc.RemoveAlert(ctx, id)
}

// Markets is the resolver for the Markets field.
func (r *queryResolver) Markets(ctx context.Context, input model.GetMarketsInput) ([]*model.Market, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &ctypes.GetMarketsRequest{
		Exchange: input.Exchange,
	}
	if input.AccountID != nil {
		request.AccountID = *input.AccountID
	}
	if len(input.MarketTypes) > 0 {
		request.MarketTypes = make([]ctypes.MarketType, 0, len(input.MarketTypes))
		for _, mt := range input.MarketTypes {
			t := converter.MarketTypeGql2Types(mt)
			if t.Valid() {
				request.MarketTypes = append(request.MarketTypes, t)
			}
		}
	}

	response, err := r.MarketSvc.GetMarkets(ctx, request)
	if err != nil {
		return nil, err
	}

	markets := make([]*model.Market, len(response.Markets))
	for i, m := range response.Markets {
		markets[i] = converter.MarketTypes2Gql(m)
	}

	return markets, nil
}

// Market is the resolver for the Market field.
func (r *queryResolver) Market(ctx context.Context, input model.GetMarketInput) (*model.Market, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &ctypes.GetMarketRequest{
		Exchange: input.Exchange,
		Symbol:   input.Symbol,
	}
	if input.AccountID != nil {
		request.AccountID = *input.AccountID
	}

	response, err := r.MarketSvc.GetMarket(ctx, request)
	if err != nil {
		return nil, err
	}

	return converter.MarketTypes2Gql(response.Market), nil
}

// StreamStats is the resolver for the StreamStats field.
func (r *queryResolver) StreamStats(ctx context.Context, windowHours *int) ([]*model.StreamStatsItem, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	wh := int32(1)
	if windowHours != nil && *windowHours > 0 {
		wh = int32(*windowHours)
	}
	req := &ctypes.GetStreamStatsRequest{WindowHours: wh}
	resp, err := r.StreamSvc.GetStreamStats(ctx, req)
	if err != nil {
		return nil, err
	}
	items := make([]*model.StreamStatsItem, 0, len(resp.Stats))
	for _, s := range resp.Stats {
		items = append(items, &model.StreamStatsItem{
			Exchange:       s.Exchange.String(),
			Stream:         s.Stream,
			EventCount:     int(s.EventCount),
			AvgLatencyMs:   s.AvgLatencyMs,
			MaxLatencyMs:   s.MaxLatencyMs,
			ReconnectCount: int(s.ReconnectCount),
		})
	}
	return items, nil
}

// OrderBook is the resolver for the OrderBook field.
func (r *queryResolver) OrderBook(ctx context.Context, input model.QueryOrderBookInput) (*model.OrderBook, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if strings.TrimSpace(input.Symbol) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}

	request := &ctypes.GetOrderBookRequest{
		Exchange: input.Exchange,
		Symbol:   input.Symbol,
		Depth:    input.Depth,
	}

	resp, err := r.MarketSvc.GetOrderBook(ctx, request)
	if err != nil {
		return nil, err
	}
	if resp == nil || resp.Snapshot == nil {
		return nil, nil
	}

	return converter.OrderBookTypes2Gql(resp.Snapshot), nil
}

// Kline is the resolver for the Kline field.
func (r *queryResolver) Kline(ctx context.Context, input model.QueryKlineInput) ([]*model.Kline, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	var startTs, endTime *int64
	if input.StartTime != nil {
		startTs = lo.ToPtr(int64(*input.StartTime))
	}
	if input.EndTime != nil {
		endTime = lo.ToPtr(int64(*input.EndTime))
	}
	var limit *int
	if input.Limit != nil {
		limit = input.Limit
	}
	request := &ctypes.GetHisKlinesRequest{
		Exchange: input.Exchange,
		Symbol:   input.Symbol,
		Interval: input.Interval,
		StartTs:  startTs,
		EndTs:    endTime,
		Limit:    limit,
	}

	response, err := r.MarketSvc.GetHisKlines(ctx, request)
	if err != nil {
		return nil, err
	}

	klines := make([]*model.Kline, len(response.Klines))
	for i, kline := range response.Klines {
		klines[i] = converter.KlineTypes2Gql(kline)
	}

	return klines, nil
}

// FundingRate is the resolver for the FundingRate field.
func (r *queryResolver) FundingRate(ctx context.Context, input model.QueryFundingRateInput) (*model.FundingRate, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if strings.TrimSpace(input.Symbol) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}

	request := &ctypes.GetFundingRateRequest{
		Exchange: input.Exchange,
		Symbol:   input.Symbol,
	}
	if input.AccountID != nil {
		request.AccountID = *input.AccountID
	}

	resp, err := r.MarketSvc.GetFundingRate(ctx, request)
	if err != nil {
		return nil, err
	}
	if resp == nil || resp.FundingRate == nil {
		return nil, nil
	}
	return converter.FundingRateTypes2Gql(resp.FundingRate), nil
}

// FundingRates is the resolver for the FundingRates field.
func (r *queryResolver) FundingRates(ctx context.Context, input model.QueryFundingRatesInput) ([]*model.FundingRate, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if strings.TrimSpace(input.Symbol) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}

	request := &ctypes.GetHisFundingRatesRequest{
		Exchange: input.Exchange,
		Symbol:   input.Symbol,
	}
	if input.StartTime != nil {
		request.StartTs = lo.ToPtr(int64(*input.StartTime))
	}
	if input.EndTime != nil {
		request.EndTs = lo.ToPtr(int64(*input.EndTime))
	}
	if input.Limit != nil {
		request.Limit = input.Limit
	}
	if input.AccountID != nil {
		request.AccountID = *input.AccountID
	}

	resp, err := r.MarketSvc.GetHisFundingRates(ctx, request)
	if err != nil {
		return nil, err
	}
	if resp == nil || len(resp.FundingRates) == 0 {
		return []*model.FundingRate{}, nil
	}

	result := make([]*model.FundingRate, 0, len(resp.FundingRates))
	for _, fr := range resp.FundingRates {
		if fr == nil {
			continue
		}
		result = append(result, converter.FundingRateTypes2Gql(fr))
	}
	return result, nil
}

// OpenInterest is the resolver for the OpenInterest field.
func (r *queryResolver) OpenInterest(ctx context.Context, input model.QueryOpenInterestInput) (*model.OpenInterest, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if strings.TrimSpace(input.Symbol) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}

	request := &ctypes.GetOpenInterestRequest{
		Exchange: input.Exchange,
		Symbol:   input.Symbol,
	}
	if input.AccountID != nil {
		request.AccountID = *input.AccountID
	}

	resp, err := r.MarketSvc.GetOpenInterest(ctx, request)
	if err != nil {
		return nil, err
	}
	openInterest := ""
	if resp != nil {
		openInterest = resp.OpenInterest
	}

	return &model.OpenInterest{
		Exchange:     input.Exchange,
		Symbol:       input.Symbol,
		OpenInterest: openInterest,
		Ts:           int(time.Now().UnixMilli()),
	}, nil
}

// LeverageBracket is the resolver for the LeverageBracket field.
func (r *queryResolver) LeverageBracket(ctx context.Context, input model.QueryLeverageBracketInput) (*model.LeverageBracket, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if strings.TrimSpace(input.Symbol) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}
	if strings.TrimSpace(input.MarkPrice) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "markPrice is required")
	}

	request := &ctypes.GetLeverageBracketRequest{
		Exchange:  input.Exchange,
		Symbol:    input.Symbol,
		MarkPrice: input.MarkPrice,
	}
	if input.AccountID != nil {
		request.AccountID = *input.AccountID
	}

	resp, err := r.MarketSvc.GetLeverageBracket(ctx, request)
	if err != nil {
		return nil, err
	}
	if resp == nil || resp.LeverageBracket == nil {
		return nil, nil
	}
	return converter.LeverageBracketTypes2Gql(resp.LeverageBracket), nil
}

// IndexPrice is the resolver for the IndexPrice field.
func (r *queryResolver) IndexPrice(ctx context.Context, input model.QueryIndexPriceInput) (*model.IndexPrice, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if strings.TrimSpace(input.Symbol) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}
	request := &ctypes.GetIndexPriceRequest{
		Exchange: input.Exchange,
		Symbol:   input.Symbol,
	}
	if input.AccountID != nil {
		request.AccountID = *input.AccountID
	}
	resp, err := r.MarketSvc.GetIndexPrice(ctx, request)
	if err != nil {
		return nil, err
	}
	if resp == nil || resp.IndexPrice == nil {
		return nil, nil
	}
	return converter.IndexPriceTypes2Gql(resp.IndexPrice), nil
}

// IndexComponent is the resolver for the IndexComponent field.
func (r *queryResolver) IndexComponent(ctx context.Context, input model.QueryIndexComponentInput) (*model.IndexComponent, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if strings.TrimSpace(input.Symbol) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}
	request := &ctypes.GetIndexComponentRequest{
		Exchange: input.Exchange,
		Symbol:   input.Symbol,
	}
	if input.AccountID != nil {
		request.AccountID = *input.AccountID
	}
	resp, err := r.MarketSvc.GetIndexComponent(ctx, request)
	if err != nil {
		return nil, err
	}
	if resp == nil || resp.IndexComponent == nil {
		return nil, nil
	}
	return converter.IndexComponentTypes2Gql(resp.IndexComponent), nil
}

// AccountInfo is the resolver for the AccountInfo field.
func (r *queryResolver) AccountInfo(ctx context.Context, input model.QueryAccountInfoInput) (*model.MarketAccount, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(input.AccountID) == 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	response, err := r.AccountSvc.GetAccount(ctx, &ctypes.GetAccountRequest{AccountID: input.AccountID})
	if err != nil {
		return nil, err
	}

	return converter.MarketAccountBo2Gql(response.Account), nil
}

// Balance is the resolver for the Balance field.
func (r *queryResolver) Balance(ctx context.Context, input model.QueryBalanceInput) (*model.Balance, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(input.AccountID) == 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	req := &ctypes.GetBalanceRequest{AccountID: input.AccountID}
	if input.WalletType != nil {
		wt := ctypes.WalletType(*input.WalletType)
		req.WalletType = &wt
	}
	req.Asset = input.Asset
	req.WithNotional = input.WithNotional

	response, err := r.AccountSvc.GetBalance(ctx, req)
	if err != nil {
		return nil, err
	}

	return converter.BalanceTypes2Gql(response.Balance), nil
}

// Positions is the resolver for the Positions field.
func (r *queryResolver) Positions(ctx context.Context, input model.QueryPositionsInput) ([]*model.Position, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(input.AccountID) == 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	mt := ctypes.MarketTypeFuture
	req := &ctypes.GetPositionsRequest{
		AccountID:  input.AccountID,
		MarketType: &mt,
	}
	if input.Symbol != nil {
		req.Symbol = input.Symbol
	}

	response, err := r.AccountSvc.GetPositions(ctx, req)
	if err != nil {
		return nil, err
	}

	positions := make([]*model.Position, 0, len(response.Positions))
	for _, p := range response.Positions {
		if pp := converter.PositionTypes2Gql(p); pp != nil {
			positions = append(positions, pp)
		}
	}

	return positions, nil
}

// Orders is the resolver for the Orders field.
func (r *queryResolver) Orders(ctx context.Context, input model.QueryOrdersInput) (*model.OrdersConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(input.AccountID) == 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	hasFinStart := input.FinishedStartTsMs != nil
	hasFinEnd := input.FinishedEndTsMs != nil
	if hasFinStart != hasFinEnd {
		return nil, mowerror.New(mowerror.InvalidArgument, "finishedStartTsMs and finishedEndTsMs must both be set or both omitted")
	}
	if hasFinStart && !input.IncludeFinished {
		return nil, mowerror.New(mowerror.InvalidArgument, "includeFinished must be true when filtering by finished time range")
	}

	request := &ctypes.QueryOrdersByPageRequest{
		AccountID: input.AccountID,
		Page:      int32(input.Page),
		Size:      int32(input.Size),
	}
	if input.Symbol != nil {
		request.Symbol = *input.Symbol
	}
	if input.OrderType != nil {
		switch *input.OrderType {
		case model.OrderTypeMarket:
			request.OrderType = lo.ToPtr(ctypes.OrderTypeMarket)
		case model.OrderTypeLimit:
			request.OrderType = lo.ToPtr(ctypes.OrderTypeLimit)
		case model.OrderTypeNone:
			request.OrderType = lo.ToPtr(ctypes.OrderTypeUnknown)
		}
	}
	if input.OrderSource != nil {
		switch *input.OrderSource {
		case model.OrderSourceUser:
			request.OrderSource = lo.ToPtr(ctypes.OrderSourceUser)
		case model.OrderSourceStrategy:
			request.OrderSource = lo.ToPtr(ctypes.OrderSourceStrategy)
		case model.OrderSourceLiquidation:
			request.OrderSource = lo.ToPtr(ctypes.OrderSourceLiquidation)
		case model.OrderSourceAdl:
			request.OrderSource = lo.ToPtr(ctypes.OrderSourceADL)
		}
	}
	if !input.IncludeFinished {
		request.Statuses = []ctypes.OrderStatus{
			ctypes.OrderStatusNew,
			ctypes.OrderStatusPending,
			ctypes.OrderStatusWorking,
			ctypes.OrderStatusPartialDone,
		}
	}
	if hasFinStart {
		fs := int64(*input.FinishedStartTsMs)
		fe := int64(*input.FinishedEndTsMs)
		request.FinishedStartTsMs = &fs
		request.FinishedEndTsMs = &fe
	}

	response, err := r.OrderSvc.QueryOrdersByPage(ctx, request)
	if err != nil {
		return nil, err
	}

	orders := make([]*model.Order, 0, len(response.Orders))
	for _, o := range response.Orders {
		if oo := converter.OrderTypes2Gql(o); oo != nil {
			orders = append(orders, oo)
		}
	}

	totalCount := int(response.TotalCount)
	result := &model.OrdersConnection{
		List:       orders,
		TotalCount: totalCount,
	}
	return result, nil
}

// Ledgers is the resolver for the Ledgers field.
func (r *queryResolver) Ledgers(ctx context.Context, input model.QueryLedgersInput) (*model.LedgersConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if len(input.AccountID) == 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	req := &ctypes.QueryLedgersRequest{
		AccountID: input.AccountID,
		StartTs:   int64(input.StartTs),
		EndTs:     int64(input.EndTs),
		Size:      int32(input.Size),
		Page:      int32(input.Page),
	}
	if input.WalletType != nil {
		wt := ctypes.WalletType(*input.WalletType)
		req.WalletType = &wt
	}
	req.Asset = input.Asset

	response, err := r.AccountSvc.QueryLedgers(ctx, req)
	if err != nil {
		return nil, err
	}

	ledgers := make([]*model.Ledger, 0, len(response.Ledgers))
	for _, l := range response.Ledgers {
		if gl := converter.LedgerTypes2Gql(l); gl != nil {
			ledgers = append(ledgers, gl)
		}
	}

	return &model.LedgersConnection{
		List:       ledgers,
		TotalCount: int(response.TotalCount),
	}, nil
}

// EstimateOrder is the resolver for the EstimateOrder field.
func (r *queryResolver) EstimateOrder(ctx context.Context, input model.EstimateOrderInput) (*model.EstimateOrderResult, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}

	if strings.TrimSpace(input.AccountID) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}
	if strings.TrimSpace(input.Symbol) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "symbol is required")
	}
	if strings.TrimSpace(input.Notional) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "notional is required")
	}
	if strings.TrimSpace(input.Price) == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "price is required")
	}

	side := ctypes.PositionSideLong
	switch input.Side {
	case model.PositionSideLong:
		side = ctypes.PositionSideLong
	case model.PositionSideShort:
		side = ctypes.PositionSideShort
	default:
		return nil, mowerror.New(mowerror.InvalidArgument, "side is required")
	}

	req := &ctypes.EstimateOrderRequest{
		AccountID: input.AccountID,
		Symbol:    input.Symbol,
		Side:      side,
		IsBuy:     input.IsBuy,
		OrderType: ctypes.OrderType(input.OrderType),
		Price:     input.Price,
		QuoteQty:  input.Notional,
	}
	if input.Leverage != nil {
		req.Leverage = int32(*input.Leverage)
	}

	resp, err := r.AccountSvc.EstimateOrder(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp == nil {
		return &model.EstimateOrderResult{}, nil
	}

	var liquidationPricePtr, feePtr, feeAssetPtr, expectedPnlPtr *string
	if lp := strings.TrimSpace(resp.LiquidationPrice); lp != "" {
		liquidationPricePtr = &lp
	}
	if f := strings.TrimSpace(resp.Fee); f != "" {
		feePtr = &f
	}
	if fa := strings.TrimSpace(resp.FeeAsset); fa != "" {
		feeAssetPtr = &fa
	}
	if pnl := strings.TrimSpace(resp.ExpectedPnl); pnl != "" {
		expectedPnlPtr = &pnl
	}

	return &model.EstimateOrderResult{
		LiquidationPrice: liquidationPricePtr,
		Fee:              feePtr,
		FeeAsset:         feeAssetPtr,
		ExpectedPnl:      expectedPnlPtr,
	}, nil
}

// ListAlerts is the resolver for the ListAlerts field.
func (r *queryResolver) ListAlerts(ctx context.Context, exchange ctypes.Exchange, symbol string) ([]*model.AlertItem, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	rows, err := r.AlertSvc.ListAlerts(ctx, exchange, symbol)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AlertItem, 0, len(rows))
	for _, row := range rows {
		out = append(out, converter.ToGqlAlertItem(row))
	}
	return out, nil
}

// Stream is the resolver for the Stream field.
func (r *subscriptionResolver) Stream(ctx context.Context, input model.StreamInput) (<-chan *model.StreamEvent, error) {
	return r.subscribeMarketStream(ctx, input)
}

// Subscription returns action.SubscriptionResolver implementation.
func (r *Resolver) Subscription() action.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
