package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"math"
	"strconv"

	"github.com/samber/lo"
	"github.com/wangliang139/NovaForge/server/pkg/action"
	"github.com/wangliang139/NovaForge/server/pkg/action/converter"
	"github.com/wangliang139/NovaForge/server/pkg/action/model"
	"github.com/wangliang139/NovaForge/server/pkg/gateway/auth"
	stypes "github.com/wangliang139/NovaForge/server/pkg/strategy/types"
	ctypes "github.com/wangliang139/NovaForge/server/pkg/types"
	"github.com/wangliang139/NovaForge/server/pkg/utils/types"
	mowerror "github.com/wangliang139/mow/errors"
)

// StrategyName is the resolver for the strategyName field.
func (r *botResolver) StrategyName(ctx context.Context, obj *model.Bot) (string, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return "", mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	response, err := r.StrategySvc.GetStrategy(ctx, &stypes.GetStrategyRequest{
		ID:      obj.StrategyID,
		Version: lo.ToPtr(obj.StrategyVer),
	})
	if err != nil {
		return "", err
	}
	if response.Strategy == nil {
		return "", mowerror.New(mowerror.NotFound, "strategy not found")
	}
	return response.Strategy.Name, nil
}

// Upgradable is the resolver for the upgradable field.
func (r *botResolver) Upgradable(ctx context.Context, obj *model.Bot) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	// 非关键字段：失败时默认认为不可升级，避免 bots 列表整页报错
	activeResp, err := r.StrategySvc.GetStrategy(ctx, &stypes.GetStrategyRequest{
		ID: obj.StrategyID,
	})
	if err != nil || activeResp.Strategy == nil {
		return false, nil
	}

	// 策略状态不是 active：不可升级
	if activeResp.Strategy.Status != stypes.StrategyStatusActive {
		return false, nil
	}

	// 策略状态为 active，且最新激活版本号与 bot 版本号不一致：可升级
	return activeResp.Strategy.Version != obj.StrategyVer, nil
}

// CreateStrategy is the resolver for the CreateStrategy field.
func (r *mutationResolver) CreateStrategy(ctx context.Context, input model.CreateStrategyInput) (*model.Strategy, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	params := make([]*stypes.StrategyParam, 0, len(input.Params))
	for _, p := range input.Params {
		param := converter.StrategyParamFromInput(p)
		params = append(params, &param)
	}
	signals := make([]*stypes.SignalDefinition, 0, len(input.Signals))
	for _, s := range input.Signals {
		signal, err := converter.SignalDefinitionFromInput(s)
		if err != nil {
			return nil, err
		}
		signals = append(signals, &signal)
	}
	request := &stypes.CreateStrategyRequest{
		Name:        input.Name,
		Description: input.Description,
		Code:        input.Code,
		Params:      params,
		Signals:     signals,
	}
	response, err := r.StrategySvc.CreateStrategy(ctx, request)
	if err != nil {
		return nil, err
	}
	return converter.StrategyTypes2Gql(response.Strategy), nil
}

// UpdateStrategy is the resolver for the UpdateStrategy field.
func (r *mutationResolver) UpdateStrategy(ctx context.Context, input model.UpdateStrategyInput) (*model.Strategy, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.UpdateStrategyRequest{
		Id:      input.ID,
		Version: input.Version,
	}
	if input.Name != nil {
		request.Name = *input.Name
	}
	if input.Description != nil {
		request.Description = *input.Description
	}
	if input.Code != nil {
		request.Code = *input.Code
	}
	if input.Params != nil {
		params := make([]*stypes.StrategyParam, 0, len(input.Params))
		for _, p := range input.Params {
			param := converter.StrategyParamFromInput(p)
			params = append(params, &param)
		}
		request.Params = params
	}
	if input.Signals != nil {
		signals := make([]*stypes.SignalDefinition, 0, len(input.Signals))
		for _, s := range input.Signals {
			signal, err := converter.SignalDefinitionFromInput(s)
			if err != nil {
				return nil, err
			}
			signals = append(signals, &signal)
		}
		request.Signals = signals
	}
	response, err := r.StrategySvc.UpdateStrategy(ctx, request)
	if err != nil {
		return nil, err
	}
	return converter.StrategyTypes2Gql(response.Strategy), nil
}

// GenerateStrategy is the resolver for the GenerateStrategy field.
func (r *mutationResolver) GenerateStrategy(ctx context.Context, input model.GenerateStrategyInput) (*model.GenerateStrategyResponse, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}

	output, err := r.StrategySvc.GenerateStrategy(ctx, &stypes.GenerateStrategyRequest{
		Query: input.Query,
	})
	if err != nil {
		return nil, err
	}

	return &model.GenerateStrategyResponse{
		SessionID: output.SessionID,
		Content:   output.Content,
	}, nil
}

// DeleteStrategy is the resolver for the DeleteStrategy field.
func (r *mutationResolver) DeleteStrategy(ctx context.Context, id string) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.DeleteStrategyRequest{
		ID: id,
	}
	_, err := r.StrategySvc.DeleteStrategy(ctx, request)
	if err != nil {
		return false, err
	}
	return true, nil
}

// ActiveStrategy is the resolver for the ActiveStrategy field.
func (r *mutationResolver) ActiveStrategy(ctx context.Context, id string) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.ActiveStrategyRequest{
		ID: id,
	}
	_, err := r.StrategySvc.ActiveStrategy(ctx, request)
	if err != nil {
		return false, err
	}
	return true, nil
}

// InactiveStrategy is the resolver for the InactiveStrategy field.
func (r *mutationResolver) InactiveStrategy(ctx context.Context, id string) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.InactiveStrategyRequest{
		ID: id,
	}
	_, err := r.StrategySvc.InactiveStrategy(ctx, request)
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateDatasource is the resolver for the CreateDatasource field.
func (r *mutationResolver) CreateDatasource(ctx context.Context, input model.CreateDatasourceInput) (*model.DataSource, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.CreateDatasourceRequest{
		Type:        converter.SignalTypeGql2Types(input.Type),
		Name:        input.Name,
		Description: input.Description,
		Exchange:    input.Exchange,
		Symbol:      input.Symbol,
		Props:       input.Props,
		StartTs:     int64(input.StartTs),
		EndTs:       int64(input.EndTs),
	}
	response, err := r.StrategySvc.CreateDatasource(ctx, request)
	if err != nil {
		return nil, err
	}
	return converter.DataSourceTypes2Gql(response.Datasource), nil
}

// DeleteDatasource is the resolver for the DeleteDatasource field.
func (r *mutationResolver) DeleteDatasource(ctx context.Context, id int) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.DeleteDatasourceRequest{
		ID: int32(id),
	}
	_, err := r.StrategySvc.DeleteDatasource(ctx, request)
	if err != nil {
		return false, err
	}
	return true, nil
}

// RunBacktest is the resolver for the RunBacktest field.
func (r *mutationResolver) RunBacktest(ctx context.Context, input model.RunBacktestInput) (*model.RunBacktestResponse, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request, err := converter.RunBacktestInputGql2Types(&input)
	if err != nil {
		return nil, err
	}
	response, err := r.StrategySvc.RunBacktest(ctx, request)
	if err != nil {
		return nil, err
	}
	return converter.RunBacktestResponseTypes2Gql(response), nil
}

// CreateBot is the resolver for the CreateBot field.
func (r *mutationResolver) CreateBot(ctx context.Context, input model.CreateBotInput) (*model.Bot, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	var mode stypes.BotMode
	switch input.Mode {
	case model.BotModeLive:
		mode = stypes.BotModeLive
	case model.BotModePaper:
		mode = stypes.BotModePaper
	default:
		return nil, fmt.Errorf("invalid bot mode")
	}

	if mode == stypes.BotModeLive && input.AccountID == "" {
		return nil, mowerror.New(mowerror.InvalidArgument, "accountId is required")
	}

	request := &stypes.CreateBotRequest{
		StrategyID:  input.StrategyID,
		StrategyVer: input.StrategyVer,
		Name:        input.Name,
		Description: input.Description,
		Mode:        mode,
		Exchange:    input.Exchange,
		Symbols:     input.Symbols,
		AccountID:   input.AccountID,
		Config:      input.Config,
	}
	response, err := r.StrategySvc.CreateBot(ctx, request)
	if err != nil {
		return nil, err
	}
	return converter.BotTypes2Gql(response.Bot), nil
}

// UpdateBot is the resolver for the UpdateBot field.
func (r *mutationResolver) UpdateBot(ctx context.Context, input model.UpdateBotInput) (*model.Bot, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.UpdateBotRequest{
		ID:          int32(input.ID),
		Name:        lo.ToPtr(input.Name),
		Description: lo.ToPtr(input.Description),
		Symbols:     input.Symbols,
		Config:      input.Config,
	}
	response, err := r.StrategySvc.UpdateBot(ctx, request)
	if err != nil {
		return nil, err
	}
	return converter.BotTypes2Gql(response.Bot), nil
}

// StartBot is the resolver for the StartBot field.
func (r *mutationResolver) StartBot(ctx context.Context, id int) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.StartBotRequest{
		ID: int32(id),
	}
	_, err := r.StrategySvc.StartBot(ctx, request)
	if err != nil {
		return false, err
	}
	return true, nil
}

// StopBot is the resolver for the StopBot field.
func (r *mutationResolver) StopBot(ctx context.Context, id int) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.StopBotRequest{
		ID: int32(id),
	}
	_, err := r.StrategySvc.StopBot(ctx, request)
	if err != nil {
		return false, err
	}
	return true, nil
}

// UpgradeBot is the resolver for the UpgradeBot field.
func (r *mutationResolver) UpgradeBot(ctx context.Context, id int) (*model.UpgradeBotResult, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.UpgradeBotRequest{
		ID: int32(id),
	}
	resp, err := r.StrategySvc.UpgradeBot(ctx, request)
	if err != nil {
		return nil, err
	}

	var msg *string
	if resp.Message != "" {
		msg = lo.ToPtr(resp.Message)
	}
	var botObj *model.Bot
	if resp.Bot != nil {
		botObj = converter.BotTypes2Gql(resp.Bot)
	}

	return &model.UpgradeBotResult{
		Success: resp.Success,
		Message: msg,
		Bot:     botObj,
	}, nil
}

// DeleteBot is the resolver for the DeleteBot field.
func (r *mutationResolver) DeleteBot(ctx context.Context, id int) (bool, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.DeleteBotRequest{
		ID: int32(id),
	}
	_, err := r.StrategySvc.DeleteBot(ctx, request)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Strategies is the resolver for the Strategies field.
func (r *queryResolver) Strategies(ctx context.Context, input model.QueryStrategiesInput) (*model.StrategiesConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.ListStrategiesRequest{
		Offset: int64(input.Offset),
		Limit:  int64(input.Limit),
	}
	if input.ID != nil {
		request.ID = input.ID
	}
	if input.Version != nil {
		request.Version = input.Version
	}
	if input.Status != nil && *input.Status != model.StrategyStatusUnspecified {
		status := converter.StrategyStatusGql2Types(*input.Status)
		request.Status = &status
	}
	if input.Name != nil {
		request.Name = input.Name
	}
	if input.CreatedAtStart != nil {
		ts := int64(*input.CreatedAtStart)
		request.CreatedAtStart = &ts
	}
	if input.CreatedAtEnd != nil {
		ts := int64(*input.CreatedAtEnd)
		request.CreatedAtEnd = &ts
	}
	response, err := r.StrategySvc.ListStrategies(ctx, request)
	if err != nil {
		return nil, err
	}
	strategies := make([]*model.Strategy, 0, len(response.Strategies))
	for _, s := range response.Strategies {
		strategies = append(strategies, converter.StrategyTypes2Gql(s))
	}
	return &model.StrategiesConnection{
		List:       strategies,
		TotalCount: int(response.Count),
	}, nil
}

// Strategy is the resolver for the Strategy field.
func (r *queryResolver) Strategy(ctx context.Context, id string) (*model.Strategy, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	// Note: proto doesn't have GetStrategy, so we need to list and filter
	request := &stypes.ListStrategiesRequest{
		Offset: 0,
		Limit:  1000, // Large limit to find the strategy
	}
	response, err := r.StrategySvc.ListStrategies(ctx, request)
	if err != nil {
		return nil, err
	}
	for _, s := range response.Strategies {
		if s.ID == id {
			return converter.StrategyTypes2Gql(s), nil
		}
	}
	return nil, mowerror.New(mowerror.NotFound, "strategy not found")
}

// Datasources is the resolver for the Datasources field.
func (r *queryResolver) Datasources(ctx context.Context, input model.QueryDatasourcesInput) (*model.DatasourcesConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.ListDatasourcesRequest{
		Offset: int64(input.Offset),
		Limit:  int64(input.Limit),
	}
	if input.Type != nil {
		t := converter.SignalTypeGql2Types(*input.Type)
		request.Type = &t
	}
	if input.Exchange != nil {
		request.Exchange = input.Exchange
	}
	if input.Symbol != nil {
		request.Symbol = input.Symbol
	}
	response, err := r.StrategySvc.ListDatasources(ctx, request)
	if err != nil {
		return nil, err
	}
	datasources := make([]*model.DataSource, 0, len(response.Datasources))
	for _, ds := range response.Datasources {
		datasources = append(datasources, converter.DataSourceTypes2Gql(ds))
	}
	return &model.DatasourcesConnection{
		List:       datasources,
		TotalCount: int(response.Count),
	}, nil
}

// Datasource is the resolver for the Datasource field.
func (r *queryResolver) Datasource(ctx context.Context, id int) (*model.DataSource, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	// Note: proto doesn't have GetDatasource, so we need to list and filter
	request := &stypes.ListDatasourcesRequest{
		Offset: 0,
		Limit:  1000, // Large limit to find the datasource
	}
	response, err := r.StrategySvc.ListDatasources(ctx, request)
	if err != nil {
		return nil, err
	}
	for _, ds := range response.Datasources {
		if int(ds.ID) == id {
			return converter.DataSourceTypes2Gql(ds), nil
		}
	}
	return nil, mowerror.New(mowerror.NotFound, "datasource not found")
}

// Bots is the resolver for the Bots field.
func (r *queryResolver) Bots(ctx context.Context, input model.QueryBotsInput) (*model.BotsConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.ListBotsRequest{
		Limit:  int32(input.Limit),
		Offset: int32(input.Offset),
	}
	if input.StrategyID != nil {
		request.StrategyID = input.StrategyID
	}
	if input.Mode != nil {
		var mode stypes.BotMode
		switch *input.Mode {
		case model.BotModeLive:
			mode = stypes.BotModeLive
		case model.BotModePaper:
			mode = stypes.BotModePaper
		}
		request.Mode = &mode
	}
	if input.Exchange != nil {
		request.Exchange = input.Exchange
	}
	if input.Status != nil {
		var status stypes.BotStatus
		switch *input.Status {
		case model.BotStatusStopped:
			status = stypes.BotStatusStopped
		case model.BotStatusRunning:
			status = stypes.BotStatusRunning
		case model.BotStatusError:
			status = stypes.BotStatusError
		}
		request.Status = &status
	}
	if input.AccountID != nil {
		request.AccountID = input.AccountID
	}
	if input.Name != nil {
		request.Name = input.Name
	}
	if input.CreatedAtStart != nil {
		ts := int64(*input.CreatedAtStart)
		request.CreatedAtStart = &ts
	}
	if input.CreatedAtEnd != nil {
		ts := int64(*input.CreatedAtEnd)
		request.CreatedAtEnd = &ts
	}

	response, err := r.StrategySvc.ListBots(ctx, request)
	if err != nil {
		return nil, err
	}

	bots := make([]*model.Bot, 0, len(response.Bots))
	for _, bot := range response.Bots {
		bots = append(bots, converter.BotTypes2Gql(bot))
	}

	return &model.BotsConnection{
		TotalCount: int(response.TotalCount),
		List:       bots,
	}, nil
}

// Bot is the resolver for the Bot field.
func (r *queryResolver) Bot(ctx context.Context, id int) (*model.Bot, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.GetBotRequest{
		ID: int32(id),
	}
	response, err := r.StrategySvc.GetBot(ctx, request)
	if err != nil {
		return nil, err
	}
	return converter.BotTypes2Gql(response.Bot), nil
}

// BotBalance is the resolver for the BotBalance field.
func (r *queryResolver) BotBalance(ctx context.Context, input model.QueryBotBalanceInput) (*model.Balance, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.GetBotBalanceRequest{
		BotID:        int32(input.BotID),
		Asset:        input.Asset,
		WithNotional: input.WithNotional,
	}
	if input.WalletType != nil {
		wt := converter.WalletTypeGql2Types(input.WalletType)
		request.WalletType = wt
	}
	response, err := r.StrategySvc.GetBotBalance(ctx, request)
	if err != nil {
		return nil, err
	}
	return converter.BalanceTypes2Gql(response.Balance), nil
}

// BotPositions is the resolver for the BotPositions field.
func (r *queryResolver) BotPositions(ctx context.Context, input model.QueryBotPositionsInput) ([]*model.Position, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.GetBotPositionsRequest{
		BotID:  int32(input.BotID),
		Symbol: input.Symbol,
	}
	if input.MarketType != nil {
		mt := converter.MarketTypeGql2Types(*input.MarketType)
		request.MarketType = &mt
	}
	response, err := r.StrategySvc.GetBotPositions(ctx, request)
	if err != nil {
		return nil, err
	}
	positions := make([]*model.Position, 0, len(response.Positions))
	for _, p := range response.Positions {
		positions = append(positions, converter.PositionTypes2Gql(p))
	}
	return positions, nil
}

// BotState is the resolver for the BotState field.
func (r *queryResolver) BotState(ctx context.Context, input model.QueryBotStateInput) (*model.BotState, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if input.BotID <= 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "botId is required")
	}

	request := &stypes.GetBotStateRequest{
		BotID: int32(input.BotID),
	}
	response, err := r.StrategySvc.GetBotState(ctx, request)
	if err != nil {
		return nil, err
	}

	var portfolio *model.BotPortfolio
	if response.Portfolio != nil {
		assets := make([]*model.BotPortfolioAsset, 0, len(response.Portfolio.Assets))
		for _, a := range response.Portfolio.Assets {
			assets = append(assets, &model.BotPortfolioAsset{
				Exchange:   a.Exchange,
				WalletType: converter.WalletTypeTypes2Gql(a.WalletType),
				Asset:      a.Asset,
				Free:       a.Free,
				Frozen:     a.Frozen,
				UpdatedTs:  int(a.UpdatedTs),
			})
		}

		positions := make([]*model.BotPortfolioPosition, 0, len(response.Portfolio.Positions))
		for _, p := range response.Portfolio.Positions {
			positions = append(positions, &model.BotPortfolioPosition{
				Exchange:   p.Exchange,
				Symbol:     p.Symbol,
				MarketType: converter.MarketTypeTypes2Gql(p.MarketType),
				Side:       converter.PositionSideTypes2Gql(p.Side),
				Qty:        p.Qty,
				AvgPrice:   p.AvgPrice,
				UpdatedTs:  int(p.UpdatedTs),
				Leverage:   int(p.Leverage),
			})
		}

		portfolio = &model.BotPortfolio{
			Assets:    assets,
			Positions: positions,
			Ts:        int(response.Portfolio.Ts),
		}
	}

	return &model.BotState{
		BotStatus:           converter.BotStatusTypes2Gql(response.BotStatus),
		ExecutorStatus:      response.ExecutorStatus,
		RunErr:              &response.RunErr,
		JsRunnerStatus:      response.JsRunnerStatus,
		Portfolio:           portfolio,
		SignalAvgDurationMs: func() *int { v := int(response.SignalAvgDurationMs); return &v }(),
		SignalAvgLatencyMs:  func() *int { v := int(response.SignalAvgLatencyMs); return &v }(),
		LastSignalTs:        func() *int { v := int(response.LastSignalTs); return &v }(),
	}, nil
}

// BotOrders is the resolver for the BotOrders field.
func (r *queryResolver) BotOrders(ctx context.Context, input model.QueryBotOrdersInput) (*model.BotOrdersConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	// includeFinished=false 时，默认只返回未完成订单（与 market.Orders 行为一致）
	var statuses []ctypes.OrderStatus
	if !input.IncludeFinished {
		statuses = []ctypes.OrderStatus{
			ctypes.OrderStatusNew,
			ctypes.OrderStatusPending,
			ctypes.OrderStatusWorking,
			ctypes.OrderStatusPartialDone,
		}
	}

	request := &stypes.ListBotOrdersRequest{
		BotID:    int32(input.BotID),
		Symbol:   input.Symbol,
		Page:     int32(input.Page),
		Size:     int32(input.Size),
		Statuses: statuses,
	}
	if input.OrderType != nil {
		ot := converter.OrderTypeGql2Types(input.OrderType)
		request.OrderType = &ot
	}
	response, err := r.StrategySvc.ListBotOrders(ctx, request)
	if err != nil {
		return nil, err
	}

	orders := make([]*model.Order, 0, len(response.Orders))
	for _, order := range response.Orders {
		orders = append(orders, converter.OrderTypes2Gql(order))
	}

	return &model.BotOrdersConnection{
		TotalCount: int(response.TotalCount),
		List:       orders,
	}, nil
}

// BotLedger is the resolver for the BotLedger field.
func (r *queryResolver) BotLedger(ctx context.Context, input model.QueryBotLedgersInput) (*model.BotLedgerConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.ListBotLedgerRequest{
		BotID:   int32(input.BotID),
		Asset:   input.Asset,
		StartTs: lo.ToPtr(int64(input.StartTs)),
		EndTs:   lo.ToPtr(int64(input.EndTs)),
		Page:    int32(input.Page),
		Size:    int32(input.Size),
	}
	if input.WalletType != nil {
		wt := converter.WalletTypeGql2Types(input.WalletType)
		request.WalletType = wt
	}
	response, err := r.StrategySvc.ListBotLedger(ctx, request)
	if err != nil {
		return nil, err
	}

	entries := make([]*model.Ledger, 0, len(response.Ledgers))
	for _, entry := range response.Ledgers {
		entries = append(entries, converter.LedgerTypes2Gql(entry))
	}

	return &model.BotLedgerConnection{
		TotalCount: int(response.TotalCount),
		List:       entries,
	}, nil
}

// BotEquity is the resolver for the BotEquity field.
func (r *queryResolver) BotEquity(ctx context.Context, botID int, startTs int, endTs int) (*model.BotEquityConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	request := &stypes.ListBotEquityRequest{
		BotID:   int32(botID),
		StartTs: int64(startTs),
		EndTs:   int64(endTs),
	}
	response, err := r.StrategySvc.ListBotEquity(ctx, request)
	if err != nil {
		return nil, err
	}

	points := make([]*model.Equity, 0, len(response.Points))
	for _, point := range response.Points {
		points = append(points, converter.EquityTypes2Gql(point))
	}

	return &model.BotEquityConnection{
		TotalCount: len(points),
		List:       points,
	}, nil
}

// BotLogs is the resolver for the BotLogs field.
func (r *queryResolver) BotLogs(ctx context.Context, input model.QueryBotLogsInput) (*model.BotLogsConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	limitVal := int32(100)
	if input.Limit != nil {
		limitVal = int32(*input.Limit)
	}

	request := &stypes.ListBotLogsRequest{
		BotID: int32(input.BotID),
		Limit: limitVal,
	}
	if input.Cursor != nil {
		request.Cursor = input.Cursor
	}
	if input.StartTs != nil {
		start := int64(*input.StartTs)
		request.StartTime = &start
	}
	if input.EndTs != nil {
		end := int64(*input.EndTs)
		request.EndTime = &end
	}
	if input.Level != nil {
		request.Level = input.Level
	}

	response, err := r.StrategySvc.ListBotLogs(ctx, request)
	if err != nil {
		return nil, err
	}

	logs := make([]*model.BotLog, 0, len(response.Logs))
	for _, logEntry := range response.Logs {
		logs = append(logs, converter.BotLogTypes2Gql(logEntry))
	}

	var nextCursor *string
	if response.NextCursor != nil {
		nextCursor = response.NextCursor
	}
	return &model.BotLogsConnection{
		List:       logs,
		NextCursor: nextCursor,
	}, nil
}

// BotSignalFlow is the resolver for the BotSignalFlow field.
func (r *queryResolver) BotSignalFlow(ctx context.Context, input model.QueryBotSignalFlowInput) (*model.BotSignalFlowConnection, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if input.BotID <= 0 {
		return nil, mowerror.New(mowerror.InvalidArgument, "botId is required")
	}

	limitVal := int32(200)
	if input.Limit != nil && *input.Limit > 0 {
		limitVal = int32(*input.Limit)
	}

	request := &stypes.QueryBotSignalFlowRequest{
		BotID: int32(input.BotID),
		Limit: limitVal,
	}
	if input.SignalType != nil {
		t := converter.SignalTypeGql2Types(*input.SignalType)
		request.SignalType = &t
	}
	if input.StartTsMs != nil {
		start := int64(*input.StartTsMs)
		request.StartTsMs = &start
	}
	if input.StartID != nil {
		startID := int64(*input.StartID)
		request.StartID = &startID
	}

	response, err := r.StrategySvc.QueryBotSignalFlow(ctx, request)
	if err != nil {
		return nil, err
	}

	events := make([]*model.BotSignalRecord, 0, len(response.Events))
	for _, evt := range response.Events {
		events = append(events, &model.BotSignalRecord{
			ID:           strconv.FormatInt(evt.ID, 10),
			BotID:        int(evt.BotID),
			AccountID:    evt.AccountID,
			Exchange:     evt.Exchange,
			Stream:       evt.Stream,
			Topic:        evt.Topic,
			EventKind:    evt.EventKind,
			TsMs:         int(evt.TsMs),
			InboundAtMs:  int(evt.InboundAtMs),
			OutboundAtMs: int(evt.OutboundAtMs),
			ReceiveAtMs:  int(evt.ReceiveAtMs),
			IngestAtMs:   int(evt.IngestAtMs),
			PayloadJSON:  evt.PayloadJSON,
		})
	}

	return &model.BotSignalFlowConnection{
		Events: events,
		NextID: strconv.FormatInt(response.NextID, 10),
	}, nil
}

// BotSignalStats is the resolver for the BotSignalStats field.
func (r *queryResolver) BotSignalStats(ctx context.Context, startTs int, endTs int, botID *int) (*model.BotSignalStats, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	req := &stypes.GetBotStatsRequest{
		StartTs: int64(startTs),
		EndTs:   int64(endTs),
	}
	if botID != nil && *botID > 0 {
		bid := int32(*botID)
		req.BotID = &bid
	}
	resp, err := r.StrategySvc.GetBotStats(ctx, req)
	if err != nil {
		return nil, err
	}
	if resp == nil || len(resp.Stats) == 0 {
		return &model.BotSignalStats{Stats: []*model.BotSignalStat{}}, nil
	}
	stats := make([]*model.BotSignalStat, 0, len(resp.Stats))
	for _, s := range resp.Stats {
		stats = append(stats, &model.BotSignalStat{
			BotID:        int(s.BotID),
			Stream:       s.Stream,
			EventCount:   int(s.EventCount),
			AvgLatencyMs: s.AvgLatencyMs,
			MaxLatencyMs: s.MaxLatencyMs,
		})
	}
	return &model.BotSignalStats{Stats: stats}, nil
}

// BotMetrics is the resolver for the BotMetrics field.
func (r *queryResolver) BotMetrics(ctx context.Context, input model.QueryBotMetricsInput) (*model.BotMetrics, error) {
	_, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return nil, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	var symbol *ctypes.Symbol
	if input.Symbol != nil {
		sym, err := ctypes.ParseSymbol(*input.Symbol)
		if err != nil {
			return nil, err
		}
		symbol = &sym
	}
	dim := converter.MetricsDimensionGql2Types(input.Dimension)
	req := &stypes.QueryBotMetricsRequest{
		BotID:     int32(input.BotID),
		Dimension: dim,
		Symbol:    symbol,
		StartTs:   types.PIntToPInt64(input.StartTs),
		EndTs:     types.PIntToPInt64(input.EndTs),
	}
	pb, err := r.StrategySvc.QueryBotMetrics(ctx, req)
	if err != nil {
		return nil, err
	}

	if pb == nil {
		return nil, nil
	}
	symbols := make([]*model.SymbolMetrics, 0, len(pb.Symbols))
	for _, s := range pb.Symbols {
		symbols = append(symbols, converter.SymbolMetricsTypes2Gql(s))
	}
	sharpe := pb.Sharpe
	if math.IsNaN(sharpe) {
		sharpe = 0
	}
	sortino := pb.Sortino
	if math.IsInf(sortino, 1) {
		sortino = 0
	}
	return &model.BotMetrics{
		AccountID:             pb.AccountID,
		BotID:                 int(pb.BotID),
		Dimension:             converter.MetricsDimensionTypes2Gql(pb.Dimension),
		SymbolsFilter:         pb.SymbolsFilter,
		Cagr:                  pb.Cagr,
		Sharpe:                sharpe,
		Sortino:               sortino,
		MaxDrawdown:           pb.MaxDrawdown,
		TimeUnderWaterSeconds: int(pb.TimeUnderWaterSeconds),
		Calmar:                pb.Calmar,
		WinRate:               pb.WinRate,
		ProfitFactor:          pb.ProfitFactor,
		RollingSharpe:         pb.RollingSharpe,
		AvgSlippageBps:        pb.AvgSlippageBps,
		FeeRatio:              pb.FeeRatio,
		MaxConsecutiveLoss:    int(pb.MaxConsecutiveLoss),
		StartTs:               int(pb.StartTs),
		EndTs:                 int(pb.EndTs),
		Symbols:               symbols,
	}, nil
}

// Bot returns action.BotResolver implementation.
func (r *Resolver) Bot() action.BotResolver { return &botResolver{r} }

type botResolver struct{ *Resolver }
