package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/wangliang139/llt-trade/server/pkg/gateway/auth"
	"github.com/wangliang139/llt-trade/server/pkg/gateway/restart"
	ctypes "github.com/wangliang139/llt-trade/server/pkg/types"
	mowerror "github.com/wangliang139/mow/errors"
)

// RequestGatewayRestart is the resolver for the RequestGatewayRestart field.
func (r *mutationResolver) RequestGatewayRestart(ctx context.Context) (bool, error) {
	u, ok := auth.GetUserFromContext(ctx)
	if !ok {
		return false, mowerror.New(mowerror.PermissionDenied, "unauthorized")
	}
	if u.Source != auth.AuthSourceJWT {
		return false, mowerror.New(mowerror.PermissionDenied, "api key cannot restart gateway")
	}
	if u.Access != string(ctypes.UserAccessAdmin) {
		return false, mowerror.New(mowerror.PermissionDenied, "admin only")
	}
	if !restart.SigtermRestartEnabled() {
		return false, mowerror.New(mowerror.FailedPrecondition, "gateway sigterm restart is not enabled on server")
	}
	restart.ScheduleSigtermToCurrentProcess()
	return true, nil
}
