// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package calendar

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const getBySid = `-- name: GetBySid :one
SELECT id, date_id, sid, source, type, category, country, project, symbol, title, content, importance, url, ext, published_at, md5, created_at, updated_at
FROM public.calendar
WHERE source = $1::calendar_source
  AND sid = $2::varchar
`

type GetBySidParams struct {
	Source CalendarSource
	Sid    string
}

// -- timeout: 3s
func (q *Queries) GetBySid(ctx context.Context, arg GetBySidParams) (*Calendar, error) {
	return _GetBySid(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetBySid(ctx context.Context, arg GetBySidParams) (*Calendar, error) {
	return _GetBySid(ctx, q, arg)
}

func _GetBySid(ctx context.Context, q CacheQuerierConn, arg GetBySidParams) (*Calendar, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	q.GetConn().CountIntent("calendar.GetBySid")
	row := q.GetConn().WQueryRow(qctx, "calendar.GetBySid", getBySid, arg.Source, arg.Sid)
	var i *Calendar = new(Calendar)
	err := row.Scan(
		&i.ID,
		&i.DateID,
		&i.Sid,
		&i.Source,
		&i.Type,
		&i.Category,
		&i.Country,
		&i.Project,
		&i.Symbol,
		&i.Title,
		&i.Content,
		&i.Importance,
		&i.Url,
		&i.Ext,
		&i.PublishedAt,
		&i.Md5,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Calendar)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const groupByDateId = `-- name: GroupByDateId :many
SELECT date_id, COUNT(1)
FROM public.calendar
WHERE source = coalesce($1::calendar_source, source)
  AND type = coalesce($2::calendar_type, type)
  AND category = coalesce($3::varchar, category)
  AND (country = coalesce($4::varchar, country) or country is null)
  AND importance >= coalesce($5::int, importance)
  AND date_id between $6::int and $7::int
GROUP BY date_id
ORDER BY date_id ASC
`

type GroupByDateIdParams struct {
	Source        NullCalendarSource
	Type          NullCalendarType
	Category      *string
	Country       *string
	MinImportance *int32
	DateIDStart   int32
	DateIDEnd     int32
}

type GroupByDateIdRow struct {
	DateID int32
	Count  int64
}

// -- timeout: 3s
func (q *Queries) GroupByDateId(ctx context.Context, arg GroupByDateIdParams) ([]GroupByDateIdRow, error) {
	return _GroupByDateId(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GroupByDateId(ctx context.Context, arg GroupByDateIdParams) ([]GroupByDateIdRow, error) {
	return _GroupByDateId(ctx, q, arg)
}

func _GroupByDateId(ctx context.Context, q CacheQuerierConn, arg GroupByDateIdParams) ([]GroupByDateIdRow, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	q.GetConn().CountIntent("calendar.GroupByDateId")
	rows, err := q.GetConn().WQuery(qctx, "calendar.GroupByDateId", groupByDateId,
		arg.Source,
		arg.Type,
		arg.Category,
		arg.Country,
		arg.MinImportance,
		arg.DateIDStart,
		arg.DateIDEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupByDateIdRow
	for rows.Next() {
		var i *GroupByDateIdRow = new(GroupByDateIdRow)
		if err := rows.Scan(&i.DateID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const queryByDateId = `-- name: QueryByDateId :many
SELECT id, date_id, sid, source, type, category, country, project, symbol, title, content, importance, url, ext, published_at, md5, created_at, updated_at
FROM public.calendar
WHERE date_id = $1::int
  AND source = coalesce($2::calendar_source, source)
  AND type = coalesce($3::calendar_type, type)
  AND category = coalesce($4::varchar, category)
  AND (country = coalesce($5::varchar, country) or country is null)
  AND importance >= coalesce($6::int, importance)
ORDER BY published_at, importance DESC
OFFSET $7::int8 LIMIT $8::int8
`

type QueryByDateIdParams struct {
	DateID        int32
	Source        NullCalendarSource
	Type          NullCalendarType
	Category      *string
	Country       *string
	MinImportance *int32
	Offset        int64
	Limit         int64
}

// -- timeout: 3s
func (q *Queries) QueryByDateId(ctx context.Context, arg QueryByDateIdParams) ([]Calendar, error) {
	return _QueryByDateId(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) QueryByDateId(ctx context.Context, arg QueryByDateIdParams) ([]Calendar, error) {
	return _QueryByDateId(ctx, q, arg)
}

func _QueryByDateId(ctx context.Context, q CacheQuerierConn, arg QueryByDateIdParams) ([]Calendar, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	q.GetConn().CountIntent("calendar.QueryByDateId")
	rows, err := q.GetConn().WQuery(qctx, "calendar.QueryByDateId", queryByDateId,
		arg.DateID,
		arg.Source,
		arg.Type,
		arg.Category,
		arg.Country,
		arg.MinImportance,
		arg.Offset,
		arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var i *Calendar = new(Calendar)
		if err := rows.Scan(
			&i.ID,
			&i.DateID,
			&i.Sid,
			&i.Source,
			&i.Type,
			&i.Category,
			&i.Country,
			&i.Project,
			&i.Symbol,
			&i.Title,
			&i.Content,
			&i.Importance,
			&i.Url,
			&i.Ext,
			&i.PublishedAt,
			&i.Md5,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const updateBySid = `-- name: UpdateBySid :one
UPDATE public.calendar
SET 
    date_id = $1::int,
    type = $2::calendar_type,
    category = $3::varchar,
    country = $4::varchar,
    project = $5::varchar,
    symbol = $6::varchar,
    title = $7::varchar,
    content = $8::varchar,
    importance = $9::int,
    url = $10::varchar,
    ext = $11::jsonb,
    md5 = $12::varchar,
    published_at = $13::timestamp with time zone,
    updated_at = now()
WHERE source = $14::calendar_source
  AND sid = $15::varchar
RETURNING id, date_id, sid, source, type, category, country, project, symbol, title, content, importance, url, ext, published_at, md5, created_at, updated_at
`

type UpdateBySidParams struct {
	DateID      int32
	Type        CalendarType
	Category    string
	Country     *string
	Project     *string
	Symbol      *string
	Title       string
	Content     string
	Importance  int32
	Url         string
	Ext         []byte
	Md5         string
	PublishedAt time.Time
	Source      CalendarSource
	Sid         string
}

// -- timeout: 1s
func (q *Queries) UpdateBySid(ctx context.Context, arg UpdateBySidParams) (*Calendar, error) {
	return _UpdateBySid(ctx, q.AsReadOnly(), arg)
}

func _UpdateBySid(ctx context.Context, q CacheQuerierConn, arg UpdateBySidParams) (*Calendar, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "calendar.UpdateBySid", updateBySid,
		arg.DateID,
		arg.Type,
		arg.Category,
		arg.Country,
		arg.Project,
		arg.Symbol,
		arg.Title,
		arg.Content,
		arg.Importance,
		arg.Url,
		arg.Ext,
		arg.Md5,
		arg.PublishedAt,
		arg.Source,
		arg.Sid)
	var i *Calendar = new(Calendar)
	err := row.Scan(
		&i.ID,
		&i.DateID,
		&i.Sid,
		&i.Source,
		&i.Type,
		&i.Category,
		&i.Country,
		&i.Project,
		&i.Symbol,
		&i.Title,
		&i.Content,
		&i.Importance,
		&i.Url,
		&i.Ext,
		&i.PublishedAt,
		&i.Md5,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Calendar)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const upsert = `-- name: Upsert :one
INSERT INTO public.calendar (date_id, source, sid, type, category, country, project, symbol, title, content, importance, url, ext, published_at, md5)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15)
ON CONFLICT (md5) DO UPDATE SET
    date_id = excluded.date_id,
    source = excluded.source,
    sid = excluded.sid,
    type = excluded.type,
    category = excluded.category,
    country = excluded.country,
    project = excluded.project,
    symbol = excluded.symbol,
    title = excluded.title,
    content = excluded.content,
    importance = excluded.importance,
    url = excluded.url,
    ext = excluded.ext,
    published_at = excluded.published_at,
    updated_at = now()
returning id, date_id, sid, source, type, category, country, project, symbol, title, content, importance, url, ext, published_at, md5, created_at, updated_at
`

type UpsertParams struct {
	DateID      int32
	Source      CalendarSource
	Sid         string
	Type        CalendarType
	Category    string
	Country     *string
	Project     *string
	Symbol      *string
	Title       string
	Content     string
	Importance  int32
	Url         string
	Ext         []byte
	PublishedAt time.Time
	Md5         string
}

// -- timeout: 1s
func (q *Queries) Upsert(ctx context.Context, arg UpsertParams) (*Calendar, error) {
	return _Upsert(ctx, q.AsReadOnly(), arg)
}

func _Upsert(ctx context.Context, q CacheQuerierConn, arg UpsertParams) (*Calendar, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "calendar.Upsert", upsert,
		arg.DateID,
		arg.Source,
		arg.Sid,
		arg.Type,
		arg.Category,
		arg.Country,
		arg.Project,
		arg.Symbol,
		arg.Title,
		arg.Content,
		arg.Importance,
		arg.Url,
		arg.Ext,
		arg.PublishedAt,
		arg.Md5)
	var i *Calendar = new(Calendar)
	err := row.Scan(
		&i.ID,
		&i.DateID,
		&i.Sid,
		&i.Source,
		&i.Type,
		&i.Category,
		&i.Country,
		&i.Project,
		&i.Symbol,
		&i.Title,
		&i.Content,
		&i.Importance,
		&i.Url,
		&i.Ext,
		&i.PublishedAt,
		&i.Md5,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Calendar)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,date_id,sid,source,type,category,country,project,symbol,title,content,importance,url,ext,published_at,md5,created_at,updated_at FROM \"calendar\" ORDER BY id,date_id,sid,category,country,project,symbol,title,content,importance,url,published_at,md5,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "calendar.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Calendar
	for rows.Next() {
		var v Calendar
		if err := rows.Scan(&v.ID, &v.DateID, &v.Sid, &v.Source, &v.Type, &v.Category, &v.Country, &v.Project, &v.Symbol, &v.Title, &v.Content, &v.Importance, &v.Url, &v.Ext, &v.PublishedAt, &v.Md5, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"calendar\" (id,date_id,sid,source,type,category,country,project,symbol,title,content,importance,url,ext,published_at,md5,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18);"
	rows := make([]Calendar, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "calendar.Load", sql, row.ID, row.DateID, row.Sid, row.Source, row.Type, row.Category, row.Country, row.Project, row.Symbol, row.Title, row.Content, row.Importance, row.Url, row.Ext, row.PublishedAt, row.Md5, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
