// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package account

import (
	"github.com/stumble/dcache"
	"github.com/stumble/wpgx"
)

// BeforeDump allows you to edit result before dump.
type BeforeDump func(m *Account)

type CacheQuerierConn interface {
	GetCache() *dcache.DCache
	GetConn() wpgx.WQuerier
}

type CacheWGConn interface {
	GetCache() *dcache.DCache
	GetConn() wpgx.WGConn
}

func New(db wpgx.WGConn, cache *dcache.DCache) *Queries {
	return &Queries{db: db, cache: cache}
}

type Queries struct {
	db    wpgx.WGConn
	cache *dcache.DCache
}

var _ CacheWGConn = (*Queries)(nil)

func (q *Queries) GetCache() *dcache.DCache {
	return q.cache
}

func (q *Queries) GetConn() wpgx.WGConn {
	return q.db
}

func (q *Queries) AsReadOnly() *ReadOnlyQueries {
	return &ReadOnlyQueries{
		db:    q.db,
		cache: q.cache,
	}
}

func (q *Queries) WithTx(tx *wpgx.WTx) *Queries {
	return &Queries{
		db:    tx,
		cache: q.cache,
	}
}

func (q *Queries) WithCache(cache *dcache.DCache) *Queries {
	return &Queries{
		db:    q.db,
		cache: cache,
	}
}

func (q *Queries) UseReplica(replicaQuerier wpgx.WQuerier) *ReadOnlyQueries {
	return &ReadOnlyQueries{
		db:    replicaQuerier,
		cache: q.cache,
	}
}

type ReadOnlyQueries struct {
	db    wpgx.WQuerier
	cache *dcache.DCache
}

var _ CacheQuerierConn = (*ReadOnlyQueries)(nil)

func (q *ReadOnlyQueries) WithCache(cache *dcache.DCache) *ReadOnlyQueries {
	return &ReadOnlyQueries{
		db:    q.db,
		cache: cache,
	}
}

func (q *ReadOnlyQueries) GetCache() *dcache.DCache {
	return q.cache
}

func (q *ReadOnlyQueries) GetConn() wpgx.WQuerier {
	return q.db
}

var Schema = `
create type public.account_status as enum (
    'online',
    'offline'
    );

create type public.exchange as enum (
    'binance',
    'okx',
    'binance_test',
    'okx_test'
    );

create type public.algorithm as enum (
    'none',
    'hmac',
    'ed25519',
    'rsa'
    );

create type public.account_type as enum (
    'real',
    'virtual'
    );

create table public.account
(
    id         varchar(32) primary key,
    name       varchar(128)                           not null,
    exchange   public.exchange                        not null default 'binance',
    config     jsonb                                  not null default '{}',
    api_key    text                                   not null,
    api_secret text                                   not null,
    passphrase text                                   not null default '',
    algorithm  public.algorithm                       not null default 'hmac',
    tags       varchar(64)[],
    status     public.account_status                  not null,
    account_type public.account_type                  not null default 'real',
    deleted_at timestamp with time zone,            -- 逻辑删除时间
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

create unique index account_name_idx on public.account (name) WHERE deleted_at IS NULL;
create index idx_account_deleted_at on public.account (deleted_at);
create index idx_account_status on public.account (status);
create index idx_account_account_type on public.account (account_type);
create index idx_account_created_at on public.account (created_at);
`
