// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package account

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const create = `-- name: Create :one
INSERT INTO public.account (id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type)
VALUES ($1,
        $2,
        $3,
        $4, -- config
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11)
returning id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type, deleted_at, created_at, updated_at
`

type CreateParams struct {
	ID          string
	Name        string
	Exchange    Exchange
	Config      []byte
	ApiKey      string
	ApiSecret   string
	Passphrase  string
	Algorithm   Algorithm
	Tags        []string
	Status      AccountStatus
	AccountType AccountType
}

// -- invalidate : [GetById, GetByName, GetDefaultAccounts]
// -- timeout: 1s
func (q *Queries) Create(ctx context.Context, arg CreateParams, getById *string, getByName *string, getDefaultAccounts *Exchange) (*Account, error) {
	return _Create(ctx, q, arg, getById, getByName, getDefaultAccounts)
}

func _Create(ctx context.Context, q CacheWGConn, arg CreateParams, getById *string, getByName *string, getDefaultAccounts *Exchange) (*Account, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "account.Create", create,
		arg.ID,
		arg.Name,
		arg.Exchange,
		arg.Config,
		arg.ApiKey,
		arg.ApiSecret,
		arg.Passphrase,
		arg.Algorithm,
		arg.Tags,
		arg.Status,
		arg.AccountType)
	var i *Account = new(Account)
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Exchange,
		&i.Config,
		&i.ApiKey,
		&i.ApiSecret,
		&i.Passphrase,
		&i.Algorithm,
		&i.Tags,
		&i.Status,
		&i.AccountType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Account)(nil), nil
	} else if err != nil {
		return nil, err
	}

	// invalidate
	_ = q.GetConn().PostExec(func() error {
		anyErr := make(chan error, 3)
		var wg sync.WaitGroup
		wg.Add(3)
		go func() {
			defer wg.Done()
			if getById != nil {
				key := "account:GetById:" + hashIfLong(fmt.Sprintf("%+v", (*getById)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		go func() {
			defer wg.Done()
			if getByName != nil {
				key := "account:GetByName:" + hashIfLong(fmt.Sprintf("%+v", (*getByName)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		go func() {
			defer wg.Done()
			if getDefaultAccounts != nil {
				key := "account:GetDefaultAccounts:" + hashIfLong(fmt.Sprintf("%+v", (*getDefaultAccounts)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		wg.Wait()
		close(anyErr)
		return <-anyErr
	})
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
UPDATE public.account
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

// -- timeout: 5s
func (q *Queries) DeleteAccount(ctx context.Context, id string) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	result, err := q.db.WExec(qctx, "account.DeleteAccount", deleteAccount, id)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const getById = `-- name: GetById :one
SELECT id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type, deleted_at, created_at, updated_at
FROM public.account
WHERE id = $1
  AND deleted_at IS NULL
`

// -- cache: 60s
// -- timeout: 5s
func (q *Queries) GetById(ctx context.Context, id string) (*Account, error) {
	return _GetById(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetById(ctx context.Context, id string) (*Account, error) {
	return _GetById(ctx, q, id)
}

func _GetById(ctx context.Context, q CacheQuerierConn, id string) (*Account, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("account.GetById")
	dbRead := func() (any, time.Duration, error) {
		cacheDuration := time.Duration(time.Millisecond * 60000)
		row := q.GetConn().WQueryRow(qctx, "account.GetById", getById, id)
		var i *Account = new(Account)
		err := row.Scan(
			&i.ID,
			&i.Name,
			&i.Exchange,
			&i.Config,
			&i.ApiKey,
			&i.ApiSecret,
			&i.Passphrase,
			&i.Algorithm,
			&i.Tags,
			&i.Status,
			&i.AccountType,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if err == pgx.ErrNoRows {
			return (*Account)(nil), cacheDuration, nil
		}
		return i, cacheDuration, err
	}
	if q.GetCache() == nil {
		i, _, err := dbRead()
		return i.(*Account), err
	}

	var i *Account
	err := q.GetCache().GetWithTtl(qctx, "account:GetById:"+hashIfLong(fmt.Sprintf("%+v", id)), &i, dbRead, false, false)
	if err != nil {
		return nil, err
	}

	return i, err
}

const getByName = `-- name: GetByName :one
SELECT id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type, deleted_at, created_at, updated_at
FROM public.account
WHERE name = $1
  AND deleted_at IS NULL
`

// -- cache: 60s
// -- timeout: 5s
func (q *Queries) GetByName(ctx context.Context, name string) (*Account, error) {
	return _GetByName(ctx, q.AsReadOnly(), name)
}

func (q *ReadOnlyQueries) GetByName(ctx context.Context, name string) (*Account, error) {
	return _GetByName(ctx, q, name)
}

func _GetByName(ctx context.Context, q CacheQuerierConn, name string) (*Account, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("account.GetByName")
	dbRead := func() (any, time.Duration, error) {
		cacheDuration := time.Duration(time.Millisecond * 60000)
		row := q.GetConn().WQueryRow(qctx, "account.GetByName", getByName, name)
		var i *Account = new(Account)
		err := row.Scan(
			&i.ID,
			&i.Name,
			&i.Exchange,
			&i.Config,
			&i.ApiKey,
			&i.ApiSecret,
			&i.Passphrase,
			&i.Algorithm,
			&i.Tags,
			&i.Status,
			&i.AccountType,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if err == pgx.ErrNoRows {
			return (*Account)(nil), cacheDuration, nil
		}
		return i, cacheDuration, err
	}
	if q.GetCache() == nil {
		i, _, err := dbRead()
		return i.(*Account), err
	}

	var i *Account
	err := q.GetCache().GetWithTtl(qctx, "account:GetByName:"+hashIfLong(fmt.Sprintf("%+v", name)), &i, dbRead, false, false)
	if err != nil {
		return nil, err
	}

	return i, err
}

const getDefaultAccounts = `-- name: GetDefaultAccounts :many
SELECT id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type, deleted_at, created_at, updated_at
FROM public.account
WHERE status = 'online'
  AND exchange = $1
  AND tags @> array ['default']::varchar[]
  AND deleted_at IS NULL
`

// -- cache: 60s
// -- timeout: 1s
func (q *Queries) GetDefaultAccounts(ctx context.Context, exchange Exchange) ([]Account, error) {
	return _GetDefaultAccounts(ctx, q.AsReadOnly(), exchange)
}

func (q *ReadOnlyQueries) GetDefaultAccounts(ctx context.Context, exchange Exchange) ([]Account, error) {
	return _GetDefaultAccounts(ctx, q, exchange)
}

func _GetDefaultAccounts(ctx context.Context, q CacheQuerierConn, exchange Exchange) ([]Account, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("account.GetDefaultAccounts")
	dbRead := func() (any, time.Duration, error) {
		cacheDuration := time.Duration(time.Millisecond * 60000)
		rows, err := q.GetConn().WQuery(qctx, "account.GetDefaultAccounts", getDefaultAccounts, exchange)
		if err != nil {
			return []Account(nil), 0, err
		}
		defer rows.Close()
		var items []Account
		for rows.Next() {
			var i *Account = new(Account)
			if err := rows.Scan(
				&i.ID,
				&i.Name,
				&i.Exchange,
				&i.Config,
				&i.ApiKey,
				&i.ApiSecret,
				&i.Passphrase,
				&i.Algorithm,
				&i.Tags,
				&i.Status,
				&i.AccountType,
				&i.DeletedAt,
				&i.CreatedAt,
				&i.UpdatedAt,
			); err != nil {
				return []Account(nil), 0, err
			}
			items = append(items, *i)
		}
		if err := rows.Err(); err != nil {
			return []Account(nil), 0, err
		}
		return items, cacheDuration, nil
	}
	if q.GetCache() == nil {
		items, _, err := dbRead()
		return items.([]Account), err
	}
	var items []Account
	err := q.GetCache().GetWithTtl(qctx, "account:GetDefaultAccounts:"+hashIfLong(fmt.Sprintf("%+v", exchange)), &items, dbRead, false, false)
	if err != nil {
		return nil, err
	}

	return items, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type, deleted_at, created_at, updated_at
FROM public.account
WHERE status = $1
  AND deleted_at IS NULL
`

// -- timeout: 5s
func (q *Queries) ListAccounts(ctx context.Context, status AccountStatus) ([]Account, error) {
	return _ListAccounts(ctx, q.AsReadOnly(), status)
}

func (q *ReadOnlyQueries) ListAccounts(ctx context.Context, status AccountStatus) ([]Account, error) {
	return _ListAccounts(ctx, q, status)
}

func _ListAccounts(ctx context.Context, q CacheQuerierConn, status AccountStatus) ([]Account, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("account.ListAccounts")
	rows, err := q.GetConn().WQuery(qctx, "account.ListAccounts", listAccounts, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i *Account = new(Account)
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Exchange,
			&i.Config,
			&i.ApiKey,
			&i.ApiSecret,
			&i.Passphrase,
			&i.Algorithm,
			&i.Tags,
			&i.Status,
			&i.AccountType,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const queryAccounts = `-- name: QueryAccounts :many
SELECT id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type, deleted_at, created_at, updated_at
FROM public.account
WHERE id = coalesce($1::varchar, id)
  AND exchange = coalesce($2::exchange, exchange)
  AND ($3::text IS NULL OR name ILIKE concat('%', $3::text, '%'))
  AND status = coalesce($4::account_status, status)
  AND ($5::varchar[] is null or tags @> $5::varchar[])
  AND deleted_at IS NULL
  AND created_at BETWEEN $6::timestamptz AND $7::timestamptz
ORDER BY id DESC
OFFSET $8::int8 LIMIT $9::int8
`

type QueryAccountsParams struct {
	ID             *string
	Exchange       NullExchange
	Name           *string
	Status         NullAccountStatus
	Tags           []string
	CreatedAtStart time.Time
	CreatedAtEnd   time.Time
	Offset         int64
	Limit          int64
}

// -- timeout: 5s
func (q *Queries) QueryAccounts(ctx context.Context, arg QueryAccountsParams) ([]Account, error) {
	return _QueryAccounts(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) QueryAccounts(ctx context.Context, arg QueryAccountsParams) ([]Account, error) {
	return _QueryAccounts(ctx, q, arg)
}

func _QueryAccounts(ctx context.Context, q CacheQuerierConn, arg QueryAccountsParams) ([]Account, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("account.QueryAccounts")
	rows, err := q.GetConn().WQuery(qctx, "account.QueryAccounts", queryAccounts,
		arg.ID,
		arg.Exchange,
		arg.Name,
		arg.Status,
		arg.Tags,
		arg.CreatedAtStart,
		arg.CreatedAtEnd,
		arg.Offset,
		arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i *Account = new(Account)
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Exchange,
			&i.Config,
			&i.ApiKey,
			&i.ApiSecret,
			&i.Passphrase,
			&i.Algorithm,
			&i.Tags,
			&i.Status,
			&i.AccountType,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const queryAccountsCount = `-- name: QueryAccountsCount :one
SELECT COUNT(1)
FROM public.account
WHERE id = coalesce($1::varchar, id)
  AND exchange = coalesce($2::exchange, exchange)
  AND ($3::text IS NULL OR name ILIKE concat('%', $3::text, '%'))
  AND status = coalesce($4::account_status, status)
  AND ($5::varchar[] is null or tags @> $5::varchar[])
  AND deleted_at IS NULL
  AND created_at BETWEEN $6::timestamptz AND $7::timestamptz
`

type QueryAccountsCountParams struct {
	ID             *string
	Exchange       NullExchange
	Name           *string
	Status         NullAccountStatus
	Tags           []string
	CreatedAtStart time.Time
	CreatedAtEnd   time.Time
}

// -- timeout: 5s
func (q *Queries) QueryAccountsCount(ctx context.Context, arg QueryAccountsCountParams) (*int64, error) {
	return _QueryAccountsCount(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) QueryAccountsCount(ctx context.Context, arg QueryAccountsCountParams) (*int64, error) {
	return _QueryAccountsCount(ctx, q, arg)
}

func _QueryAccountsCount(ctx context.Context, q CacheQuerierConn, arg QueryAccountsCountParams) (*int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("account.QueryAccountsCount")
	row := q.GetConn().WQueryRow(qctx, "account.QueryAccountsCount", queryAccountsCount,
		arg.ID,
		arg.Exchange,
		arg.Name,
		arg.Status,
		arg.Tags,
		arg.CreatedAtStart,
		arg.CreatedAtEnd)
	var count *int64 = new(int64)
	err := row.Scan(count)
	if err == pgx.ErrNoRows {
		return (*int64)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return count, err
}

const update = `-- name: Update :one
UPDATE public.account
SET name       = $2,
    api_key    = $3,
    api_secret = $4,
    passphrase = $5,
    algorithm  = $6,
    tags       = $7,
    status     = $8,
    exchange   = $9,
    account_type = $10,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
returning id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type, deleted_at, created_at, updated_at
`

type UpdateParams struct {
	ID          string
	Name        string
	ApiKey      string
	ApiSecret   string
	Passphrase  string
	Algorithm   Algorithm
	Tags        []string
	Status      AccountStatus
	Exchange    Exchange
	AccountType AccountType
}

// -- invalidate : [GetById, GetByName, GetDefaultAccounts]
// -- timeout: 1s
func (q *Queries) Update(ctx context.Context, arg UpdateParams, getById *string, getByName *string, getDefaultAccounts *Exchange) (*Account, error) {
	return _Update(ctx, q, arg, getById, getByName, getDefaultAccounts)
}

func _Update(ctx context.Context, q CacheWGConn, arg UpdateParams, getById *string, getByName *string, getDefaultAccounts *Exchange) (*Account, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "account.Update", update,
		arg.ID,
		arg.Name,
		arg.ApiKey,
		arg.ApiSecret,
		arg.Passphrase,
		arg.Algorithm,
		arg.Tags,
		arg.Status,
		arg.Exchange,
		arg.AccountType)
	var i *Account = new(Account)
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Exchange,
		&i.Config,
		&i.ApiKey,
		&i.ApiSecret,
		&i.Passphrase,
		&i.Algorithm,
		&i.Tags,
		&i.Status,
		&i.AccountType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Account)(nil), nil
	} else if err != nil {
		return nil, err
	}

	// invalidate
	_ = q.GetConn().PostExec(func() error {
		anyErr := make(chan error, 3)
		var wg sync.WaitGroup
		wg.Add(3)
		go func() {
			defer wg.Done()
			if getById != nil {
				key := "account:GetById:" + hashIfLong(fmt.Sprintf("%+v", (*getById)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		go func() {
			defer wg.Done()
			if getByName != nil {
				key := "account:GetByName:" + hashIfLong(fmt.Sprintf("%+v", (*getByName)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		go func() {
			defer wg.Done()
			if getDefaultAccounts != nil {
				key := "account:GetDefaultAccounts:" + hashIfLong(fmt.Sprintf("%+v", (*getDefaultAccounts)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		wg.Wait()
		close(anyErr)
		return <-anyErr
	})
	return i, err
}

const updateRiskConfig = `-- name: UpdateRiskConfig :one
UPDATE public.account
SET config = jsonb_set(
      coalesce(config, '{}'::jsonb),
      '{risk}',
      coalesce($1::jsonb, '{}'::jsonb),
      true
    ),
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, name, exchange, config, api_key, api_secret, passphrase, algorithm, tags, status, account_type, deleted_at, created_at, updated_at
`

type UpdateRiskConfigParams struct {
	Risk []byte
	ID   string
}

// -- invalidate : [GetById, GetByName, GetDefaultAccounts]
// -- timeout: 1s
func (q *Queries) UpdateRiskConfig(ctx context.Context, arg UpdateRiskConfigParams, getById *string, getByName *string, getDefaultAccounts *Exchange) (*Account, error) {
	return _UpdateRiskConfig(ctx, q, arg, getById, getByName, getDefaultAccounts)
}

func _UpdateRiskConfig(ctx context.Context, q CacheWGConn, arg UpdateRiskConfigParams, getById *string, getByName *string, getDefaultAccounts *Exchange) (*Account, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "account.UpdateRiskConfig", updateRiskConfig, arg.Risk, arg.ID)
	var i *Account = new(Account)
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Exchange,
		&i.Config,
		&i.ApiKey,
		&i.ApiSecret,
		&i.Passphrase,
		&i.Algorithm,
		&i.Tags,
		&i.Status,
		&i.AccountType,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Account)(nil), nil
	} else if err != nil {
		return nil, err
	}

	// invalidate
	_ = q.GetConn().PostExec(func() error {
		anyErr := make(chan error, 3)
		var wg sync.WaitGroup
		wg.Add(3)
		go func() {
			defer wg.Done()
			if getById != nil {
				key := "account:GetById:" + hashIfLong(fmt.Sprintf("%+v", (*getById)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		go func() {
			defer wg.Done()
			if getByName != nil {
				key := "account:GetByName:" + hashIfLong(fmt.Sprintf("%+v", (*getByName)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		go func() {
			defer wg.Done()
			if getDefaultAccounts != nil {
				key := "account:GetDefaultAccounts:" + hashIfLong(fmt.Sprintf("%+v", (*getDefaultAccounts)))
				err = q.GetCache().Invalidate(ctx, key)
				if err != nil {
					log.Ctx(ctx).Error().Err(err).Msgf(
						"Failed to invalidate: %s", key)
					anyErr <- err
				}
			}
		}()
		wg.Wait()
		close(anyErr)
		return <-anyErr
	})
	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,name,exchange,config,api_key,api_secret,passphrase,algorithm,tags,status,account_type,deleted_at,created_at,updated_at FROM \"account\" ORDER BY id,name,api_key,api_secret,passphrase,deleted_at,created_at,updated_at ASC;"
	rows, err := q.db.WQuery(ctx, "account.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var v Account
		if err := rows.Scan(&v.ID, &v.Name, &v.Exchange, &v.Config, &v.ApiKey, &v.ApiSecret, &v.Passphrase, &v.Algorithm, &v.Tags, &v.Status, &v.AccountType, &v.DeletedAt, &v.CreatedAt, &v.UpdatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"account\" (id,name,exchange,config,api_key,api_secret,passphrase,algorithm,tags,status,account_type,deleted_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14);"
	rows := make([]Account, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "account.Load", sql, row.ID, row.Name, row.Exchange, row.Config, row.ApiKey, row.ApiSecret, row.Passphrase, row.Algorithm, row.Tags, row.Status, row.AccountType, row.DeletedAt, row.CreatedAt, row.UpdatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
