// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package equity

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rs/zerolog/log"
)

const createEquity = `-- name: CreateEquity :one
INSERT INTO equity (account_id, ts, notional, unrealized_profit)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, ts, notional, unrealized_profit, created_at
`

type CreateEquityParams struct {
	AccountID        string
	Ts               time.Time
	Notional         pgtype.Numeric
	UnrealizedProfit pgtype.Numeric
}

// -- timeout: 1s
func (q *Queries) CreateEquity(ctx context.Context, arg CreateEquityParams) (*Equity, error) {
	return _CreateEquity(ctx, q.AsReadOnly(), arg)
}

func _CreateEquity(ctx context.Context, q CacheQuerierConn, arg CreateEquityParams) (*Equity, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "equity.CreateEquity", createEquity,
		arg.AccountID,
		arg.Ts,
		arg.Notional,
		arg.UnrealizedProfit)
	var i *Equity = new(Equity)
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Ts,
		&i.Notional,
		&i.UnrealizedProfit,
		&i.CreatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Equity)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getEquityBeforeTs = `-- name: GetEquityBeforeTs :one
SELECT id, account_id, ts, notional, unrealized_profit, created_at FROM equity
WHERE account_id = $1 AND ts <= $2
ORDER BY ts DESC
LIMIT 1
`

type GetEquityBeforeTsParams struct {
	AccountID string
	Ts        time.Time
}

// -- timeout: 1s
func (q *Queries) GetEquityBeforeTs(ctx context.Context, arg GetEquityBeforeTsParams) (*Equity, error) {
	return _GetEquityBeforeTs(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetEquityBeforeTs(ctx context.Context, arg GetEquityBeforeTsParams) (*Equity, error) {
	return _GetEquityBeforeTs(ctx, q, arg)
}

func _GetEquityBeforeTs(ctx context.Context, q CacheQuerierConn, arg GetEquityBeforeTsParams) (*Equity, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("equity.GetEquityBeforeTs")
	row := q.GetConn().WQueryRow(qctx, "equity.GetEquityBeforeTs", getEquityBeforeTs, arg.AccountID, arg.Ts)
	var i *Equity = new(Equity)
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Ts,
		&i.Notional,
		&i.UnrealizedProfit,
		&i.CreatedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Equity)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const listEquityByAccountAndRange = `-- name: ListEquityByAccountAndRange :many
SELECT id, account_id, ts, notional, unrealized_profit, created_at FROM equity
WHERE account_id = $1 AND ts >= $2 AND ts <= $3
ORDER BY ts ASC
`

type ListEquityByAccountAndRangeParams struct {
	AccountID string
	Ts        time.Time
	Ts_2      time.Time
}

// -- timeout: 1s
func (q *Queries) ListEquityByAccountAndRange(ctx context.Context, arg ListEquityByAccountAndRangeParams) ([]Equity, error) {
	return _ListEquityByAccountAndRange(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListEquityByAccountAndRange(ctx context.Context, arg ListEquityByAccountAndRangeParams) ([]Equity, error) {
	return _ListEquityByAccountAndRange(ctx, q, arg)
}

func _ListEquityByAccountAndRange(ctx context.Context, q CacheQuerierConn, arg ListEquityByAccountAndRangeParams) ([]Equity, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("equity.ListEquityByAccountAndRange")
	rows, err := q.GetConn().WQuery(qctx, "equity.ListEquityByAccountAndRange", listEquityByAccountAndRange, arg.AccountID, arg.Ts, arg.Ts_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equity
	for rows.Next() {
		var i *Equity = new(Equity)
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Ts,
			&i.Notional,
			&i.UnrealizedProfit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,account_id,ts,notional,unrealized_profit,created_at FROM \"equity\" ORDER BY id,account_id,ts,created_at ASC;"
	rows, err := q.db.WQuery(ctx, "equity.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equity
	for rows.Next() {
		var v Equity
		if err := rows.Scan(&v.ID, &v.AccountID, &v.Ts, &v.Notional, &v.UnrealizedProfit, &v.CreatedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"equity\" (id,account_id,ts,notional,unrealized_profit,created_at) VALUES ($1,$2,$3,$4,$5,$6);"
	rows := make([]Equity, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "equity.Load", sql, row.ID, row.AccountID, row.Ts, row.Notional, row.UnrealizedProfit, row.CreatedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
