// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package snapshot

import (
	"time"
)

type Snapshot struct {
	ID         int32      `json:"id"`
	StrategyID string     `json:"strategy_id"`
	ParentID   int32      `json:"parent_id"`
	Version    string     `json:"version"`
	Code       string     `json:"code"`
	Params     []byte     `json:"params"`
	Signals    []byte     `json:"signals"`
	IsActive   bool       `json:"is_active"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
}
