// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package snapshot

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (strategy_id, parent_id, version, code, params, signals, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, strategy_id, parent_id, version, code, params, signals, is_active, created_at, updated_at, deleted_at
`

type CreateSnapshotParams struct {
	StrategyID string
	ParentID   int32
	Version    string
	Code       string
	Params     []byte
	Signals    []byte
	IsActive   bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// -- timeout: 1s
func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (*Snapshot, error) {
	return _CreateSnapshot(ctx, q.AsReadOnly(), arg)
}

func _CreateSnapshot(ctx context.Context, q CacheQuerierConn, arg CreateSnapshotParams) (*Snapshot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "snapshot.CreateSnapshot", createSnapshot,
		arg.StrategyID,
		arg.ParentID,
		arg.Version,
		arg.Code,
		arg.Params,
		arg.Signals,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt)
	var i *Snapshot = new(Snapshot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.ParentID,
		&i.Version,
		&i.Code,
		&i.Params,
		&i.Signals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Snapshot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const deleteById = `-- name: DeleteById :execrows
UPDATE snapshots
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) DeleteById(ctx context.Context, id int32) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	result, err := q.db.WExec(qctx, "snapshot.DeleteById", deleteById, id)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const deleteByStrategyId = `-- name: DeleteByStrategyId :execrows
UPDATE snapshots
SET deleted_at = CURRENT_TIMESTAMP
WHERE strategy_id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) DeleteByStrategyId(ctx context.Context, strategyID string) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	result, err := q.db.WExec(qctx, "snapshot.DeleteByStrategyId", deleteByStrategyId, strategyID)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const getActicedSnapshot = `-- name: GetActicedSnapshot :one
SELECT id, strategy_id, parent_id, version, code, params, signals, is_active, created_at, updated_at, deleted_at FROM snapshots
WHERE strategy_id = $1 AND is_active = TRUE AND deleted_at IS NULL
LIMIT 1
`

// -- timeout: 1s
func (q *Queries) GetActicedSnapshot(ctx context.Context, strategyID string) (*Snapshot, error) {
	return _GetActicedSnapshot(ctx, q.AsReadOnly(), strategyID)
}

func (q *ReadOnlyQueries) GetActicedSnapshot(ctx context.Context, strategyID string) (*Snapshot, error) {
	return _GetActicedSnapshot(ctx, q, strategyID)
}

func _GetActicedSnapshot(ctx context.Context, q CacheQuerierConn, strategyID string) (*Snapshot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("snapshot.GetActicedSnapshot")
	row := q.GetConn().WQueryRow(qctx, "snapshot.GetActicedSnapshot", getActicedSnapshot, strategyID)
	var i *Snapshot = new(Snapshot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.ParentID,
		&i.Version,
		&i.Code,
		&i.Params,
		&i.Signals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Snapshot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getById = `-- name: GetById :one
SELECT id, strategy_id, parent_id, version, code, params, signals, is_active, created_at, updated_at, deleted_at FROM snapshots
WHERE id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) GetById(ctx context.Context, id int32) (*Snapshot, error) {
	return _GetById(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetById(ctx context.Context, id int32) (*Snapshot, error) {
	return _GetById(ctx, q, id)
}

func _GetById(ctx context.Context, q CacheQuerierConn, id int32) (*Snapshot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("snapshot.GetById")
	row := q.GetConn().WQueryRow(qctx, "snapshot.GetById", getById, id)
	var i *Snapshot = new(Snapshot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.ParentID,
		&i.Version,
		&i.Code,
		&i.Params,
		&i.Signals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Snapshot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getByStrategyIdAndVersion = `-- name: GetByStrategyIdAndVersion :one
SELECT id, strategy_id, parent_id, version, code, params, signals, is_active, created_at, updated_at, deleted_at FROM snapshots
WHERE strategy_id = $1 AND version = $2 AND deleted_at IS NULL
`

type GetByStrategyIdAndVersionParams struct {
	StrategyID string
	Version    string
}

// -- timeout: 1s
func (q *Queries) GetByStrategyIdAndVersion(ctx context.Context, arg GetByStrategyIdAndVersionParams) (*Snapshot, error) {
	return _GetByStrategyIdAndVersion(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) GetByStrategyIdAndVersion(ctx context.Context, arg GetByStrategyIdAndVersionParams) (*Snapshot, error) {
	return _GetByStrategyIdAndVersion(ctx, q, arg)
}

func _GetByStrategyIdAndVersion(ctx context.Context, q CacheQuerierConn, arg GetByStrategyIdAndVersionParams) (*Snapshot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("snapshot.GetByStrategyIdAndVersion")
	row := q.GetConn().WQueryRow(qctx, "snapshot.GetByStrategyIdAndVersion", getByStrategyIdAndVersion, arg.StrategyID, arg.Version)
	var i *Snapshot = new(Snapshot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.ParentID,
		&i.Version,
		&i.Code,
		&i.Params,
		&i.Signals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Snapshot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, strategy_id, parent_id, version, code, params, signals, is_active, created_at, updated_at, deleted_at FROM snapshots
WHERE strategy_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

// -- timeout: 1s
func (q *Queries) GetLatestSnapshot(ctx context.Context, strategyID string) (*Snapshot, error) {
	return _GetLatestSnapshot(ctx, q.AsReadOnly(), strategyID)
}

func (q *ReadOnlyQueries) GetLatestSnapshot(ctx context.Context, strategyID string) (*Snapshot, error) {
	return _GetLatestSnapshot(ctx, q, strategyID)
}

func _GetLatestSnapshot(ctx context.Context, q CacheQuerierConn, strategyID string) (*Snapshot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.GetConn().CountIntent("snapshot.GetLatestSnapshot")
	row := q.GetConn().WQueryRow(qctx, "snapshot.GetLatestSnapshot", getLatestSnapshot, strategyID)
	var i *Snapshot = new(Snapshot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.ParentID,
		&i.Version,
		&i.Code,
		&i.Params,
		&i.Signals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Snapshot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const inactivateSnapshot = `-- name: InactivateSnapshot :execrows
UPDATE snapshots
SET is_active = FALSE
WHERE id = $1 AND deleted_at IS NULL
`

// -- timeout: 1s
func (q *Queries) InactivateSnapshot(ctx context.Context, id int32) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	result, err := q.db.WExec(qctx, "snapshot.InactivateSnapshot", inactivateSnapshot, id)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const updateParams = `-- name: UpdateParams :one
UPDATE snapshots
SET params = $1, 
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, strategy_id, parent_id, version, code, params, signals, is_active, created_at, updated_at, deleted_at
`

type UpdateParamsParams struct {
	Params []byte
	ID     int32
}

// -- timeout: 1s
func (q *Queries) UpdateParams(ctx context.Context, arg UpdateParamsParams) (*Snapshot, error) {
	return _UpdateParams(ctx, q.AsReadOnly(), arg)
}

func _UpdateParams(ctx context.Context, q CacheQuerierConn, arg UpdateParamsParams) (*Snapshot, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "snapshot.UpdateParams", updateParams, arg.Params, arg.ID)
	var i *Snapshot = new(Snapshot)
	err := row.Scan(
		&i.ID,
		&i.StrategyID,
		&i.ParentID,
		&i.Version,
		&i.Code,
		&i.Params,
		&i.Signals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*Snapshot)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,strategy_id,parent_id,version,code,params,signals,is_active,created_at,updated_at,deleted_at FROM \"snapshots\" ORDER BY id,strategy_id,parent_id,version,code,is_active,created_at,updated_at,deleted_at ASC;"
	rows, err := q.db.WQuery(ctx, "snapshot.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var v Snapshot
		if err := rows.Scan(&v.ID, &v.StrategyID, &v.ParentID, &v.Version, &v.Code, &v.Params, &v.Signals, &v.IsActive, &v.CreatedAt, &v.UpdatedAt, &v.DeletedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"snapshots\" (id,strategy_id,parent_id,version,code,params,signals,is_active,created_at,updated_at,deleted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11);"
	rows := make([]Snapshot, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "snapshot.Load", sql, row.ID, row.StrategyID, row.ParentID, row.Version, row.Code, row.Params, row.Signals, row.IsActive, row.CreatedAt, row.UpdatedAt, row.DeletedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
