// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package llm_session

import (
	"time"
)

type LlmSession struct {
	ID           int64      `json:"id"`
	UserID       int64      `json:"user_id"`
	Title        string     `json:"title"`
	Summary      string     `json:"summary"`
	LastDialogID int64      `json:"last_dialog_id"`
	DialogCount  int32      `json:"dialog_count"`
	TurnCount    int32      `json:"turn_count"`
	Stats        []byte     `json:"stats"`
	LastDialogAt *time.Time `json:"last_dialog_at"`
	Status       string     `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}
