// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package llm_session

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const create = `-- name: Create :one
insert into public.llm_session (
  id,
  user_id,
  title,
  summary,
  last_dialog_id,
  dialog_count,
  turn_count,
  stats,
  last_dialog_at,
  status
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) returning id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
`

type CreateParams struct {
	ID           int64
	UserID       int64
	Title        string
	Summary      string
	LastDialogID int64
	DialogCount  int32
	TurnCount    int32
	Stats        []byte
	LastDialogAt *time.Time
	Status       string
}

// -- timeout: 3s
func (q *Queries) Create(ctx context.Context, arg CreateParams) (*LlmSession, error) {
	return _Create(ctx, q.AsReadOnly(), arg)
}

func _Create(ctx context.Context, q CacheQuerierConn, arg CreateParams) (*LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_session.Create", create,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Summary,
		arg.LastDialogID,
		arg.DialogCount,
		arg.TurnCount,
		arg.Stats,
		arg.LastDialogAt,
		arg.Status)
	var i *LlmSession = new(LlmSession)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LastDialogID,
		&i.DialogCount,
		&i.TurnCount,
		&i.Stats,
		&i.LastDialogAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmSession)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const deleteByID = `-- name: DeleteByID :execrows
update public.llm_session
set deleted_at = now(),
    updated_at = now()
where id = $1
  and deleted_at is null
`

// -- timeout: 3s
func (q *Queries) DeleteByID(ctx context.Context, id int64) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	result, err := q.db.WExec(qctx, "llm_session.DeleteByID", deleteByID, id)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const getByID = `-- name: GetByID :one
select id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
from public.llm_session
where id = $1
  and deleted_at is null
`

// -- timeout: 3s
func (q *Queries) GetByID(ctx context.Context, id int64) (*LlmSession, error) {
	return _GetByID(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetByID(ctx context.Context, id int64) (*LlmSession, error) {
	return _GetByID(ctx, q, id)
}

func _GetByID(ctx context.Context, q CacheQuerierConn, id int64) (*LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	q.GetConn().CountIntent("llm_session.GetByID")
	row := q.GetConn().WQueryRow(qctx, "llm_session.GetByID", getByID, id)
	var i *LlmSession = new(LlmSession)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LastDialogID,
		&i.DialogCount,
		&i.TurnCount,
		&i.Stats,
		&i.LastDialogAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmSession)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const listByUserID = `-- name: ListByUserID :many
select id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
from public.llm_session
where user_id = $1
  and deleted_at is null
order by updated_at desc
limit $2 offset $3
`

type ListByUserIDParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

// -- timeout: 5s
func (q *Queries) ListByUserID(ctx context.Context, arg ListByUserIDParams) ([]LlmSession, error) {
	return _ListByUserID(ctx, q.AsReadOnly(), arg)
}

func (q *ReadOnlyQueries) ListByUserID(ctx context.Context, arg ListByUserIDParams) ([]LlmSession, error) {
	return _ListByUserID(ctx, q, arg)
}

func _ListByUserID(ctx context.Context, q CacheQuerierConn, arg ListByUserIDParams) ([]LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("llm_session.ListByUserID")
	rows, err := q.GetConn().WQuery(qctx, "llm_session.ListByUserID", listByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmSession
	for rows.Next() {
		var i *LlmSession = new(LlmSession)
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Summary,
			&i.LastDialogID,
			&i.DialogCount,
			&i.TurnCount,
			&i.Stats,
			&i.LastDialogAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const lockByID = `-- name: LockByID :one
select id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
from public.llm_session
where id = $1
  and deleted_at is null
for update
`

// -- timeout: 3s
func (q *Queries) LockByID(ctx context.Context, id int64) (*LlmSession, error) {
	return _LockByID(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) LockByID(ctx context.Context, id int64) (*LlmSession, error) {
	return _LockByID(ctx, q, id)
}

func _LockByID(ctx context.Context, q CacheQuerierConn, id int64) (*LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	q.GetConn().CountIntent("llm_session.LockByID")
	row := q.GetConn().WQueryRow(qctx, "llm_session.LockByID", lockByID, id)
	var i *LlmSession = new(LlmSession)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LastDialogID,
		&i.DialogCount,
		&i.TurnCount,
		&i.Stats,
		&i.LastDialogAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmSession)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const setRegenerateAnswerID = `-- name: SetRegenerateAnswerID :one
update public.llm_session
set last_dialog_id = $1,
    last_dialog_at = $2,
    updated_at = now()
where id = $3
returning id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
`

type SetRegenerateAnswerIDParams struct {
	LastDialogID int64
	LastDialogAt *time.Time
	ID           int64
}

// -- timeout: 3s
func (q *Queries) SetRegenerateAnswerID(ctx context.Context, arg SetRegenerateAnswerIDParams) (*LlmSession, error) {
	return _SetRegenerateAnswerID(ctx, q.AsReadOnly(), arg)
}

func _SetRegenerateAnswerID(ctx context.Context, q CacheQuerierConn, arg SetRegenerateAnswerIDParams) (*LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_session.SetRegenerateAnswerID", setRegenerateAnswerID, arg.LastDialogID, arg.LastDialogAt, arg.ID)
	var i *LlmSession = new(LlmSession)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LastDialogID,
		&i.DialogCount,
		&i.TurnCount,
		&i.Stats,
		&i.LastDialogAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmSession)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateActivity = `-- name: UpdateActivity :one
update public.llm_session
set last_dialog_id = $1,
    dialog_count = dialog_count + $2,
    turn_count = turn_count + $3,
    last_dialog_at = $4,
    updated_at = now()
where id = $5
returning id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
`

type UpdateActivityParams struct {
	LastDialogID     int64
	DialogCountDelta int32
	TurnCountDelta   int32
	LastDialogAt     *time.Time
	ID               int64
}

// -- timeout: 3s
func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (*LlmSession, error) {
	return _UpdateActivity(ctx, q.AsReadOnly(), arg)
}

func _UpdateActivity(ctx context.Context, q CacheQuerierConn, arg UpdateActivityParams) (*LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_session.UpdateActivity", updateActivity,
		arg.LastDialogID,
		arg.DialogCountDelta,
		arg.TurnCountDelta,
		arg.LastDialogAt,
		arg.ID)
	var i *LlmSession = new(LlmSession)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LastDialogID,
		&i.DialogCount,
		&i.TurnCount,
		&i.Stats,
		&i.LastDialogAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmSession)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateStatus = `-- name: UpdateStatus :one
update public.llm_session
set status = $2,
    updated_at = now()
where id = $1
returning id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
`

type UpdateStatusParams struct {
	ID     int64
	Status string
}

// -- timeout: 3s
func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (*LlmSession, error) {
	return _UpdateStatus(ctx, q.AsReadOnly(), arg)
}

func _UpdateStatus(ctx context.Context, q CacheQuerierConn, arg UpdateStatusParams) (*LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_session.UpdateStatus", updateStatus, arg.ID, arg.Status)
	var i *LlmSession = new(LlmSession)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LastDialogID,
		&i.DialogCount,
		&i.TurnCount,
		&i.Stats,
		&i.LastDialogAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmSession)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateSummary = `-- name: UpdateSummary :one
update public.llm_session
set summary = $2,
    updated_at = now()
where id = $1
returning id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
`

type UpdateSummaryParams struct {
	ID      int64
	Summary string
}

// -- timeout: 3s
func (q *Queries) UpdateSummary(ctx context.Context, arg UpdateSummaryParams) (*LlmSession, error) {
	return _UpdateSummary(ctx, q.AsReadOnly(), arg)
}

func _UpdateSummary(ctx context.Context, q CacheQuerierConn, arg UpdateSummaryParams) (*LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_session.UpdateSummary", updateSummary, arg.ID, arg.Summary)
	var i *LlmSession = new(LlmSession)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LastDialogID,
		&i.DialogCount,
		&i.TurnCount,
		&i.Stats,
		&i.LastDialogAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmSession)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateTitle = `-- name: UpdateTitle :one
update public.llm_session
set title = $2,
    updated_at = now()
where id = $1
returning id, user_id, title, summary, last_dialog_id, dialog_count, turn_count, stats, last_dialog_at, status, created_at, updated_at, deleted_at
`

type UpdateTitleParams struct {
	ID    int64
	Title string
}

// -- timeout: 3s
func (q *Queries) UpdateTitle(ctx context.Context, arg UpdateTitleParams) (*LlmSession, error) {
	return _UpdateTitle(ctx, q.AsReadOnly(), arg)
}

func _UpdateTitle(ctx context.Context, q CacheQuerierConn, arg UpdateTitleParams) (*LlmSession, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_session.UpdateTitle", updateTitle, arg.ID, arg.Title)
	var i *LlmSession = new(LlmSession)
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.LastDialogID,
		&i.DialogCount,
		&i.TurnCount,
		&i.Stats,
		&i.LastDialogAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmSession)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,user_id,title,summary,last_dialog_id,dialog_count,turn_count,stats,last_dialog_at,status,created_at,updated_at,deleted_at FROM \"llm_session\" ORDER BY id,user_id,title,summary,last_dialog_id,dialog_count,turn_count,last_dialog_at,status,created_at,updated_at,deleted_at ASC;"
	rows, err := q.db.WQuery(ctx, "llm_session.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmSession
	for rows.Next() {
		var v LlmSession
		if err := rows.Scan(&v.ID, &v.UserID, &v.Title, &v.Summary, &v.LastDialogID, &v.DialogCount, &v.TurnCount, &v.Stats, &v.LastDialogAt, &v.Status, &v.CreatedAt, &v.UpdatedAt, &v.DeletedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"llm_session\" (id,user_id,title,summary,last_dialog_id,dialog_count,turn_count,stats,last_dialog_at,status,created_at,updated_at,deleted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13);"
	rows := make([]LlmSession, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "llm_session.Load", sql, row.ID, row.UserID, row.Title, row.Summary, row.LastDialogID, row.DialogCount, row.TurnCount, row.Stats, row.LastDialogAt, row.Status, row.CreatedAt, row.UpdatedAt, row.DeletedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
