// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package ledgers

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type WalletType string

const (
	WalletTypeFund   WalletType = "fund"
	WalletTypeTrade  WalletType = "trade"
	WalletTypeSpot   WalletType = "spot"
	WalletTypeFuture WalletType = "future"
	WalletTypeMargin WalletType = "margin"
)

func (e *WalletType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletType(s)
	case string:
		*e = WalletType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletType: %T", src)
	}
	return nil
}

type NullWalletType struct {
	WalletType WalletType
	Valid      bool // Valid is true if WalletType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletType), nil
}

func (e WalletType) Valid() bool {
	switch e {
	case WalletTypeFund,
		WalletTypeTrade,
		WalletTypeSpot,
		WalletTypeFuture,
		WalletTypeMargin:
		return true
	}
	return false
}

func AllWalletTypeValues() []WalletType {
	return []WalletType{
		WalletTypeFund,
		WalletTypeTrade,
		WalletTypeSpot,
		WalletTypeFuture,
		WalletTypeMargin,
	}
}

type Asset struct {
	AccountID     string         `json:"account_id"`
	Exchange      string         `json:"exchange"`
	Asset         string         `json:"asset"`
	WalletType    WalletType     `json:"wallet_type"`
	Total         pgtype.Numeric `json:"total"`
	Frozen        pgtype.Numeric `json:"frozen"`
	OrderOccupied pgtype.Numeric `json:"order_occupied"`
	AvgPrice      pgtype.Numeric `json:"avg_price"`
	LastUpdatedTs time.Time      `json:"last_updated_ts"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}
