// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package symbol_equity

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type SymbolEquity struct {
	ID           int64          `json:"id"`
	AccountID    string         `json:"account_id"`
	Exchange     string         `json:"exchange"`
	Symbol       string         `json:"symbol"`
	NetValue     pgtype.Numeric `json:"net_value"`
	BaseCurrency string         `json:"base_currency"`
	Ts           time.Time      `json:"ts"`
	CreatedAt    time.Time      `json:"created_at"`
}
