// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package risk_event

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiskEvent struct {
	ID        int64          `json:"id"`
	AccountID string         `json:"account_id"`
	Exchange  string         `json:"exchange"`
	Rule      string         `json:"rule"`
	RiskIndex pgtype.Numeric `json:"risk_index"`
	Payload   []byte         `json:"payload"`
	CreatedAt time.Time      `json:"created_at"`
}
