// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork

package llm_dialog

import (
	"time"
)

type LlmDialog struct {
	ID            int64      `json:"id"`
	SessionID     int64      `json:"session_id"`
	DialogID      int64      `json:"dialog_id"`
	Seq           int32      `json:"seq"`
	Role          string     `json:"role"`
	Provider      string     `json:"provider"`
	Model         string     `json:"model"`
	ContentText   string     `json:"content_text"`
	Parts         []byte     `json:"parts"`
	ContextMeta   []byte     `json:"context_meta"`
	CanRegenerate bool       `json:"can_regenerate"`
	Stats         []byte     `json:"stats"`
	Visible       bool       `json:"visible"`
	Status        string     `json:"status"`
	ErrorCode     string     `json:"error_code"`
	ErrorMessage  string     `json:"error_message"`
	StartedAt     *time.Time `json:"started_at"`
	CompletedAt   *time.Time `json:"completed_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	DeletedAt     *time.Time `json:"deleted_at"`
}
