// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.1-wicked-fork
// source: query.sql

package llm_dialog

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sync"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

const create = `-- name: Create :one
insert into public.llm_dialog (
  id,
  session_id,
  seq,
  dialog_id,
  role,
  status,
  content_text,
  parts,
  context_meta,
  stats,
  provider,
  model,
  can_regenerate,
  error_code,
  error_message,
  visible,
  started_at,
  completed_at
) values (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) returning id, session_id, dialog_id, seq, role, provider, model, content_text, parts, context_meta, can_regenerate, stats, visible, status, error_code, error_message, started_at, completed_at, created_at, updated_at, deleted_at
`

type CreateParams struct {
	ID            int64
	SessionID     int64
	Seq           int32
	DialogID      int64
	Role          string
	Status        string
	ContentText   string
	Parts         []byte
	ContextMeta   []byte
	Stats         []byte
	Provider      string
	Model         string
	CanRegenerate bool
	ErrorCode     string
	ErrorMessage  string
	Visible       bool
	StartedAt     *time.Time
	CompletedAt   *time.Time
}

// -- timeout: 3s
func (q *Queries) Create(ctx context.Context, arg CreateParams) (*LlmDialog, error) {
	return _Create(ctx, q.AsReadOnly(), arg)
}

func _Create(ctx context.Context, q CacheQuerierConn, arg CreateParams) (*LlmDialog, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_dialog.Create", create,
		arg.ID,
		arg.SessionID,
		arg.Seq,
		arg.DialogID,
		arg.Role,
		arg.Status,
		arg.ContentText,
		arg.Parts,
		arg.ContextMeta,
		arg.Stats,
		arg.Provider,
		arg.Model,
		arg.CanRegenerate,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Visible,
		arg.StartedAt,
		arg.CompletedAt)
	var i *LlmDialog = new(LlmDialog)
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DialogID,
		&i.Seq,
		&i.Role,
		&i.Provider,
		&i.Model,
		&i.ContentText,
		&i.Parts,
		&i.ContextMeta,
		&i.CanRegenerate,
		&i.Stats,
		&i.Visible,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmDialog)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const deleteBySessionID = `-- name: DeleteBySessionID :execrows
update public.llm_dialog
set deleted_at = now(),
    updated_at = now()
where session_id = $1
  and deleted_at is null
`

// -- timeout: 3s
func (q *Queries) DeleteBySessionID(ctx context.Context, sessionID int64) (int64, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	result, err := q.db.WExec(qctx, "llm_dialog.DeleteBySessionID", deleteBySessionID, sessionID)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected(), nil
}

const getByID = `-- name: GetByID :one
select id, session_id, dialog_id, seq, role, provider, model, content_text, parts, context_meta, can_regenerate, stats, visible, status, error_code, error_message, started_at, completed_at, created_at, updated_at, deleted_at
from public.llm_dialog
where id = $1
  and deleted_at is null
`

// -- timeout: 3s
func (q *Queries) GetByID(ctx context.Context, id int64) (*LlmDialog, error) {
	return _GetByID(ctx, q.AsReadOnly(), id)
}

func (q *ReadOnlyQueries) GetByID(ctx context.Context, id int64) (*LlmDialog, error) {
	return _GetByID(ctx, q, id)
}

func _GetByID(ctx context.Context, q CacheQuerierConn, id int64) (*LlmDialog, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	q.GetConn().CountIntent("llm_dialog.GetByID")
	row := q.GetConn().WQueryRow(qctx, "llm_dialog.GetByID", getByID, id)
	var i *LlmDialog = new(LlmDialog)
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DialogID,
		&i.Seq,
		&i.Role,
		&i.Provider,
		&i.Model,
		&i.ContentText,
		&i.Parts,
		&i.ContextMeta,
		&i.CanRegenerate,
		&i.Stats,
		&i.Visible,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmDialog)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const getLatestAnswerBySessionID = `-- name: GetLatestAnswerBySessionID :one
select id, session_id, dialog_id, seq, role, provider, model, content_text, parts, context_meta, can_regenerate, stats, visible, status, error_code, error_message, started_at, completed_at, created_at, updated_at, deleted_at
from public.llm_dialog
where session_id = $1
  and deleted_at is null
  and role = 'answer'
  and visible = true
order by seq desc
limit 1
`

// -- timeout: 3s
func (q *Queries) GetLatestAnswerBySessionID(ctx context.Context, sessionID int64) (*LlmDialog, error) {
	return _GetLatestAnswerBySessionID(ctx, q.AsReadOnly(), sessionID)
}

func (q *ReadOnlyQueries) GetLatestAnswerBySessionID(ctx context.Context, sessionID int64) (*LlmDialog, error) {
	return _GetLatestAnswerBySessionID(ctx, q, sessionID)
}

func _GetLatestAnswerBySessionID(ctx context.Context, q CacheQuerierConn, sessionID int64) (*LlmDialog, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	q.GetConn().CountIntent("llm_dialog.GetLatestAnswerBySessionID")
	row := q.GetConn().WQueryRow(qctx, "llm_dialog.GetLatestAnswerBySessionID", getLatestAnswerBySessionID, sessionID)
	var i *LlmDialog = new(LlmDialog)
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DialogID,
		&i.Seq,
		&i.Role,
		&i.Provider,
		&i.Model,
		&i.ContentText,
		&i.Parts,
		&i.ContextMeta,
		&i.CanRegenerate,
		&i.Stats,
		&i.Visible,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmDialog)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const hideAnswerByID = `-- name: HideAnswerByID :one
update public.llm_dialog
set visible = false,
    can_regenerate = false,
    updated_at = now()
where id = $1
  and role = 'answer'
  and deleted_at is null
returning id, session_id, dialog_id, seq, role, provider, model, content_text, parts, context_meta, can_regenerate, stats, visible, status, error_code, error_message, started_at, completed_at, created_at, updated_at, deleted_at
`

// -- timeout: 3s
func (q *Queries) HideAnswerByID(ctx context.Context, id int64) (*LlmDialog, error) {
	return _HideAnswerByID(ctx, q.AsReadOnly(), id)
}

func _HideAnswerByID(ctx context.Context, q CacheQuerierConn, id int64) (*LlmDialog, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_dialog.HideAnswerByID", hideAnswerByID, id)
	var i *LlmDialog = new(LlmDialog)
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DialogID,
		&i.Seq,
		&i.Role,
		&i.Provider,
		&i.Model,
		&i.ContentText,
		&i.Parts,
		&i.ContextMeta,
		&i.CanRegenerate,
		&i.Stats,
		&i.Visible,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmDialog)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const listBySessionID = `-- name: ListBySessionID :many
select id, session_id, dialog_id, seq, role, provider, model, content_text, parts, context_meta, can_regenerate, stats, visible, status, error_code, error_message, started_at, completed_at, created_at, updated_at, deleted_at
from public.llm_dialog
where session_id = $1
  and deleted_at is null
  and (role <> 'answer' or visible = true)
order by seq asc
`

// -- timeout: 5s
func (q *Queries) ListBySessionID(ctx context.Context, sessionID int64) ([]LlmDialog, error) {
	return _ListBySessionID(ctx, q.AsReadOnly(), sessionID)
}

func (q *ReadOnlyQueries) ListBySessionID(ctx context.Context, sessionID int64) ([]LlmDialog, error) {
	return _ListBySessionID(ctx, q, sessionID)
}

func _ListBySessionID(ctx context.Context, q CacheQuerierConn, sessionID int64) ([]LlmDialog, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*5000)
	defer cancel()
	q.GetConn().CountIntent("llm_dialog.ListBySessionID")
	rows, err := q.GetConn().WQuery(qctx, "llm_dialog.ListBySessionID", listBySessionID, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmDialog
	for rows.Next() {
		var i *LlmDialog = new(LlmDialog)
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DialogID,
			&i.Seq,
			&i.Role,
			&i.Provider,
			&i.Model,
			&i.ContentText,
			&i.Parts,
			&i.ContextMeta,
			&i.CanRegenerate,
			&i.Stats,
			&i.Visible,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, *i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, err
}

const startAnswerStream = `-- name: StartAnswerStream :one
update public.llm_dialog
set status = 'streaming',
    started_at = coalesce($1::timestamptz, now()),
    completed_at = null,
    updated_at = now()
where id = $2
  and deleted_at is null
returning id, session_id, dialog_id, seq, role, provider, model, content_text, parts, context_meta, can_regenerate, stats, visible, status, error_code, error_message, started_at, completed_at, created_at, updated_at, deleted_at
`

type StartAnswerStreamParams struct {
	StartedAt *time.Time
	ID        int64
}

// -- timeout: 3s
func (q *Queries) StartAnswerStream(ctx context.Context, arg StartAnswerStreamParams) (*LlmDialog, error) {
	return _StartAnswerStream(ctx, q.AsReadOnly(), arg)
}

func _StartAnswerStream(ctx context.Context, q CacheQuerierConn, arg StartAnswerStreamParams) (*LlmDialog, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_dialog.StartAnswerStream", startAnswerStream, arg.StartedAt, arg.ID)
	var i *LlmDialog = new(LlmDialog)
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DialogID,
		&i.Seq,
		&i.Role,
		&i.Provider,
		&i.Model,
		&i.ContentText,
		&i.Parts,
		&i.ContextMeta,
		&i.CanRegenerate,
		&i.Stats,
		&i.Visible,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmDialog)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateAnswerResult = `-- name: UpdateAnswerResult :one
update public.llm_dialog
set status = $1,
    content_text = $2,
    parts = $3,
    context_meta = $4,
    stats = $5,
    provider = $6,
    model = $7,
    error_code = $8,
    error_message = $9,
    completed_at = $10::timestamptz,
    updated_at = now()
where id = $11
  and deleted_at is null
returning id, session_id, dialog_id, seq, role, provider, model, content_text, parts, context_meta, can_regenerate, stats, visible, status, error_code, error_message, started_at, completed_at, created_at, updated_at, deleted_at
`

type UpdateAnswerResultParams struct {
	Status       string
	ContentText  string
	Parts        []byte
	ContextMeta  []byte
	Stats        []byte
	Provider     string
	Model        string
	ErrorCode    string
	ErrorMessage string
	CompletedAt  *time.Time
	ID           int64
}

// -- timeout: 3s
func (q *Queries) UpdateAnswerResult(ctx context.Context, arg UpdateAnswerResultParams) (*LlmDialog, error) {
	return _UpdateAnswerResult(ctx, q.AsReadOnly(), arg)
}

func _UpdateAnswerResult(ctx context.Context, q CacheQuerierConn, arg UpdateAnswerResultParams) (*LlmDialog, error) {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	row := q.GetConn().WQueryRow(qctx, "llm_dialog.UpdateAnswerResult", updateAnswerResult,
		arg.Status,
		arg.ContentText,
		arg.Parts,
		arg.ContextMeta,
		arg.Stats,
		arg.Provider,
		arg.Model,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.CompletedAt,
		arg.ID)
	var i *LlmDialog = new(LlmDialog)
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DialogID,
		&i.Seq,
		&i.Role,
		&i.Provider,
		&i.Model,
		&i.ContentText,
		&i.Parts,
		&i.ContextMeta,
		&i.CanRegenerate,
		&i.Stats,
		&i.Visible,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err == pgx.ErrNoRows {
		return (*LlmDialog)(nil), nil
	} else if err != nil {
		return nil, err
	}

	return i, err
}

const updateCanRegenerateBySessionID = `-- name: UpdateCanRegenerateBySessionID :exec
update public.llm_dialog
set can_regenerate = case when id = $2 then true else false end,
    updated_at = now()
where session_id = $1
  and deleted_at is null
  and role = 'answer'
  and visible = true
`

type UpdateCanRegenerateBySessionIDParams struct {
	SessionID int64
	ID        int64
}

// -- timeout: 3s
func (q *Queries) UpdateCanRegenerateBySessionID(ctx context.Context, arg UpdateCanRegenerateBySessionIDParams) error {
	qctx, cancel := context.WithTimeout(ctx, time.Millisecond*3000)
	defer cancel()
	_, err := q.db.WExec(qctx, "llm_dialog.UpdateCanRegenerateBySessionID", updateCanRegenerateBySessionID, arg.SessionID, arg.ID)
	if err != nil {
		return err
	}

	return nil
}

//// auto generated functions

func (q *Queries) Dump(ctx context.Context, beforeDump ...BeforeDump) ([]byte, error) {
	sql := "SELECT id,session_id,dialog_id,seq,role,provider,model,content_text,parts,context_meta,can_regenerate,stats,visible,status,error_code,error_message,started_at,completed_at,created_at,updated_at,deleted_at FROM \"llm_dialog\" ORDER BY id,session_id,dialog_id,seq,role,provider,model,content_text,can_regenerate,visible,status,error_code,error_message,started_at,completed_at,created_at,updated_at,deleted_at ASC;"
	rows, err := q.db.WQuery(ctx, "llm_dialog.Dump", sql)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmDialog
	for rows.Next() {
		var v LlmDialog
		if err := rows.Scan(&v.ID, &v.SessionID, &v.DialogID, &v.Seq, &v.Role, &v.Provider, &v.Model, &v.ContentText, &v.Parts, &v.ContextMeta, &v.CanRegenerate, &v.Stats, &v.Visible, &v.Status, &v.ErrorCode, &v.ErrorMessage, &v.StartedAt, &v.CompletedAt, &v.CreatedAt, &v.UpdatedAt, &v.DeletedAt); err != nil {
			return nil, err
		}
		for _, applyBeforeDump := range beforeDump {
			applyBeforeDump(&v)
		}
		items = append(items, v)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	bytes, err := json.MarshalIndent(items, "", "  ")
	if err != nil {
		return nil, err
	}
	return bytes, nil
}

func (q *Queries) Load(ctx context.Context, data []byte) error {
	sql := "INSERT INTO \"llm_dialog\" (id,session_id,dialog_id,seq,role,provider,model,content_text,parts,context_meta,can_regenerate,stats,visible,status,error_code,error_message,started_at,completed_at,created_at,updated_at,deleted_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21);"
	rows := make([]LlmDialog, 0)
	err := json.Unmarshal(data, &rows)
	if err != nil {
		return err
	}
	for _, row := range rows {
		_, err := q.db.WExec(ctx, "llm_dialog.Load", sql, row.ID, row.SessionID, row.DialogID, row.Seq, row.Role, row.Provider, row.Model, row.ContentText, row.Parts, row.ContextMeta, row.CanRegenerate, row.Stats, row.Visible, row.Status, row.ErrorCode, row.ErrorMessage, row.StartedAt, row.CompletedAt, row.CreatedAt, row.UpdatedAt, row.DeletedAt)
		if err != nil {
			return err
		}
	}
	return nil
}

func hashIfLong(v string) string {
	if len(v) > 64 {
		hash := sha256.Sum256([]byte(v))
		return "h(" + hex.EncodeToString(hash[:]) + ")"
	}
	return v
}

func ptrStr[T any](v *T) string {
	if v == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%+v", *v)
}

// eliminate unused error
var _ = log.Logger
var _ = fmt.Sprintf("")
var _ = time.Now()
var _ = json.RawMessage{}
var _ = sha256.Sum256(nil)
var _ = hex.EncodeToString(nil)
var _ = sync.WaitGroup{}
